<?php

use Update\Seed;

class AnNazioniTableSeeder extends Seed
{
    /**
     * Auto generated seed file.
     */
    public function run()
    {
        $this->capsule->table('an_nazioni')->truncate();

        $this->capsule->table('an_nazioni')->insert([
            [
                'id' => 2,
                'nome' => 'Algeria',
                'iso2' => 'DZ',
                'name' => 'Algeria',
            ],
            [
                'id' => 3,
                'nome' => 'Andorra',
                'iso2' => 'AD',
                'name' => 'Andorra',
            ],
            [
                'id' => 4,
                'nome' => 'Angola',
                'iso2' => 'AO',
                'name' => 'Angola',
            ],
            [
                'id' => 5,
                'nome' => 'Anguilla',
                'iso2' => 'AI',
                'name' => 'Anguilla',
            ],
            [
                'id' => 6,
                'nome' => 'Antigua e Barbuda',
                'iso2' => 'AG',
                'name' => 'Antigua & Barbuda',
            ],
            [
                'id' => 7,
                'nome' => 'Argentina',
                'iso2' => 'AR',
                'name' => 'Argentina',
            ],
            [
                'id' => 8,
                'nome' => 'Armenia',
                'iso2' => 'AM',
                'name' => 'Armenia',
            ],
            [
                'id' => 9,
                'nome' => 'Aruba',
                'iso2' => 'AW',
                'name' => 'Aruba',
            ],
            [
                'id' => 10,
                'nome' => 'Australia',
                'iso2' => 'AU',
                'name' => 'Australia',
            ],
            [
                'id' => 11,
                'nome' => 'Austria',
                'iso2' => 'AT',
                'name' => 'Austria',
            ],
            [
                'id' => 12,
                'nome' => 'Azerbaijan',
                'iso2' => '',
                'name' => null,
            ],
            [
                'id' => 13,
                'nome' => 'Bahamas',
                'iso2' => 'BS',
                'name' => 'Bahamas',
            ],
            [
                'id' => 14,
                'nome' => 'BAHRAIN',
                'iso2' => '',
                'name' => null,
            ],
            [
                'id' => 15,
                'nome' => 'Barbados',
                'iso2' => 'BB',
                'name' => 'Barbados',
            ],
            [
                'id' => 16,
                'nome' => 'Belgio',
                'iso2' => 'BE',
                'name' => 'Belgium',
            ],
            [
                'id' => 17,
                'nome' => 'Belize',
                'iso2' => 'BZ',
                'name' => 'Belize',
            ],
            [
                'id' => 18,
                'nome' => 'Benin',
                'iso2' => 'BJ',
                'name' => 'Benin',
            ],
            [
                'id' => 19,
                'nome' => 'Bermuda',
                'iso2' => 'BM',
                'name' => 'Bermuda',
            ],
            [
                'id' => 20,
                'nome' => 'Bhutan',
                'iso2' => 'BT',
                'name' => 'Bhutan',
            ],
            [
                'id' => 21,
                'nome' => 'Bolivia',
                'iso2' => 'BO',
                'name' => 'Bolivia',
            ],
            [
                'id' => 22,
                'nome' => 'Bosnia & Herzegovina',
                'iso2' => '',
                'name' => null,
            ],
            [
                'id' => 23,
                'nome' => 'Botswana',
                'iso2' => 'BW',
                'name' => 'Botswana',
            ],
            [
                'id' => 24,
                'nome' => 'Brasile',
                'iso2' => 'BR',
                'name' => 'Brazil',
            ],
            [
                'id' => 25,
                'nome' => 'BRITISH VIRGIN ISLANDS',
                'iso2' => '',
                'name' => null,
            ],
            [
                'id' => 26,
                'nome' => 'Brunei',
                'iso2' => 'BN',
                'name' => 'Brunei',
            ],
            [
                'id' => 27,
                'nome' => 'Bulgaria',
                'iso2' => 'BG',
                'name' => 'Bulgaria',
            ],
            [
                'id' => 28,
                'nome' => 'Burkina Faso',
                'iso2' => 'BF',
                'name' => 'Burkina Faso',
            ],
            [
                'id' => 29,
                'nome' => 'Burundi',
                'iso2' => 'BI',
                'name' => 'Burundi',
            ],
            [
                'id' => 30,
                'nome' => 'Cambogia',
                'iso2' => 'KH',
                'name' => 'Cambodia',
            ],
            [
                'id' => 31,
                'nome' => 'Canada',
                'iso2' => 'CA',
                'name' => 'Canada',
            ],
            [
                'id' => 32,
                'nome' => 'Capo Verde',
                'iso2' => 'CV',
                'name' => 'Cape Verde',
            ],
            [
                'id' => 33,
                'nome' => 'CAYMAN ISLANDS',
                'iso2' => '',
                'name' => null,
            ],
            [
                'id' => 34,
                'nome' => 'CHAD',
                'iso2' => '',
                'name' => null,
            ],
            [
                'id' => 35,
                'nome' => 'CHILE',
                'iso2' => '',
                'name' => null,
            ],
            [
                'id' => 36,
                'nome' => 'China',
                'iso2' => '',
                'name' => null,
            ],
            [
                'id' => 37,
                'nome' => 'Colombia',
                'iso2' => 'CO',
                'name' => 'Colombia',
            ],
            [
                'id' => 38,
                'nome' => 'COMOROS',
                'iso2' => '',
                'name' => null,
            ],
            [
                'id' => 39,
                'nome' => 'COOK ISLANDS',
                'iso2' => '',
                'name' => null,
            ],
            [
                'id' => 40,
                'nome' => 'Costa Rica',
                'iso2' => 'CR',
                'name' => 'Costa Rica',
            ],
            [
                'id' => 41,
                'nome' => 'Croazia',
                'iso2' => 'HR',
                'name' => 'Croatia',
            ],
            [
                'id' => 42,
                'nome' => 'Cipro',
                'iso2' => 'CY',
                'name' => 'Cyprus',
            ],
            [
                'id' => 43,
                'nome' => 'Repubblica ceca',
                'iso2' => 'CZ',
                'name' => 'Czechia',
            ],
            [
                'id' => 44,
                'nome' => 'Repubblica Democratica del Congo',
                'iso2' => '',
                'name' => null,
            ],
            [
                'id' => 45,
                'nome' => 'Danimarca',
                'iso2' => 'DK',
                'name' => 'Denmark',
            ],
            [
                'id' => 46,
                'nome' => 'DJIBOUTI',
                'iso2' => '',
                'name' => null,
            ],
            [
                'id' => 47,
                'nome' => 'Dominica',
                'iso2' => 'DM',
                'name' => 'Dominica',
            ],
            [
                'id' => 48,
                'nome' => 'Repubblica Dominicana',
                'iso2' => 'DO',
                'name' => 'Dominican Republic',
            ],
            [
                'id' => 49,
                'nome' => 'Ecuador',
                'iso2' => 'EC',
                'name' => 'Ecuador',
            ],
            [
                'id' => 50,
                'nome' => 'El Salvador',
                'iso2' => 'SV',
                'name' => 'El Salvador',
            ],
            [
                'id' => 51,
                'nome' => 'Eritrea',
                'iso2' => 'ER',
                'name' => 'Eritrea',
            ],
            [
                'id' => 52,
                'nome' => 'Estonia',
                'iso2' => 'EE',
                'name' => 'Estonia',
            ],
            [
                'id' => 53,
                'nome' => 'ETHIOPIA',
                'iso2' => '',
                'name' => null,
            ],
            [
                'id' => 54,
                'nome' => 'FALKLAND ISLANDS',
                'iso2' => '',
                'name' => null,
            ],
            [
                'id' => 55,
                'nome' => 'FAROE ISLANDS',
                'iso2' => '',
                'name' => null,
            ],
            [
                'id' => 56,
                'nome' => 'Micronesia',
                'iso2' => 'FM',
                'name' => 'Micronesia',
            ],
            [
                'id' => 57,
                'nome' => 'FIJI',
                'iso2' => '',
                'name' => null,
            ],
            [
                'id' => 58,
                'nome' => 'Finlandia',
                'iso2' => 'FI',
                'name' => 'Finland',
            ],
            [
                'id' => 59,
                'nome' => 'Francia',
                'iso2' => 'FR',
                'name' => 'France',
            ],
            [
                'id' => 60,
                'nome' => 'FRENCH GUIANA',
                'iso2' => '',
                'name' => null,
            ],
            [
                'id' => 61,
                'nome' => 'FRENCH POLYNESIA',
                'iso2' => '',
                'name' => null,
            ],
            [
                'id' => 62,
                'nome' => 'Gabon',
                'iso2' => 'GA',
                'name' => 'Gabon',
            ],
            [
                'id' => 63,
                'nome' => 'Gambia',
                'iso2' => 'GM',
                'name' => 'Gambia',
            ],
            [
                'id' => 64,
                'nome' => 'Germania',
                'iso2' => 'DE',
                'name' => 'Germany',
            ],
            [
                'id' => 65,
                'nome' => 'GIBRALTAR',
                'iso2' => '',
                'name' => null,
            ],
            [
                'id' => 66,
                'nome' => 'Grecia',
                'iso2' => 'GR',
                'name' => 'Greece',
            ],
            [
                'id' => 67,
                'nome' => 'GREENLAND',
                'iso2' => '',
                'name' => null,
            ],
            [
                'id' => 68,
                'nome' => 'Grenada',
                'iso2' => 'GD',
                'name' => 'Grenada',
            ],
            [
                'id' => 69,
                'nome' => 'GUADELOUPE',
                'iso2' => '',
                'name' => null,
            ],
            [
                'id' => 70,
                'nome' => 'Guatemala',
                'iso2' => 'GT',
                'name' => 'Guatemala',
            ],
            [
                'id' => 71,
                'nome' => 'Guinea',
                'iso2' => 'GN',
                'name' => 'Guinea',
            ],
            [
                'id' => 72,
                'nome' => 'Guinea-Bissau',
                'iso2' => 'GW',
                'name' => 'Guinea-Bissau',
            ],
            [
                'id' => 73,
                'nome' => 'Guyana',
                'iso2' => 'GY',
                'name' => 'Guyana',
            ],
            [
                'id' => 74,
                'nome' => 'Honduras',
                'iso2' => 'HN',
                'name' => 'Honduras',
            ],
            [
                'id' => 75,
                'nome' => 'RAS di Hong Kong',
                'iso2' => 'HK',
                'name' => 'Hong Kong SAR China',
            ],
            [
                'id' => 76,
                'nome' => 'Ungheria',
                'iso2' => 'HU',
                'name' => 'Hungary',
            ],
            [
                'id' => 77,
                'nome' => 'Islanda',
                'iso2' => 'IS',
                'name' => 'Iceland',
            ],
            [
                'id' => 78,
                'nome' => 'India',
                'iso2' => 'IN',
                'name' => 'India',
            ],
            [
                'id' => 79,
                'nome' => 'Indonesia',
                'iso2' => 'ID',
                'name' => 'Indonesia',
            ],
            [
                'id' => 80,
                'nome' => 'Irlanda',
                'iso2' => 'IE',
                'name' => 'Ireland',
            ],
            [
                'id' => 81,
                'nome' => 'Israele',
                'iso2' => 'IL',
                'name' => 'Israel',
            ],
            [
                'id' => 82,
                'nome' => 'Italia',
                'iso2' => 'IT',
                'name' => 'Italy',
            ],
            [
                'id' => 83,
                'nome' => 'JAMAICA',
                'iso2' => '',
                'name' => null,
            ],
            [
                'id' => 84,
                'nome' => 'Giappone',
                'iso2' => 'JP',
                'name' => 'Japan',
            ],
            [
                'id' => 85,
                'nome' => 'JORDAN',
                'iso2' => '',
                'name' => null,
            ],
            [
                'id' => 86,
                'nome' => 'KAZAKHSTAN',
                'iso2' => '',
                'name' => null,
            ],
            [
                'id' => 87,
                'nome' => 'Kenya',
                'iso2' => 'KE',
                'name' => 'Kenya',
            ],
            [
                'id' => 88,
                'nome' => 'Kiribati',
                'iso2' => 'KI',
                'name' => 'Kiribati',
            ],
            [
                'id' => 89,
                'nome' => 'Kuwait',
                'iso2' => 'KW',
                'name' => 'Kuwait',
            ],
            [
                'id' => 90,
                'nome' => 'KYRGYZSTAN',
                'iso2' => '',
                'name' => null,
            ],
            [
                'id' => 91,
                'nome' => 'Laos',
                'iso2' => 'LA',
                'name' => 'Laos',
            ],
            [
                'id' => 92,
                'nome' => 'LATVIA',
                'iso2' => '',
                'name' => null,
            ],
            [
                'id' => 93,
                'nome' => 'Lesotho',
                'iso2' => 'LS',
                'name' => 'Lesotho',
            ],
            [
                'id' => 94,
                'nome' => 'Liechtenstein',
                'iso2' => 'LI',
                'name' => 'Liechtenstein',
            ],
            [
                'id' => 95,
                'nome' => 'Lituania',
                'iso2' => 'LT',
                'name' => 'Lithuania',
            ],
            [
                'id' => 96,
                'nome' => 'Lussemburgo',
                'iso2' => 'LU',
                'name' => 'Luxembourg',
            ],
            [
                'id' => 97,
                'nome' => 'Madagascar',
                'iso2' => 'MG',
                'name' => 'Madagascar',
            ],
            [
                'id' => 98,
                'nome' => 'Malawi',
                'iso2' => 'MW',
                'name' => 'Malawi',
            ],
            [
                'id' => 99,
                'nome' => 'Malesia',
                'iso2' => 'MY',
                'name' => 'Malaysia',
            ],
            [
                'id' => 100,
                'nome' => 'Maldive',
                'iso2' => 'MV',
                'name' => 'Maldives',
            ],
            [
                'id' => 101,
                'nome' => 'Mali',
                'iso2' => 'ML',
                'name' => 'Mali',
            ],
            [
                'id' => 102,
                'nome' => 'Malta',
                'iso2' => 'MT',
                'name' => 'Malta',
            ],
            [
                'id' => 103,
                'nome' => 'MARSHALL ISLANDS',
                'iso2' => '',
                'name' => null,
            ],
            [
                'id' => 104,
                'nome' => 'MARTINIQUE',
                'iso2' => '',
                'name' => null,
            ],
            [
                'id' => 105,
                'nome' => 'Mauritania',
                'iso2' => 'MR',
                'name' => 'Mauritania',
            ],
            [
                'id' => 106,
                'nome' => 'Mauritius',
                'iso2' => 'MU',
                'name' => 'Mauritius',
            ],
            [
                'id' => 107,
                'nome' => 'Mayotte',
                'iso2' => 'YT',
                'name' => 'Mayotte',
            ],
            [
                'id' => 108,
                'nome' => 'Messico',
                'iso2' => 'MX',
                'name' => 'Mexico',
            ],
            [
                'id' => 109,
                'nome' => 'Mongolia',
                'iso2' => 'MN',
                'name' => 'Mongolia',
            ],
            [
                'id' => 110,
                'nome' => 'Montserrat',
                'iso2' => 'MS',
                'name' => 'Montserrat',
            ],
            [
                'id' => 111,
                'nome' => 'Marocco',
                'iso2' => 'MA',
                'name' => 'Morocco',
            ],
            [
                'id' => 112,
                'nome' => 'Mozambico',
                'iso2' => 'MZ',
                'name' => 'Mozambique',
            ],
            [
                'id' => 113,
                'nome' => 'Namibia',
                'iso2' => 'NA',
                'name' => 'Namibia',
            ],
            [
                'id' => 114,
                'nome' => 'Nauru',
                'iso2' => 'NR',
                'name' => 'Nauru',
            ],
            [
                'id' => 115,
                'nome' => 'Nepal',
                'iso2' => 'NP',
                'name' => 'Nepal',
            ],
            [
                'id' => 116,
                'nome' => 'Paesi Bassi',
                'iso2' => 'NL',
                'name' => 'Netherlands',
            ],
            [
                'id' => 117,
                'nome' => 'NETHERLANDS ANTILLES',
                'iso2' => '',
                'name' => null,
            ],
            [
                'id' => 118,
                'nome' => 'Nuova Caledonia',
                'iso2' => 'NC',
                'name' => 'New Caledonia',
            ],
            [
                'id' => 119,
                'nome' => 'Nuova Zelanda',
                'iso2' => 'NZ',
                'name' => 'New Zealand',
            ],
            [
                'id' => 120,
                'nome' => 'Nicaragua',
                'iso2' => 'NI',
                'name' => 'Nicaragua',
            ],
            [
                'id' => 121,
                'nome' => 'Nigeria',
                'iso2' => 'NG',
                'name' => 'Nigeria',
            ],
            [
                'id' => 122,
                'nome' => 'Niue',
                'iso2' => 'NU',
                'name' => 'Niue',
            ],
            [
                'id' => 123,
                'nome' => 'NORFOLK ISLAND',
                'iso2' => '',
                'name' => null,
            ],
            [
                'id' => 124,
                'nome' => 'Norway',
                'iso2' => '',
                'name' => null,
            ],
            [
                'id' => 125,
                'nome' => 'Oman',
                'iso2' => 'OM',
                'name' => 'Oman',
            ],
            [
                'id' => 126,
                'nome' => 'Palau',
                'iso2' => 'PW',
                'name' => 'Palau',
            ],
            [
                'id' => 127,
                'nome' => 'Panamá',
                'iso2' => 'PA',
                'name' => 'Panama',
            ],
            [
                'id' => 128,
                'nome' => 'Papua Nuova Guinea',
                'iso2' => 'PG',
                'name' => 'Papua New Guinea',
            ],
            [
                'id' => 129,
                'nome' => 'Perù',
                'iso2' => 'PE',
                'name' => 'Peru',
            ],
            [
                'id' => 130,
                'nome' => 'Filippine',
                'iso2' => 'PH',
                'name' => 'Philippines',
            ],
            [
                'id' => 131,
                'nome' => 'PITCAIRN ISLANDS',
                'iso2' => '',
                'name' => null,
            ],
            [
                'id' => 132,
                'nome' => 'Polonia',
                'iso2' => 'PL',
                'name' => 'Poland',
            ],
            [
                'id' => 133,
                'nome' => 'Portogallo',
                'iso2' => 'PT',
                'name' => 'Portugal',
            ],
            [
                'id' => 134,
                'nome' => 'Qatar',
                'iso2' => 'QA',
                'name' => 'Qatar',
            ],
            [
                'id' => 135,
                'nome' => 'REPUBBLICA DEL CONGO',
                'iso2' => '',
                'name' => null,
            ],
            [
                'id' => 136,
                'nome' => 'REUNION',
                'iso2' => '',
                'name' => null,
            ],
            [
                'id' => 137,
                'nome' => 'Romania',
                'iso2' => 'RO',
                'name' => 'Romania',
            ],
            [
                'id' => 138,
                'nome' => 'Russia',
                'iso2' => 'RU',
                'name' => 'Russia',
            ],
            [
                'id' => 139,
                'nome' => 'Ruanda',
                'iso2' => 'RW',
                'name' => 'Rwanda',
            ],
            [
                'id' => 140,
                'nome' => 'Saint Vincent e Grenadines',
                'iso2' => 'VC',
                'name' => 'St. Vincent & Grenadines',
            ],
            [
                'id' => 141,
                'nome' => 'Samoa',
                'iso2' => 'WS',
                'name' => 'Samoa',
            ],
            [
                'id' => 142,
                'nome' => 'San Marino',
                'iso2' => 'SM',
                'name' => 'San Marino',
            ],
            [
                'id' => 144,
                'nome' => 'SAUDI ARABIA',
                'iso2' => '',
                'name' => null,
            ],
            [
                'id' => 145,
                'nome' => 'Senegal',
                'iso2' => 'SN',
                'name' => 'Senegal',
            ],
            [
                'id' => 146,
                'nome' => 'Seychelles',
                'iso2' => 'SC',
                'name' => 'Seychelles',
            ],
            [
                'id' => 147,
                'nome' => 'Sierra Leone',
                'iso2' => 'SL',
                'name' => 'Sierra Leone',
            ],
            [
                'id' => 148,
                'nome' => 'Singapore',
                'iso2' => 'SG',
                'name' => 'Singapore',
            ],
            [
                'id' => 149,
                'nome' => 'Slovacchia',
                'iso2' => 'SK',
                'name' => 'Slovakia',
            ],
            [
                'id' => 150,
                'nome' => 'Slovenia',
                'iso2' => 'SI',
                'name' => 'Slovenia',
            ],
            [
                'id' => 151,
                'nome' => 'SOLOMON ISLANDS',
                'iso2' => '',
                'name' => null,
            ],
            [
                'id' => 152,
                'nome' => 'Somalia',
                'iso2' => 'SO',
                'name' => 'Somalia',
            ],
            [
                'id' => 153,
                'nome' => 'South Africa',
                'iso2' => '',
                'name' => null,
            ],
            [
                'id' => 154,
                'nome' => 'Corea del Sud',
                'iso2' => 'KR',
                'name' => 'South Korea',
            ],
            [
                'id' => 155,
                'nome' => 'Spagna',
                'iso2' => 'ES',
                'name' => 'Spain',
            ],
            [
                'id' => 156,
                'nome' => 'Sri Lanka',
                'iso2' => 'LK',
                'name' => 'Sri Lanka',
            ],
            [
                'id' => 157,
                'nome' => 'ST. HELENA',
                'iso2' => '',
                'name' => null,
            ],
            [
                'id' => 158,
                'nome' => 'Saint Kitts e Nevis',
                'iso2' => 'KN',
                'name' => 'St. Kitts & Nevis',
            ],
            [
                'id' => 159,
                'nome' => 'ST. LUCIA',
                'iso2' => '',
                'name' => null,
            ],
            [
                'id' => 160,
                'nome' => 'St. Pierre & Miquelon',
                'iso2' => '',
                'name' => null,
            ],
            [
                'id' => 161,
                'nome' => 'Suriname',
                'iso2' => 'SR',
                'name' => 'Suriname',
            ],
            [
                'id' => 162,
                'nome' => 'Svalbard e Jan Mayen',
                'iso2' => 'SJ',
                'name' => 'Svalbard & Jan Mayen',
            ],
            [
                'id' => 163,
                'nome' => 'Swaziland',
                'iso2' => 'SZ',
                'name' => 'Swaziland',
            ],
            [
                'id' => 164,
                'nome' => 'Svezia',
                'iso2' => 'SE',
                'name' => 'Sweden',
            ],
            [
                'id' => 165,
                'nome' => 'Svizzera',
                'iso2' => 'CH',
                'name' => 'Switzerland',
            ],
            [
                'id' => 166,
                'nome' => 'Taiwan',
                'iso2' => 'TW',
                'name' => 'Taiwan',
            ],
            [
                'id' => 167,
                'nome' => 'TAJIKISTAN',
                'iso2' => '',
                'name' => null,
            ],
            [
                'id' => 168,
                'nome' => 'Tanzania',
                'iso2' => 'TZ',
                'name' => 'Tanzania',
            ],
            [
                'id' => 169,
                'nome' => 'THAILAND',
                'iso2' => '',
                'name' => null,
            ],
            [
                'id' => 170,
                'nome' => 'Togo',
                'iso2' => 'TG',
                'name' => 'Togo',
            ],
            [
                'id' => 171,
                'nome' => 'Tonga',
                'iso2' => 'TO',
                'name' => 'Tonga',
            ],
            [
                'id' => 172,
                'nome' => 'Trinidad e Tobago',
                'iso2' => 'TT',
                'name' => 'Trinidad & Tobago',
            ],
            [
                'id' => 173,
                'nome' => 'Tunisia',
                'iso2' => 'TN',
                'name' => 'Tunisia',
            ],
            [
                'id' => 174,
                'nome' => 'Turchia',
                'iso2' => 'TR',
                'name' => 'Turkey',
            ],
            [
                'id' => 175,
                'nome' => 'Turkmenistan',
                'iso2' => 'TM',
                'name' => 'Turkmenistan',
            ],
            [
                'id' => 176,
                'nome' => 'Isole Turks e Caicos',
                'iso2' => 'TC',
                'name' => 'Turks & Caicos Islands',
            ],
            [
                'id' => 177,
                'nome' => 'Tuvalu',
                'iso2' => 'TV',
                'name' => 'Tuvalu',
            ],
            [
                'id' => 178,
                'nome' => 'Uganda',
                'iso2' => 'UG',
                'name' => 'Uganda',
            ],
            [
                'id' => 179,
                'nome' => 'Ucraina',
                'iso2' => 'UA',
                'name' => 'Ukraine',
            ],
            [
                'id' => 180,
                'nome' => 'Emirati Arabi Uniti',
                'iso2' => 'AE',
                'name' => 'United Arab Emirates',
            ],
            [
                'id' => 181,
                'nome' => 'Regno Unito',
                'iso2' => 'GB',
                'name' => 'United Kingdom',
            ],
            [
                'id' => 182,
                'nome' => 'Stati Uniti',
                'iso2' => 'US',
                'name' => 'United States',
            ],
            [
                'id' => 183,
                'nome' => 'Uruguay',
                'iso2' => 'UY',
                'name' => 'Uruguay',
            ],
            [
                'id' => 184,
                'nome' => 'Vanuatu',
                'iso2' => 'VU',
                'name' => 'Vanuatu',
            ],
            [
                'id' => 185,
                'nome' => 'Città del Vaticano',
                'iso2' => 'VA',
                'name' => 'Vatican City',
            ],
            [
                'id' => 186,
                'nome' => 'Venezuela',
                'iso2' => 'VE',
                'name' => 'Venezuela',
            ],
            [
                'id' => 187,
                'nome' => 'Vietnam',
                'iso2' => 'VN',
                'name' => 'Vietnam',
            ],
            [
                'id' => 188,
                'nome' => 'Wallis & Futuna',
                'iso2' => '',
                'name' => null,
            ],
            [
                'id' => 189,
                'nome' => 'Yemen',
                'iso2' => 'YE',
                'name' => 'Yemen',
            ],
            [
                'id' => 190,
                'nome' => 'Zambia',
                'iso2' => 'ZM',
                'name' => 'Zambia',
            ],
            [
                'id' => 193,
                'nome' => 'Albania',
                'iso2' => 'AL',
                'name' => 'Albania',
            ],
            [
                'id' => 194,
                'nome' => 'Afghanistan',
                'iso2' => 'AF',
                'name' => 'Afghanistan',
            ],
            [
                'id' => 195,
                'nome' => 'Altre isole americane del Pacifico',
                'iso2' => 'UM',
                'name' => 'U.S. Outlying Islands',
            ],
            [
                'id' => 196,
                'nome' => 'Antartide',
                'iso2' => 'AQ',
                'name' => 'Antarctica',
            ],
            [
                'id' => 197,
                'nome' => 'Bangladesh',
                'iso2' => 'BD',
                'name' => 'Bangladesh',
            ],
            [
                'id' => 198,
                'nome' => 'Bielorussia',
                'iso2' => 'BY',
                'name' => 'Belarus',
            ],
            [
                'id' => 199,
                'nome' => 'Camerun',
                'iso2' => 'CM',
                'name' => 'Cameroon',
            ],
            [
                'id' => 200,
                'nome' => 'Caraibi olandesi',
                'iso2' => 'BQ',
                'name' => 'Caribbean Netherlands',
            ],
            [
                'id' => 201,
                'nome' => 'Ceuta e Melilla',
                'iso2' => 'EA',
                'name' => 'Ceuta & Melilla',
            ],
            [
                'id' => 202,
                'nome' => 'Corea del Nord',
                'iso2' => 'KP',
                'name' => 'North Korea',
            ],
            [
                'id' => 203,
                'nome' => 'Costa d’Avorio',
                'iso2' => 'CI',
                'name' => 'Côte d’Ivoire',
            ],
            [
                'id' => 204,
                'nome' => 'Cuba',
                'iso2' => 'CU',
                'name' => 'Cuba',
            ],
            [
                'id' => 205,
                'nome' => 'Curaçao',
                'iso2' => 'CW',
                'name' => 'Curaçao',
            ],
            [
                'id' => 206,
                'nome' => 'Diego Garcia',
                'iso2' => 'DG',
                'name' => 'Diego Garcia',
            ],
            [
                'id' => 207,
                'nome' => 'Egitto',
                'iso2' => 'EG',
                'name' => 'Egypt',
            ],
            [
                'id' => 208,
                'nome' => 'Eurozone',
                'iso2' => 'EZ',
                'name' => 'Eurozone',
            ],
            [
                'id' => 209,
                'nome' => 'Georgia',
                'iso2' => 'GE',
                'name' => 'Georgia',
            ],
            [
                'id' => 210,
                'nome' => 'Georgia del Sud e Sandwich australi',
                'iso2' => 'GS',
                'name' => 'South Georgia & South Sandwich Islands',
            ],
            [
                'id' => 211,
                'nome' => 'Ghana',
                'iso2' => 'GH',
                'name' => 'Ghana',
            ],
            [
                'id' => 212,
                'nome' => 'Guam',
                'iso2' => 'GU',
                'name' => 'Guam',
            ],
            [
                'id' => 213,
                'nome' => 'Guernsey',
                'iso2' => 'GG',
                'name' => 'Guernsey',
            ],
            [
                'id' => 214,
                'nome' => 'Guinea Equatoriale',
                'iso2' => 'GQ',
                'name' => 'Equatorial Guinea',
            ],
            [
                'id' => 215,
                'nome' => 'Haiti',
                'iso2' => 'HT',
                'name' => 'Haiti',
            ],
            [
                'id' => 216,
                'nome' => 'Iran',
                'iso2' => 'IR',
                'name' => 'Iran',
            ],
            [
                'id' => 217,
                'nome' => 'Iraq',
                'iso2' => 'IQ',
                'name' => 'Iraq',
            ],
            [
                'id' => 218,
                'nome' => 'Isola Ascensione',
                'iso2' => 'AC',
                'name' => 'Ascension Island',
            ],
            [
                'id' => 219,
                'nome' => 'Isola Christmas',
                'iso2' => 'CX',
                'name' => 'Christmas Island',
            ],
            [
                'id' => 220,
                'nome' => 'Isola di Man',
                'iso2' => 'IM',
                'name' => 'Isle of Man',
            ],
            [
                'id' => 221,
                'nome' => 'Isole Åland',
                'iso2' => 'AX',
                'name' => 'Åland Islands',
            ],
            [
                'id' => 222,
                'nome' => 'Isole Canarie',
                'iso2' => 'IC',
                'name' => 'Canary Islands',
            ],
            [
                'id' => 223,
            'nome' => 'Isole Cocos (Keeling)',
                'iso2' => 'CC',
            'name' => 'Cocos (Keeling) Islands',
            ],
            [
                'id' => 224,
                'nome' => 'Isole Marianne settentrionali',
                'iso2' => 'MP',
                'name' => 'Northern Mariana Islands',
            ],
            [
                'id' => 225,
                'nome' => 'Isole Vergini Americane',
                'iso2' => 'VI',
                'name' => 'U.S. Virgin Islands',
            ],
            [
                'id' => 226,
                'nome' => 'Jersey',
                'iso2' => 'JE',
                'name' => 'Jersey',
            ],
            [
                'id' => 227,
                'nome' => 'Kosovo',
                'iso2' => 'XK',
                'name' => 'Kosovo',
            ],
            [
                'id' => 228,
                'nome' => 'Libano',
                'iso2' => 'LB',
                'name' => 'Lebanon',
            ],
            [
                'id' => 229,
                'nome' => 'Liberia',
                'iso2' => 'LR',
                'name' => 'Liberia',
            ],
            [
                'id' => 230,
                'nome' => 'Libia',
                'iso2' => 'LY',
                'name' => 'Libya',
            ],
            [
                'id' => 231,
                'nome' => 'Moldavia',
                'iso2' => 'MD',
                'name' => 'Moldova',
            ],
            [
                'id' => 232,
                'nome' => 'Monaco',
                'iso2' => 'MC',
                'name' => 'Monaco',
            ],
            [
                'id' => 233,
                'nome' => 'Montenegro',
                'iso2' => 'ME',
                'name' => 'Montenegro',
            ],
            [
                'id' => 234,
            'nome' => 'Myanmar (Birmania)',
                'iso2' => 'MM',
            'name' => 'Myanmar (Burma)',
            ],
            [
                'id' => 235,
                'nome' => 'nazioni unite',
                'iso2' => 'UN',
                'name' => 'United Nations',
            ],
            [
                'id' => 236,
                'nome' => 'Niger',
                'iso2' => 'NE',
                'name' => 'Niger',
            ],
            [
                'id' => 237,
                'nome' => 'Pakistan',
                'iso2' => 'PK',
                'name' => 'Pakistan',
            ],
            [
                'id' => 238,
                'nome' => 'Paraguay',
                'iso2' => 'PY',
                'name' => 'Paraguay',
            ],
            [
                'id' => 239,
                'nome' => 'Portorico',
                'iso2' => 'PR',
                'name' => 'Puerto Rico',
            ],
            [
                'id' => 240,
                'nome' => 'RAS di Macao',
                'iso2' => 'MO',
                'name' => 'Macau SAR China',
            ],
            [
                'id' => 241,
                'nome' => 'Repubblica Centrafricana',
                'iso2' => 'CF',
                'name' => 'Central African Republic',
            ],
            [
                'id' => 242,
                'nome' => 'Repubblica di Macedonia',
                'iso2' => 'MK',
                'name' => 'Macedonia',
            ],
            [
                'id' => 243,
                'nome' => 'Sahara occidentale',
                'iso2' => 'EH',
                'name' => 'Western Sahara',
            ],
            [
                'id' => 244,
                'nome' => 'Saint Martin',
                'iso2' => 'MF',
                'name' => 'St. Martin',
            ],
            [
                'id' => 245,
                'nome' => 'Saint-Barthélemy',
                'iso2' => 'BL',
                'name' => 'St. Barthélemy',
            ],
            [
                'id' => 246,
                'nome' => 'Samoa americane',
                'iso2' => 'AS',
                'name' => 'American Samoa',
            ],
            [
                'id' => 247,
                'nome' => 'São Tomé e Príncipe',
                'iso2' => 'ST',
                'name' => 'São Tomé & Príncipe',
            ],
            [
                'id' => 248,
                'nome' => 'Serbia',
                'iso2' => 'RS',
                'name' => 'Serbia',
            ],
            [
                'id' => 249,
                'nome' => 'Sint Maarten',
                'iso2' => 'SX',
                'name' => 'Sint Maarten',
            ],
            [
                'id' => 250,
                'nome' => 'Siria',
                'iso2' => 'SY',
                'name' => 'Syria',
            ],
            [
                'id' => 251,
                'nome' => 'Sud Sudan',
                'iso2' => 'SS',
                'name' => 'South Sudan',
            ],
            [
                'id' => 252,
                'nome' => 'Sudan',
                'iso2' => 'SD',
                'name' => 'Sudan',
            ],
            [
                'id' => 253,
                'nome' => 'Terre australi francesi',
                'iso2' => 'TF',
                'name' => 'French Southern Territories',
            ],
            [
                'id' => 254,
                'nome' => 'Territori palestinesi',
                'iso2' => 'PS',
                'name' => 'Palestinian Territories',
            ],
            [
                'id' => 255,
                'nome' => 'Territorio britannico dell’Oceano Indiano',
                'iso2' => 'IO',
                'name' => 'British Indian Ocean Territory',
            ],
            [
                'id' => 256,
                'nome' => 'Timor Est',
                'iso2' => 'TL',
                'name' => 'Timor-Leste',
            ],
            [
                'id' => 257,
                'nome' => 'Tokelau',
                'iso2' => 'TK',
                'name' => 'Tokelau',
            ],
            [
                'id' => 258,
                'nome' => 'Tristan da Cunha',
                'iso2' => 'TA',
                'name' => 'Tristan da Cunha',
            ],
            [
                'id' => 259,
                'nome' => 'Uzbekistan',
                'iso2' => 'UZ',
                'name' => 'Uzbekistan',
            ],
            [
                'id' => 260,
                'nome' => 'Zimbabwe',
                'iso2' => 'ZW',
                'name' => 'Zimbabwe',
            ],
        ]);
    }
}
