<?php

use Update\Seed;

class CoIvaTableSeeder extends Seed
{
    /**
     * Auto generated seed file.
     */
    public function run()
    {
        $this->capsule->table('co_iva')->truncate();

        $this->capsule->table('co_iva')->insert([
            [
                'id' => 95,
                'descrizione' => 'Fuori campo IVA',
                'percentuale' => '0.00',
                'indetraibile' => '0.00',
                'esente' => 1,
                'dicitura' => null,
                'codice_natura_fe' => 'N2',
                'codice' => 300,
                'esigibilita' => 'I',
                'default' => 1,
            ],
            [
                'id' => 96,
                'descrizione' => 'Es.art27DL98/11',
                'percentuale' => '0.00',
                'indetraibile' => '0.00',
                'esente' => 1,
                'dicitura' => null,
                'codice_natura_fe' => 'N2',
                'codice' => 301,
                'esigibilita' => 'I',
                'default' => 1,
            ],
            [
                'id' => 97,
                'descrizione' => 'Escluso art. 2',
                'percentuale' => '0.00',
                'indetraibile' => '0.00',
                'esente' => 1,
                'dicitura' => null,
                'codice_natura_fe' => 'N2',
                'codice' => 302,
                'esigibilita' => 'I',
                'default' => 1,
            ],
            [
                'id' => 98,
                'descrizione' => 'Escluso art. 3',
                'percentuale' => '0.00',
                'indetraibile' => '0.00',
                'esente' => 1,
                'dicitura' => null,
                'codice_natura_fe' => 'N2',
                'codice' => 303,
                'esigibilita' => 'I',
                'default' => 1,
            ],
            [
                'id' => 99,
                'descrizione' => 'Escluso art. 4',
                'percentuale' => '0.00',
                'indetraibile' => '0.00',
                'esente' => 1,
                'dicitura' => null,
                'codice_natura_fe' => 'N2',
                'codice' => 304,
                'esigibilita' => 'I',
                'default' => 1,
            ],
            [
                'id' => 100,
                'descrizione' => 'Escluso art. 5',
                'percentuale' => '0.00',
                'indetraibile' => '0.00',
                'esente' => 1,
                'dicitura' => null,
                'codice_natura_fe' => 'N2',
                'codice' => 305,
                'esigibilita' => 'I',
                'default' => 1,
            ],
            [
                'id' => 101,
                'descrizione' => 'Esc.art7tr noUE',
                'percentuale' => '0.00',
                'indetraibile' => '0.00',
                'esente' => 1,
                'dicitura' => null,
                'codice_natura_fe' => 'N2',
                'codice' => 306,
                'esigibilita' => 'I',
                'default' => 1,
            ],
            [
                'id' => 102,
                'descrizione' => 'Escl.art7ter UE',
                'percentuale' => '0.00',
                'indetraibile' => '0.00',
                'esente' => 1,
                'dicitura' => null,
                'codice_natura_fe' => 'N6',
                'codice' => 307,
                'esigibilita' => 'I',
                'default' => 1,
            ],
            [
                'id' => 103,
                'descrizione' => 'Es. art.10 n.18',
                'percentuale' => '0.00',
                'indetraibile' => '0.00',
                'esente' => 1,
                'dicitura' => null,
                'codice_natura_fe' => 'N4',
                'codice' => 308,
                'esigibilita' => 'I',
                'default' => 1,
            ],
            [
                'id' => 104,
                'descrizione' => 'Es.art.10 n.1/9',
                'percentuale' => '0.00',
                'indetraibile' => '0.00',
                'esente' => 1,
                'dicitura' => null,
                'codice_natura_fe' => 'N4',
                'codice' => 309,
                'esigibilita' => 'I',
                'default' => 1,
            ],
            [
                'id' => 105,
                'descrizione' => 'Esente art. 10',
                'percentuale' => '0.00',
                'indetraibile' => '0.00',
                'esente' => 1,
                'dicitura' => null,
                'codice_natura_fe' => 'N4',
                'codice' => 310,
                'esigibilita' => 'I',
                'default' => 1,
            ],
            [
                'id' => 106,
                'descrizione' => 'Art8,1/a triang',
                'percentuale' => '0.00',
                'indetraibile' => '0.00',
                'esente' => 1,
                'dicitura' => null,
                'codice_natura_fe' => 'N3',
                'codice' => 311,
                'esigibilita' => 'I',
                'default' => 1,
            ],
            [
                'id' => 107,
                'descrizione' => 'N.I.art.8,2 ITA',
                'percentuale' => '0.00',
                'indetraibile' => '0.00',
                'esente' => 1,
                'dicitura' => null,
                'codice_natura_fe' => 'N3',
                'codice' => 312,
                'esigibilita' => 'I',
                'default' => 1,
            ],
            [
                'id' => 108,
                'descrizione' => 'N.I.art.8,2 UE',
                'percentuale' => '0.00',
                'indetraibile' => '0.00',
                'esente' => 1,
                'dicitura' => null,
                'codice_natura_fe' => 'N3',
                'codice' => 313,
                'esigibilita' => 'I',
                'default' => 1,
            ],
            [
                'id' => 109,
                'descrizione' => 'N.I. art. 9 c.1',
                'percentuale' => '0.00',
                'indetraibile' => '0.00',
                'esente' => 1,
                'dicitura' => null,
                'codice_natura_fe' => 'N3',
                'codice' => 314,
                'esigibilita' => 'I',
                'default' => 1,
            ],
            [
                'id' => 110,
                'descrizione' => 'Escluso art. 15',
                'percentuale' => '0.00',
                'indetraibile' => '0.00',
                'esente' => 1,
                'dicitura' => null,
                'codice_natura_fe' => 'N1',
                'codice' => 315,
                'esigibilita' => 'I',
                'default' => 1,
            ],
            [
                'id' => 111,
                'descrizione' => 'Art.17,6 let.a-',
                'percentuale' => '0.00',
                'indetraibile' => '0.00',
                'esente' => 1,
                'dicitura' => null,
                'codice_natura_fe' => 'N6',
                'codice' => 316,
                'esigibilita' => 'I',
                'default' => 1,
            ],
            [
                'id' => 112,
                'descrizione' => 'N.I. art.74 ter',
                'percentuale' => '0.00',
                'indetraibile' => '0.00',
                'esente' => 1,
                'dicitura' => null,
                'codice_natura_fe' => 'N5',
                'codice' => 317,
                'esigibilita' => 'I',
                'default' => 1,
            ],
            [
                'id' => 113,
                'descrizione' => 'N.I.art.14 L.49',
                'percentuale' => '0.00',
                'indetraibile' => '0.00',
                'esente' => 1,
                'dicitura' => null,
                'codice_natura_fe' => 'N3',
                'codice' => 318,
                'esigibilita' => 'I',
                'default' => 1,
            ],
            [
                'id' => 114,
                'descrizione' => 'Es.art.10 n.27q',
                'percentuale' => '0.00',
                'indetraibile' => '0.00',
                'esente' => 1,
                'dicitura' => null,
                'codice_natura_fe' => 'N4',
                'codice' => 319,
                'esigibilita' => 'I',
                'default' => 1,
            ],
            [
                'id' => 115,
                'descrizione' => 'N.I.a.8,2 no-UE',
                'percentuale' => '0.00',
                'indetraibile' => '0.00',
                'esente' => 1,
                'dicitura' => null,
                'codice_natura_fe' => 'N3',
                'codice' => 320,
                'esigibilita' => 'I',
                'default' => 1,
            ],
            [
                'id' => 116,
                'descrizione' => 'Es. art.10 n.11',
                'percentuale' => '0.00',
                'indetraibile' => '0.00',
                'esente' => 1,
                'dicitura' => null,
                'codice_natura_fe' => 'N4',
                'codice' => 321,
                'esigibilita' => 'I',
                'default' => 1,
            ],
            [
                'id' => 117,
                'descrizione' => 'N.I. art. 8 bis',
                'percentuale' => '0.00',
                'indetraibile' => '0.00',
                'esente' => 1,
                'dicitura' => null,
                'codice_natura_fe' => 'N3',
                'codice' => 322,
                'esigibilita' => 'I',
                'default' => 1,
            ],
            [
                'id' => 118,
                'descrizione' => 'N.I. art.8,1 b',
                'percentuale' => '0.00',
                'indetraibile' => '0.00',
                'esente' => 1,
                'dicitura' => null,
                'codice_natura_fe' => 'N3',
                'codice' => 323,
                'esigibilita' => 'I',
                'default' => 1,
            ],
            [
                'id' => 119,
                'descrizione' => 'N.I. art.8,1 c',
                'percentuale' => '0.00',
                'indetraibile' => '0.00',
                'esente' => 1,
                'dicitura' => null,
                'codice_natura_fe' => 'N3',
                'codice' => 324,
                'esigibilita' => 'I',
                'default' => 1,
            ],
            [
                'id' => 120,
                'descrizione' => 'N.I. art.8,1 a',
                'percentuale' => '0.00',
                'indetraibile' => '0.00',
                'esente' => 1,
                'dicitura' => null,
                'codice_natura_fe' => 'N3',
                'codice' => 325,
                'esigibilita' => 'I',
                'default' => 1,
            ],
            [
                'id' => 121,
                'descrizione' => 'N.V.escl.art.26',
                'percentuale' => '0.00',
                'indetraibile' => '0.00',
                'esente' => 1,
                'dicitura' => null,
                'codice_natura_fe' => 'N2',
                'codice' => 326,
                'esigibilita' => 'I',
                'default' => 1,
            ],
            [
                'id' => 122,
                'descrizione' => 'N.I. altri acq.',
                'percentuale' => '0.00',
                'indetraibile' => '0.00',
                'esente' => 1,
                'dicitura' => null,
                'codice_natura_fe' => 'N3',
                'codice' => 327,
                'esigibilita' => 'I',
                'default' => 1,
            ],
            [
                'id' => 123,
                'descrizione' => 'Op. non sog.ter',
                'percentuale' => '0.00',
                'indetraibile' => '0.00',
                'esente' => 1,
                'dicitura' => null,
                'codice_natura_fe' => 'N2',
                'codice' => 328,
                'esigibilita' => 'I',
                'default' => 1,
            ],
            [
                'id' => 124,
                'descrizione' => 'N.I. art. 9 c.2',
                'percentuale' => '0.00',
                'indetraibile' => '0.00',
                'esente' => 1,
                'dicitura' => null,
                'codice_natura_fe' => 'N3',
                'codice' => 329,
                'esigibilita' => 'I',
                'default' => 1,
            ],
            [
                'id' => 125,
                'descrizione' => 'Esc.art7quatrUE',
                'percentuale' => '0.00',
                'indetraibile' => '0.00',
                'esente' => 1,
                'dicitura' => null,
                'codice_natura_fe' => 'N6',
                'codice' => 330,
                'esigibilita' => 'I',
                'default' => 1,
            ],
            [
                'id' => 126,
                'descrizione' => 'Esc.art7qtrNOUE',
                'percentuale' => '0.00',
                'indetraibile' => '0.00',
                'esente' => 1,
                'dicitura' => null,
                'codice_natura_fe' => 'N2',
                'codice' => 331,
                'esigibilita' => 'I',
                'default' => 1,
            ],
            [
                'id' => 127,
                'descrizione' => 'Esc.art7quinqUE',
                'percentuale' => '0.00',
                'indetraibile' => '0.00',
                'esente' => 1,
                'dicitura' => null,
                'codice_natura_fe' => 'N6',
                'codice' => 332,
                'esigibilita' => 'I',
                'default' => 1,
            ],
            [
                'id' => 128,
                'descrizione' => 'Esc.art7qnqNOUE',
                'percentuale' => '0.00',
                'indetraibile' => '0.00',
                'esente' => 1,
                'dicitura' => null,
                'codice_natura_fe' => 'N2',
                'codice' => 333,
                'esigibilita' => 'I',
                'default' => 1,
            ],
            [
                'id' => 129,
                'descrizione' => 'Art.36-bis',
                'percentuale' => '0.00',
                'indetraibile' => '0.00',
                'esente' => 1,
                'dicitura' => null,
                'codice_natura_fe' => 'N2',
                'codice' => 334,
                'esigibilita' => 'I',
                'default' => 1,
            ],
            [
                'id' => 130,
                'descrizione' => 'Art.17 comma 3',
                'percentuale' => '0.00',
                'indetraibile' => '0.00',
                'esente' => 1,
                'dicitura' => null,
                'codice_natura_fe' => 'N2',
                'codice' => 335,
                'esigibilita' => 'I',
                'default' => 1,
            ],
            [
                'id' => 131,
                'descrizione' => 'DL41/95 art.36',
                'percentuale' => '0.00',
                'indetraibile' => '0.00',
                'esente' => 1,
                'dicitura' => null,
                'codice_natura_fe' => 'N5',
                'codice' => 336,
                'esigibilita' => 'I',
                'default' => 1,
            ],
            [
                'id' => 132,
                'descrizione' => 'Es.art.19c3abis',
                'percentuale' => '0.00',
                'indetraibile' => '0.00',
                'esente' => 1,
                'dicitura' => null,
                'codice_natura_fe' => 'N4',
                'codice' => 337,
                'esigibilita' => 'I',
                'default' => 1,
            ],
            [
                'id' => 133,
                'descrizione' => 'N.I. art.38 q.',
                'percentuale' => '0.00',
                'indetraibile' => '0.00',
                'esente' => 1,
                'dicitura' => null,
                'codice_natura_fe' => 'N3',
                'codice' => 338,
                'esigibilita' => 'I',
                'default' => 1,
            ],
            [
                'id' => 134,
                'descrizione' => 'Escl.art.7nodet',
                'percentuale' => '0.00',
                'indetraibile' => '0.00',
                'esente' => 1,
                'dicitura' => null,
                'codice_natura_fe' => 'N2',
                'codice' => 339,
                'esigibilita' => 'I',
                'default' => 1,
            ],
            [
                'id' => 135,
                'descrizione' => 'Esc.art.7spt/sx',
                'percentuale' => '0.00',
                'indetraibile' => '0.00',
                'esente' => 1,
                'dicitura' => null,
                'codice_natura_fe' => 'N2',
                'codice' => 340,
                'esigibilita' => 'I',
                'default' => 1,
            ],
            [
                'id' => 136,
                'descrizione' => 'DL331/93 art.41',
                'percentuale' => '0.00',
                'indetraibile' => '0.00',
                'esente' => 1,
                'dicitura' => null,
                'codice_natura_fe' => 'N3',
                'codice' => 341,
                'esigibilita' => 'I',
                'default' => 1,
            ],
            [
                'id' => 137,
                'descrizione' => 'DL331art42,40c2',
                'percentuale' => '0.00',
                'indetraibile' => '0.00',
                'esente' => 1,
                'dicitura' => null,
                'codice_natura_fe' => 'N3',
                'codice' => 342,
                'esigibilita' => 'I',
                'default' => 1,
            ],
            [
                'id' => 138,
                'descrizione' => 'N.I.art.8,1 b2',
                'percentuale' => '0.00',
                'indetraibile' => '0.00',
                'esente' => 1,
                'dicitura' => null,
                'codice_natura_fe' => 'N3',
                'codice' => 343,
                'esigibilita' => 'I',
                'default' => 1,
            ],
            [
                'id' => 139,
                'descrizione' => 'Escl.art.7bisUE',
                'percentuale' => '0.00',
                'indetraibile' => '0.00',
                'esente' => 1,
                'dicitura' => null,
                'codice_natura_fe' => 'N6',
                'codice' => 344,
                'esigibilita' => 'I',
                'default' => 1,
            ],
            [
                'id' => 140,
                'descrizione' => 'DL331 a.50b,4-g',
                'percentuale' => '0.00',
                'indetraibile' => '0.00',
                'esente' => 1,
                'dicitura' => null,
                'codice_natura_fe' => 'N3',
                'codice' => 350,
                'esigibilita' => 'I',
                'default' => 1,
            ],
            [
                'id' => 141,
                'descrizione' => 'DL331 a.50b,4-f',
                'percentuale' => '0.00',
                'indetraibile' => '0.00',
                'esente' => 1,
                'dicitura' => null,
                'codice_natura_fe' => 'N3',
                'codice' => 351,
                'esigibilita' => 'I',
                'default' => 1,
            ],
            [
                'id' => 142,
                'descrizione' => 'Cess. dep. IVA',
                'percentuale' => '0.00',
                'indetraibile' => '0.00',
                'esente' => 1,
                'dicitura' => null,
                'codice_natura_fe' => 'N2',
                'codice' => 352,
                'esigibilita' => 'I',
                'default' => 1,
            ],
            [
                'id' => 143,
                'descrizione' => 'N.I.Acq.dep.IVA',
                'percentuale' => '0.00',
                'indetraibile' => '0.00',
                'esente' => 1,
                'dicitura' => null,
                'codice_natura_fe' => 'N2',
                'codice' => 353,
                'esigibilita' => 'I',
                'default' => 1,
            ],
            [
                'id' => 144,
                'descrizione' => 'Es.art1 L190/14',
                'percentuale' => '0.00',
                'indetraibile' => '0.00',
                'esente' => 1,
                'dicitura' => null,
                'codice_natura_fe' => 'N2',
                'codice' => 354,
                'esigibilita' => 'I',
                'default' => 1,
            ],
            [
                'id' => 145,
                'descrizione' => 'Ces.gratuiteExp',
                'percentuale' => '0.00',
                'indetraibile' => '0.00',
                'esente' => 1,
                'dicitura' => null,
                'codice_natura_fe' => 'N3',
                'codice' => 355,
                'esigibilita' => 'I',
                'default' => 1,
            ],
            [
                'id' => 146,
                'descrizione' => 'DL331/93 a.58,1',
                'percentuale' => '0.00',
                'indetraibile' => '0.00',
                'esente' => 1,
                'dicitura' => null,
                'codice_natura_fe' => 'N3',
                'codice' => 358,
                'esigibilita' => 'I',
                'default' => 1,
            ],
            [
                'id' => 147,
                'descrizione' => 'Esc.legge67/88',
                'percentuale' => '0.00',
                'indetraibile' => '0.00',
                'esente' => 1,
                'dicitura' => null,
                'codice_natura_fe' => 'N2',
                'codice' => 367,
                'esigibilita' => 'I',
                'default' => 1,
            ],
            [
                'id' => 148,
                'descrizione' => 'Imp.n.s. art.68',
                'percentuale' => '0.00',
                'indetraibile' => '0.00',
                'esente' => 1,
                'dicitura' => null,
                'codice_natura_fe' => 'N3',
                'codice' => 368,
                'esigibilita' => 'I',
                'default' => 1,
            ],
            [
                'id' => 149,
                'descrizione' => 'Art.74 ter c. 8',
                'percentuale' => '0.00',
                'indetraibile' => '0.00',
                'esente' => 1,
                'dicitura' => null,
                'codice_natura_fe' => 'N6',
                'codice' => 369,
                'esigibilita' => 'I',
                'default' => 1,
            ],
            [
                'id' => 150,
                'descrizione' => 'Escl.art.7bis',
                'percentuale' => '0.00',
                'indetraibile' => '0.00',
                'esente' => 1,
                'dicitura' => null,
                'codice_natura_fe' => 'N2',
                'codice' => 370,
                'esigibilita' => 'I',
                'default' => 1,
            ],
            [
                'id' => 151,
                'descrizione' => 'N.I.art.71 V-SM',
                'percentuale' => '0.00',
                'indetraibile' => '0.00',
                'esente' => 1,
                'dicitura' => null,
                'codice_natura_fe' => 'N3',
                'codice' => 371,
                'esigibilita' => 'I',
                'default' => 1,
            ],
            [
                'id' => 152,
                'descrizione' => 'N.I. art. 72',
                'percentuale' => '0.00',
                'indetraibile' => '0.00',
                'esente' => 1,
                'dicitura' => null,
                'codice_natura_fe' => 'N3',
                'codice' => 372,
                'esigibilita' => 'I',
                'default' => 1,
            ],
            [
                'id' => 153,
                'descrizione' => 'N.I.art.74c.1-2',
                'percentuale' => '0.00',
                'indetraibile' => '0.00',
                'esente' => 1,
                'dicitura' => null,
                'codice_natura_fe' => 'N2',
                'codice' => 374,
                'esigibilita' => 'I',
                'default' => 1,
            ],
            [
                'id' => 154,
                'descrizione' => 'Art. 74 c. 7-8',
                'percentuale' => '0.00',
                'indetraibile' => '0.00',
                'esente' => 1,
                'dicitura' => null,
                'codice_natura_fe' => 'N6',
                'codice' => 375,
                'esigibilita' => 'I',
                'default' => 1,
            ],
            [
                'id' => 155,
                'descrizione' => 'Art. 17 c. 5',
                'percentuale' => '0.00',
                'indetraibile' => '0.00',
                'esente' => 1,
                'dicitura' => null,
                'codice_natura_fe' => 'N6',
                'codice' => 376,
                'esigibilita' => 'I',
                'default' => 1,
            ],
            [
                'id' => 156,
                'descrizione' => 'Art.17,6 lett.a',
                'percentuale' => '0.00',
                'indetraibile' => '0.00',
                'esente' => 1,
                'dicitura' => null,
                'codice_natura_fe' => 'N6',
                'codice' => 377,
                'esigibilita' => 'I',
                'default' => 1,
            ],
            [
                'id' => 157,
                'descrizione' => 'Art.74 ter c. 8',
                'percentuale' => '0.00',
                'indetraibile' => '0.00',
                'esente' => 1,
                'dicitura' => null,
                'codice_natura_fe' => 'N3',
                'codice' => 378,
                'esigibilita' => 'I',
                'default' => 1,
            ],
            [
                'id' => 158,
                'descrizione' => 'Art.17,6 lett.b',
                'percentuale' => '0.00',
                'indetraibile' => '0.00',
                'esente' => 1,
                'dicitura' => null,
                'codice_natura_fe' => 'N6',
                'codice' => 379,
                'esigibilita' => 'I',
                'default' => 1,
            ],
            [
                'id' => 159,
                'descrizione' => 'Art.17,6 lett.c',
                'percentuale' => '0.00',
                'indetraibile' => '0.00',
                'esente' => 1,
                'dicitura' => null,
                'codice_natura_fe' => 'N6',
                'codice' => 380,
                'esigibilita' => 'I',
                'default' => 1,
            ],
            [
                'id' => 160,
                'descrizione' => 'Art.17,6 let.a3',
                'percentuale' => '0.00',
                'indetraibile' => '0.00',
                'esente' => 1,
                'dicitura' => null,
                'codice_natura_fe' => 'N6',
                'codice' => 381,
                'esigibilita' => 'I',
                'default' => 1,
            ],
            [
                'id' => 161,
                'descrizione' => 'Art.17,6,lett.d',
                'percentuale' => '0.00',
                'indetraibile' => '0.00',
                'esente' => 1,
                'dicitura' => null,
                'codice_natura_fe' => 'N6',
                'codice' => 382,
                'esigibilita' => 'I',
                'default' => 1,
            ],
            [
                'id' => 162,
                'descrizione' => 'Aliq. Iva 2%',
                'percentuale' => '2.00',
                'indetraibile' => '0.00',
                'esente' => 0,
                'dicitura' => null,
                'codice_natura_fe' => null,
                'codice' => 2,
                'esigibilita' => 'I',
                'default' => 1,
            ],
            [
                'id' => 163,
                'descrizione' => 'Aliq. Iva 4%',
                'percentuale' => '4.00',
                'indetraibile' => '0.00',
                'esente' => 0,
                'dicitura' => null,
                'codice_natura_fe' => null,
                'codice' => 4,
                'esigibilita' => 'I',
                'default' => 1,
            ],
            [
                'id' => 164,
                'descrizione' => 'Aliq. Iva 5%',
                'percentuale' => '5.00',
                'indetraibile' => '0.00',
                'esente' => 0,
                'dicitura' => null,
                'codice_natura_fe' => null,
                'codice' => 5,
                'esigibilita' => 'I',
                'default' => 1,
            ],
            [
                'id' => 165,
                'descrizione' => 'Aliq. Iva 7%',
                'percentuale' => '7.00',
                'indetraibile' => '0.00',
                'esente' => 0,
                'dicitura' => null,
                'codice_natura_fe' => null,
                'codice' => 7,
                'esigibilita' => 'I',
                'default' => 1,
            ],
            [
                'id' => 166,
                'descrizione' => 'Aliq. Iva 8%',
                'percentuale' => '8.00',
                'indetraibile' => '0.00',
                'esente' => 0,
                'dicitura' => null,
                'codice_natura_fe' => null,
                'codice' => 8,
                'esigibilita' => 'I',
                'default' => 1,
            ],
            [
                'id' => 167,
                'descrizione' => 'Aliq. Iva 10%',
                'percentuale' => '10.00',
                'indetraibile' => '0.00',
                'esente' => 0,
                'dicitura' => null,
                'codice_natura_fe' => null,
                'codice' => 10,
                'esigibilita' => 'I',
                'default' => 1,
            ],
            [
                'id' => 168,
                'descrizione' => 'Aliq. Iva 12,3%',
                'percentuale' => '12.30',
                'indetraibile' => '0.00',
                'esente' => 0,
                'dicitura' => null,
                'codice_natura_fe' => null,
                'codice' => 13,
                'esigibilita' => 'I',
                'default' => 1,
            ],
            [
                'id' => 169,
                'descrizione' => 'Aliq. Iva 20%',
                'percentuale' => '20.00',
                'indetraibile' => '0.00',
                'esente' => 0,
                'dicitura' => null,
                'codice_natura_fe' => null,
                'codice' => 20,
                'esigibilita' => 'I',
                'default' => 1,
            ],
            [
                'id' => 170,
                'descrizione' => 'Aliq. Iva 21%',
                'percentuale' => '21.00',
                'indetraibile' => '0.00',
                'esente' => 0,
                'dicitura' => null,
                'codice_natura_fe' => null,
                'codice' => 21,
                'esigibilita' => 'I',
                'default' => 1,
            ],
            [
                'id' => 171,
                'descrizione' => 'Aliq. Iva 22%',
                'percentuale' => '22.00',
                'indetraibile' => '0.00',
                'esente' => 0,
                'dicitura' => null,
                'codice_natura_fe' => null,
                'codice' => 22,
                'esigibilita' => 'I',
                'default' => 1,
            ],
            [
                'id' => 172,
                'descrizione' => 'Aliq. Iva 7,3%',
                'percentuale' => '7.30',
                'indetraibile' => '0.00',
                'esente' => 0,
                'dicitura' => null,
                'codice_natura_fe' => null,
                'codice' => 73,
                'esigibilita' => 'I',
                'default' => 1,
            ],
            [
                'id' => 173,
                'descrizione' => 'Aliq. Iva 7,5%',
                'percentuale' => '7.50',
                'indetraibile' => '0.00',
                'esente' => 0,
                'dicitura' => null,
                'codice_natura_fe' => null,
                'codice' => 75,
                'esigibilita' => 'I',
                'default' => 1,
            ],
            [
                'id' => 174,
                'descrizione' => 'Aliq. Iva 7,65%',
                'percentuale' => '7.65',
                'indetraibile' => '0.00',
                'esente' => 0,
                'dicitura' => null,
                'codice_natura_fe' => null,
                'codice' => 76,
                'esigibilita' => 'I',
                'default' => 1,
            ],
            [
                'id' => 175,
                'descrizione' => 'Aliq. Iva 7,7%',
                'percentuale' => '7.70',
                'indetraibile' => '0.00',
                'esente' => 0,
                'dicitura' => null,
                'codice_natura_fe' => null,
                'codice' => 77,
                'esigibilita' => 'I',
                'default' => 1,
            ],
            [
                'id' => 176,
                'descrizione' => 'Aliq. Iva 7,95%',
                'percentuale' => '7.95',
                'indetraibile' => '0.00',
                'esente' => 0,
                'dicitura' => null,
                'codice_natura_fe' => null,
                'codice' => 79,
                'esigibilita' => 'I',
                'default' => 1,
            ],
            [
                'id' => 177,
                'descrizione' => 'Aliq. Iva 8,3%',
                'percentuale' => '8.30',
                'indetraibile' => '0.00',
                'esente' => 0,
                'dicitura' => null,
                'codice_natura_fe' => null,
                'codice' => 83,
                'esigibilita' => 'I',
                'default' => 1,
            ],
            [
                'id' => 178,
                'descrizione' => 'Aliq. Iva 8,5%',
                'percentuale' => '8.50',
                'indetraibile' => '0.00',
                'esente' => 0,
                'dicitura' => null,
                'codice_natura_fe' => null,
                'codice' => 85,
                'esigibilita' => 'I',
                'default' => 1,
            ],
            [
                'id' => 179,
                'descrizione' => 'Aliq. Iva 8,8%',
                'percentuale' => '8.80',
                'indetraibile' => '0.00',
                'esente' => 0,
                'dicitura' => null,
                'codice_natura_fe' => null,
                'codice' => 88,
                'esigibilita' => 'I',
                'default' => 1,
            ],
            [
                'id' => 180,
                'descrizione' => 'Scorporo 2%',
                'percentuale' => '2.00',
                'indetraibile' => '0.00',
                'esente' => 0,
                'dicitura' => null,
                'codice_natura_fe' => null,
                'codice' => 102,
                'esigibilita' => 'I',
                'default' => 1,
            ],
            [
                'id' => 181,
                'descrizione' => 'Scorporo 4%',
                'percentuale' => '4.00',
                'indetraibile' => '0.00',
                'esente' => 0,
                'dicitura' => null,
                'codice_natura_fe' => null,
                'codice' => 104,
                'esigibilita' => 'I',
                'default' => 1,
            ],
            [
                'id' => 182,
                'descrizione' => 'Scorporo 5%',
                'percentuale' => '5.00',
                'indetraibile' => '0.00',
                'esente' => 0,
                'dicitura' => null,
                'codice_natura_fe' => null,
                'codice' => 105,
                'esigibilita' => 'I',
                'default' => 1,
            ],
            [
                'id' => 183,
                'descrizione' => 'Scorporo 7%',
                'percentuale' => '7.00',
                'indetraibile' => '0.00',
                'esente' => 0,
                'dicitura' => null,
                'codice_natura_fe' => null,
                'codice' => 107,
                'esigibilita' => 'I',
                'default' => 1,
            ],
            [
                'id' => 184,
                'descrizione' => 'Scorporo 8%',
                'percentuale' => '8.00',
                'indetraibile' => '0.00',
                'esente' => 0,
                'dicitura' => null,
                'codice_natura_fe' => null,
                'codice' => 108,
                'esigibilita' => 'I',
                'default' => 1,
            ],
            [
                'id' => 185,
                'descrizione' => 'Scorporo 10%',
                'percentuale' => '10.00',
                'indetraibile' => '0.00',
                'esente' => 0,
                'dicitura' => null,
                'codice_natura_fe' => null,
                'codice' => 110,
                'esigibilita' => 'I',
                'default' => 1,
            ],
            [
                'id' => 186,
                'descrizione' => 'Scorporo 12,3%',
                'percentuale' => '12.30',
                'indetraibile' => '0.00',
                'esente' => 0,
                'dicitura' => null,
                'codice_natura_fe' => null,
                'codice' => 113,
                'esigibilita' => 'I',
                'default' => 1,
            ],
            [
                'id' => 187,
                'descrizione' => 'Scorporo 20%',
                'percentuale' => '20.00',
                'indetraibile' => '0.00',
                'esente' => 0,
                'dicitura' => null,
                'codice_natura_fe' => null,
                'codice' => 120,
                'esigibilita' => 'I',
                'default' => 1,
            ],
            [
                'id' => 188,
                'descrizione' => 'Scorporo 21%',
                'percentuale' => '21.00',
                'indetraibile' => '0.00',
                'esente' => 0,
                'dicitura' => null,
                'codice_natura_fe' => null,
                'codice' => 121,
                'esigibilita' => 'I',
                'default' => 1,
            ],
            [
                'id' => 189,
                'descrizione' => 'Scorporo 22%',
                'percentuale' => '22.00',
                'indetraibile' => '0.00',
                'esente' => 0,
                'dicitura' => null,
                'codice_natura_fe' => null,
                'codice' => 122,
                'esigibilita' => 'I',
                'default' => 1,
            ],
            [
                'id' => 190,
                'descrizione' => 'Scorporo 7,3%',
                'percentuale' => '7.30',
                'indetraibile' => '0.00',
                'esente' => 0,
                'dicitura' => null,
                'codice_natura_fe' => null,
                'codice' => 173,
                'esigibilita' => 'I',
                'default' => 1,
            ],
            [
                'id' => 191,
                'descrizione' => 'Scorporo 7,5%',
                'percentuale' => '7.50',
                'indetraibile' => '0.00',
                'esente' => 0,
                'dicitura' => null,
                'codice_natura_fe' => null,
                'codice' => 175,
                'esigibilita' => 'I',
                'default' => 1,
            ],
            [
                'id' => 192,
                'descrizione' => 'Scorporo 7,65%',
                'percentuale' => '7.65',
                'indetraibile' => '0.00',
                'esente' => 0,
                'dicitura' => null,
                'codice_natura_fe' => null,
                'codice' => 176,
                'esigibilita' => 'I',
                'default' => 1,
            ],
            [
                'id' => 193,
                'descrizione' => 'Scorporo 7,7%',
                'percentuale' => '7.70',
                'indetraibile' => '0.00',
                'esente' => 0,
                'dicitura' => null,
                'codice_natura_fe' => null,
                'codice' => 177,
                'esigibilita' => 'I',
                'default' => 1,
            ],
            [
                'id' => 194,
                'descrizione' => 'Scorporo 7,95%',
                'percentuale' => '7.95',
                'indetraibile' => '0.00',
                'esente' => 0,
                'dicitura' => null,
                'codice_natura_fe' => null,
                'codice' => 179,
                'esigibilita' => 'I',
                'default' => 1,
            ],
            [
                'id' => 195,
                'descrizione' => 'Scorporo 8,3%',
                'percentuale' => '8.30',
                'indetraibile' => '0.00',
                'esente' => 0,
                'dicitura' => null,
                'codice_natura_fe' => null,
                'codice' => 183,
                'esigibilita' => 'I',
                'default' => 1,
            ],
            [
                'id' => 196,
                'descrizione' => 'Scorporo 8,5%',
                'percentuale' => '8.50',
                'indetraibile' => '0.00',
                'esente' => 0,
                'dicitura' => null,
                'codice_natura_fe' => null,
                'codice' => 185,
                'esigibilita' => 'I',
                'default' => 1,
            ],
            [
                'id' => 197,
                'descrizione' => 'Scorporo 8,8%',
                'percentuale' => '8.80',
                'indetraibile' => '0.00',
                'esente' => 0,
                'dicitura' => null,
                'codice_natura_fe' => null,
                'codice' => 188,
                'esigibilita' => 'I',
                'default' => 1,
            ],
            [
                'id' => 198,
                'descrizione' => 'Corr. Ventilati',
                'percentuale' => '0.00',
                'indetraibile' => '0.00',
                'esente' => 0,
                'dicitura' => null,
                'codice_natura_fe' => null,
                'codice' => 200,
                'esigibilita' => 'I',
                'default' => 1,
            ],
            [
                'id' => 199,
                'descrizione' => 'Iva Vent. 2%',
                'percentuale' => '2.00',
                'indetraibile' => '0.00',
                'esente' => 0,
                'dicitura' => null,
                'codice_natura_fe' => null,
                'codice' => 202,
                'esigibilita' => 'I',
                'default' => 1,
            ],
            [
                'id' => 200,
                'descrizione' => 'Iva Vent. 4%',
                'percentuale' => '4.00',
                'indetraibile' => '0.00',
                'esente' => 0,
                'dicitura' => null,
                'codice_natura_fe' => null,
                'codice' => 204,
                'esigibilita' => 'I',
                'default' => 1,
            ],
            [
                'id' => 201,
                'descrizione' => 'Iva Vent. 5%',
                'percentuale' => '5.00',
                'indetraibile' => '0.00',
                'esente' => 0,
                'dicitura' => null,
                'codice_natura_fe' => null,
                'codice' => 205,
                'esigibilita' => 'I',
                'default' => 1,
            ],
            [
                'id' => 202,
                'descrizione' => 'Iva Vent. 7%',
                'percentuale' => '7.00',
                'indetraibile' => '0.00',
                'esente' => 0,
                'dicitura' => null,
                'codice_natura_fe' => null,
                'codice' => 207,
                'esigibilita' => 'I',
                'default' => 1,
            ],
            [
                'id' => 203,
                'descrizione' => 'Iva Vent. 8%',
                'percentuale' => '8.00',
                'indetraibile' => '0.00',
                'esente' => 0,
                'dicitura' => null,
                'codice_natura_fe' => null,
                'codice' => 208,
                'esigibilita' => 'I',
                'default' => 1,
            ],
            [
                'id' => 204,
                'descrizione' => 'Iva Vent. 10%',
                'percentuale' => '10.00',
                'indetraibile' => '0.00',
                'esente' => 0,
                'dicitura' => null,
                'codice_natura_fe' => null,
                'codice' => 210,
                'esigibilita' => 'I',
                'default' => 1,
            ],
            [
                'id' => 205,
                'descrizione' => 'Iva Vent. 12,3%',
                'percentuale' => '12.30',
                'indetraibile' => '0.00',
                'esente' => 0,
                'dicitura' => null,
                'codice_natura_fe' => null,
                'codice' => 213,
                'esigibilita' => 'I',
                'default' => 1,
            ],
            [
                'id' => 206,
                'descrizione' => 'Iva Vent. 20%',
                'percentuale' => '20.00',
                'indetraibile' => '0.00',
                'esente' => 0,
                'dicitura' => null,
                'codice_natura_fe' => null,
                'codice' => 220,
                'esigibilita' => 'I',
                'default' => 1,
            ],
            [
                'id' => 207,
                'descrizione' => 'Iva Vent. 21%',
                'percentuale' => '21.00',
                'indetraibile' => '0.00',
                'esente' => 0,
                'dicitura' => null,
                'codice_natura_fe' => null,
                'codice' => 221,
                'esigibilita' => 'I',
                'default' => 1,
            ],
            [
                'id' => 208,
                'descrizione' => 'Iva Vent. 22%',
                'percentuale' => '22.00',
                'indetraibile' => '0.00',
                'esente' => 0,
                'dicitura' => null,
                'codice_natura_fe' => null,
                'codice' => 222,
                'esigibilita' => 'I',
                'default' => 1,
            ],
            [
                'id' => 209,
                'descrizione' => 'Iva Vent. 7,3%',
                'percentuale' => '7.30',
                'indetraibile' => '0.00',
                'esente' => 0,
                'dicitura' => null,
                'codice_natura_fe' => null,
                'codice' => 273,
                'esigibilita' => 'I',
                'default' => 1,
            ],
            [
                'id' => 210,
                'descrizione' => 'Iva Vent. 7,5%',
                'percentuale' => '7.50',
                'indetraibile' => '0.00',
                'esente' => 0,
                'dicitura' => null,
                'codice_natura_fe' => null,
                'codice' => 275,
                'esigibilita' => 'I',
                'default' => 1,
            ],
            [
                'id' => 211,
                'descrizione' => 'Iva Vent. 7,65%',
                'percentuale' => '7.65',
                'indetraibile' => '0.00',
                'esente' => 0,
                'dicitura' => null,
                'codice_natura_fe' => null,
                'codice' => 276,
                'esigibilita' => 'I',
                'default' => 1,
            ],
            [
                'id' => 212,
                'descrizione' => 'Iva Vent. 7,7%',
                'percentuale' => '7.70',
                'indetraibile' => '0.00',
                'esente' => 0,
                'dicitura' => null,
                'codice_natura_fe' => null,
                'codice' => 277,
                'esigibilita' => 'I',
                'default' => 1,
            ],
            [
                'id' => 213,
                'descrizione' => 'Iva Vent. 7,95%',
                'percentuale' => '7.95',
                'indetraibile' => '0.00',
                'esente' => 0,
                'dicitura' => null,
                'codice_natura_fe' => null,
                'codice' => 279,
                'esigibilita' => 'I',
                'default' => 1,
            ],
            [
                'id' => 214,
                'descrizione' => 'Iva Vent. 8,3%',
                'percentuale' => '8.30',
                'indetraibile' => '0.00',
                'esente' => 0,
                'dicitura' => null,
                'codice_natura_fe' => null,
                'codice' => 283,
                'esigibilita' => 'I',
                'default' => 1,
            ],
            [
                'id' => 215,
                'descrizione' => 'Iva Vent. 8,5%',
                'percentuale' => '8.50',
                'indetraibile' => '0.00',
                'esente' => 0,
                'dicitura' => null,
                'codice_natura_fe' => null,
                'codice' => 285,
                'esigibilita' => 'I',
                'default' => 1,
            ],
            [
                'id' => 216,
                'descrizione' => 'Iva Vent. 8,8%',
                'percentuale' => '8.80',
                'indetraibile' => '0.00',
                'esente' => 0,
                'dicitura' => null,
                'codice_natura_fe' => null,
                'codice' => 288,
                'esigibilita' => 'I',
                'default' => 1,
            ],
            [
                'id' => 217,
                'descrizione' => 'Iva Tot. Indetr 2%',
                'percentuale' => '2.00',
                'indetraibile' => '100.00',
                'esente' => 0,
                'dicitura' => null,
                'codice_natura_fe' => null,
                'codice' => 602,
                'esigibilita' => 'I',
                'default' => 1,
            ],
            [
                'id' => 218,
                'descrizione' => 'Iva Tot. Indetr 4%',
                'percentuale' => '4.00',
                'indetraibile' => '100.00',
                'esente' => 0,
                'dicitura' => null,
                'codice_natura_fe' => null,
                'codice' => 604,
                'esigibilita' => 'I',
                'default' => 1,
            ],
            [
                'id' => 219,
                'descrizione' => 'Iva Tot. Indetr 5%',
                'percentuale' => '5.00',
                'indetraibile' => '100.00',
                'esente' => 0,
                'dicitura' => null,
                'codice_natura_fe' => null,
                'codice' => 605,
                'esigibilita' => 'I',
                'default' => 1,
            ],
            [
                'id' => 220,
                'descrizione' => 'Iva Tot. Indetr 7%',
                'percentuale' => '7.00',
                'indetraibile' => '100.00',
                'esente' => 0,
                'dicitura' => null,
                'codice_natura_fe' => null,
                'codice' => 607,
                'esigibilita' => 'I',
                'default' => 1,
            ],
            [
                'id' => 221,
                'descrizione' => 'Iva Tot. Indetr 8%',
                'percentuale' => '8.00',
                'indetraibile' => '100.00',
                'esente' => 0,
                'dicitura' => null,
                'codice_natura_fe' => null,
                'codice' => 608,
                'esigibilita' => 'I',
                'default' => 1,
            ],
            [
                'id' => 222,
                'descrizione' => 'Iva Tot. Indetr 10%',
                'percentuale' => '10.00',
                'indetraibile' => '100.00',
                'esente' => 0,
                'dicitura' => null,
                'codice_natura_fe' => null,
                'codice' => 610,
                'esigibilita' => 'I',
                'default' => 1,
            ],
            [
                'id' => 223,
                'descrizione' => 'Iva Tot. Indetr 12,3%',
                'percentuale' => '12.30',
                'indetraibile' => '100.00',
                'esente' => 0,
                'dicitura' => null,
                'codice_natura_fe' => null,
                'codice' => 613,
                'esigibilita' => 'I',
                'default' => 1,
            ],
            [
                'id' => 224,
                'descrizione' => 'Iva Tot. Indetr 20%',
                'percentuale' => '20.00',
                'indetraibile' => '100.00',
                'esente' => 0,
                'dicitura' => null,
                'codice_natura_fe' => null,
                'codice' => 620,
                'esigibilita' => 'I',
                'default' => 1,
            ],
            [
                'id' => 225,
                'descrizione' => 'Iva Tot. Indetr 21%',
                'percentuale' => '21.00',
                'indetraibile' => '100.00',
                'esente' => 0,
                'dicitura' => null,
                'codice_natura_fe' => null,
                'codice' => 621,
                'esigibilita' => 'I',
                'default' => 1,
            ],
            [
                'id' => 226,
                'descrizione' => 'Iva Tot. Indetr 22%',
                'percentuale' => '22.00',
                'indetraibile' => '100.00',
                'esente' => 0,
                'dicitura' => null,
                'codice_natura_fe' => null,
                'codice' => 622,
                'esigibilita' => 'I',
                'default' => 1,
            ],
            [
                'id' => 227,
                'descrizione' => 'Iva Tot. Indetr 7,3%',
                'percentuale' => '7.30',
                'indetraibile' => '100.00',
                'esente' => 0,
                'dicitura' => null,
                'codice_natura_fe' => null,
                'codice' => 673,
                'esigibilita' => 'I',
                'default' => 1,
            ],
            [
                'id' => 228,
                'descrizione' => 'Iva Tot. Indetr 7,5%',
                'percentuale' => '7.50',
                'indetraibile' => '100.00',
                'esente' => 0,
                'dicitura' => null,
                'codice_natura_fe' => null,
                'codice' => 675,
                'esigibilita' => 'I',
                'default' => 1,
            ],
            [
                'id' => 229,
                'descrizione' => 'Iva Tot. Indetr 7,65%',
                'percentuale' => '7.65',
                'indetraibile' => '100.00',
                'esente' => 0,
                'dicitura' => null,
                'codice_natura_fe' => null,
                'codice' => 676,
                'esigibilita' => 'I',
                'default' => 1,
            ],
            [
                'id' => 230,
                'descrizione' => 'Iva Tot. Indetr 7,7%',
                'percentuale' => '7.70',
                'indetraibile' => '100.00',
                'esente' => 0,
                'dicitura' => null,
                'codice_natura_fe' => null,
                'codice' => 677,
                'esigibilita' => 'I',
                'default' => 1,
            ],
            [
                'id' => 231,
                'descrizione' => 'Iva Tot. Indetr 7,95%',
                'percentuale' => '7.95',
                'indetraibile' => '100.00',
                'esente' => 0,
                'dicitura' => null,
                'codice_natura_fe' => null,
                'codice' => 679,
                'esigibilita' => 'I',
                'default' => 1,
            ],
            [
                'id' => 232,
                'descrizione' => 'Iva Tot. Indetr 8,3%',
                'percentuale' => '8.30',
                'indetraibile' => '100.00',
                'esente' => 0,
                'dicitura' => null,
                'codice_natura_fe' => null,
                'codice' => 683,
                'esigibilita' => 'I',
                'default' => 1,
            ],
            [
                'id' => 233,
                'descrizione' => 'Iva Tot. Indetr 8,5%',
                'percentuale' => '8.50',
                'indetraibile' => '100.00',
                'esente' => 0,
                'dicitura' => null,
                'codice_natura_fe' => null,
                'codice' => 685,
                'esigibilita' => 'I',
                'default' => 1,
            ],
            [
                'id' => 234,
                'descrizione' => 'Iva Tot. Indetr 8,8%',
                'percentuale' => '8.80',
                'indetraibile' => '100.00',
                'esente' => 0,
                'dicitura' => null,
                'codice_natura_fe' => null,
                'codice' => 688,
                'esigibilita' => 'I',
                'default' => 1,
            ],
            [
                'id' => 235,
                'descrizione' => 'Iva Agric. 2%',
                'percentuale' => '2.00',
                'indetraibile' => '0.00',
                'esente' => 0,
                'dicitura' => null,
                'codice_natura_fe' => null,
                'codice' => 802,
                'esigibilita' => 'I',
                'default' => 1,
            ],
            [
                'id' => 236,
                'descrizione' => 'Iva Agric. 4%',
                'percentuale' => '4.00',
                'indetraibile' => '0.00',
                'esente' => 0,
                'dicitura' => null,
                'codice_natura_fe' => null,
                'codice' => 804,
                'esigibilita' => 'I',
                'default' => 1,
            ],
            [
                'id' => 237,
                'descrizione' => 'Iva Agric. 5%',
                'percentuale' => '5.00',
                'indetraibile' => '0.00',
                'esente' => 0,
                'dicitura' => null,
                'codice_natura_fe' => null,
                'codice' => 805,
                'esigibilita' => 'I',
                'default' => 1,
            ],
            [
                'id' => 238,
                'descrizione' => 'Iva Agric. 7%',
                'percentuale' => '7.00',
                'indetraibile' => '0.00',
                'esente' => 0,
                'dicitura' => null,
                'codice_natura_fe' => null,
                'codice' => 807,
                'esigibilita' => 'I',
                'default' => 1,
            ],
            [
                'id' => 239,
                'descrizione' => 'Iva Agric. 8%',
                'percentuale' => '8.00',
                'indetraibile' => '0.00',
                'esente' => 0,
                'dicitura' => null,
                'codice_natura_fe' => null,
                'codice' => 808,
                'esigibilita' => 'I',
                'default' => 1,
            ],
            [
                'id' => 240,
                'descrizione' => 'Iva Agric. 10%',
                'percentuale' => '10.00',
                'indetraibile' => '0.00',
                'esente' => 0,
                'dicitura' => null,
                'codice_natura_fe' => null,
                'codice' => 810,
                'esigibilita' => 'I',
                'default' => 1,
            ],
            [
                'id' => 241,
                'descrizione' => 'Iva Agric. 12,3',
                'percentuale' => '12.30',
                'indetraibile' => '0.00',
                'esente' => 0,
                'dicitura' => null,
                'codice_natura_fe' => null,
                'codice' => 813,
                'esigibilita' => 'I',
                'default' => 1,
            ],
            [
                'id' => 242,
                'descrizione' => 'Iva Agric. 20%',
                'percentuale' => '20.00',
                'indetraibile' => '0.00',
                'esente' => 0,
                'dicitura' => null,
                'codice_natura_fe' => null,
                'codice' => 820,
                'esigibilita' => 'I',
                'default' => 1,
            ],
            [
                'id' => 243,
                'descrizione' => 'Iva Agric. 21%',
                'percentuale' => '21.00',
                'indetraibile' => '0.00',
                'esente' => 0,
                'dicitura' => null,
                'codice_natura_fe' => null,
                'codice' => 821,
                'esigibilita' => 'I',
                'default' => 1,
            ],
            [
                'id' => 244,
                'descrizione' => 'Iva Agric. 22%',
                'percentuale' => '22.00',
                'indetraibile' => '0.00',
                'esente' => 0,
                'dicitura' => null,
                'codice_natura_fe' => null,
                'codice' => 822,
                'esigibilita' => 'I',
                'default' => 1,
            ],
            [
                'id' => 245,
                'descrizione' => 'Iva Agric. 7,3%',
                'percentuale' => '7.30',
                'indetraibile' => '0.00',
                'esente' => 0,
                'dicitura' => null,
                'codice_natura_fe' => null,
                'codice' => 873,
                'esigibilita' => 'I',
                'default' => 1,
            ],
            [
                'id' => 246,
                'descrizione' => 'Iva Agric. 7,5%',
                'percentuale' => '7.50',
                'indetraibile' => '0.00',
                'esente' => 0,
                'dicitura' => null,
                'codice_natura_fe' => null,
                'codice' => 875,
                'esigibilita' => 'I',
                'default' => 1,
            ],
            [
                'id' => 247,
                'descrizione' => 'Iva Agric. 7,65',
                'percentuale' => '7.65',
                'indetraibile' => '0.00',
                'esente' => 0,
                'dicitura' => null,
                'codice_natura_fe' => null,
                'codice' => 876,
                'esigibilita' => 'I',
                'default' => 1,
            ],
            [
                'id' => 248,
                'descrizione' => 'Iva Agric. 7,7%',
                'percentuale' => '7.70',
                'indetraibile' => '0.00',
                'esente' => 0,
                'dicitura' => null,
                'codice_natura_fe' => null,
                'codice' => 877,
                'esigibilita' => 'I',
                'default' => 1,
            ],
            [
                'id' => 249,
                'descrizione' => 'Iva Agric. 7,95',
                'percentuale' => '7.95',
                'indetraibile' => '0.00',
                'esente' => 0,
                'dicitura' => null,
                'codice_natura_fe' => null,
                'codice' => 879,
                'esigibilita' => 'I',
                'default' => 1,
            ],
            [
                'id' => 250,
                'descrizione' => 'Iva Agric. 8,3%',
                'percentuale' => '8.30',
                'indetraibile' => '0.00',
                'esente' => 0,
                'dicitura' => null,
                'codice_natura_fe' => null,
                'codice' => 883,
                'esigibilita' => 'I',
                'default' => 1,
            ],
            [
                'id' => 251,
                'descrizione' => 'Iva Agric. 8,5%',
                'percentuale' => '8.50',
                'indetraibile' => '0.00',
                'esente' => 0,
                'dicitura' => null,
                'codice_natura_fe' => null,
                'codice' => 885,
                'esigibilita' => 'I',
                'default' => 1,
            ],
            [
                'id' => 252,
                'descrizione' => 'Iva Agric. 8,8%',
                'percentuale' => '8.80',
                'indetraibile' => '0.00',
                'esente' => 0,
                'dicitura' => null,
                'codice_natura_fe' => null,
                'codice' => 888,
                'esigibilita' => 'I',
                'default' => 1,
            ],
        ]);
    }
}
