<?php

use Update\Seed;

class CoPagamentiTableSeeder extends Seed
{
    /**
     * Auto generated seed file.
     */
    public function run()
    {
        $this->capsule->table('co_pagamenti')->truncate();

        $this->capsule->table('co_pagamenti')->insert([
            [
                'id' => 1,
                'descrizione' => 'Rimessa diretta',
                'giorno' => 0,
                'num_giorni' => 0,
                'prc' => 100,
                'idconto_vendite' => 1,
                'idconto_acquisti' => 1,
                'codice_modalita_pagamento_fe' => 'MP01',
            ],
            [
                'id' => 2,
                'descrizione' => 'Rimessa diretta a 30gg',
                'giorno' => 0,
                'num_giorni' => 30,
                'prc' => 100,
                'idconto_vendite' => 1,
                'idconto_acquisti' => 1,
                'codice_modalita_pagamento_fe' => 'MP01',
            ],
            [
                'id' => 3,
                'descrizione' => 'Rimessa diretta 30gg fisso al 15',
                'giorno' => 15,
                'num_giorni' => 30,
                'prc' => 100,
                'idconto_vendite' => 1,
                'idconto_acquisti' => 1,
                'codice_modalita_pagamento_fe' => 'MP01',
            ],
            [
                'id' => 4,
                'descrizione' => 'Ri.Ba. 30gg d.f.',
                'giorno' => 0,
                'num_giorni' => 30,
                'prc' => 100,
                'idconto_vendite' => 2,
                'idconto_acquisti' => 2,
                'codice_modalita_pagamento_fe' => 'MP12',
            ],
            [
                'id' => 5,
                'descrizione' => 'Ri.Ba. 60gg d.f.',
                'giorno' => 0,
                'num_giorni' => 60,
                'prc' => 100,
                'idconto_vendite' => 2,
                'idconto_acquisti' => 2,
                'codice_modalita_pagamento_fe' => 'MP12',
            ],
            [
                'id' => 6,
                'descrizione' => 'Ri.Ba. 90gg d.f.',
                'giorno' => 0,
                'num_giorni' => 90,
                'prc' => 100,
                'idconto_vendite' => 2,
                'idconto_acquisti' => 2,
                'codice_modalita_pagamento_fe' => 'MP12',
            ],
            [
                'id' => 7,
                'descrizione' => 'Ri.Ba. 120gg d.f.',
                'giorno' => 0,
                'num_giorni' => 120,
                'prc' => 100,
                'idconto_vendite' => 2,
                'idconto_acquisti' => 2,
                'codice_modalita_pagamento_fe' => 'MP12',
            ],
            [
                'id' => 8,
                'descrizione' => 'Ri.Ba. 150gg d.f.',
                'giorno' => 0,
                'num_giorni' => 150,
                'prc' => 100,
                'idconto_vendite' => 2,
                'idconto_acquisti' => 2,
                'codice_modalita_pagamento_fe' => 'MP12',
            ],
            [
                'id' => 9,
                'descrizione' => 'Ri.Ba. 180gg d.f.',
                'giorno' => 0,
                'num_giorni' => 180,
                'prc' => 100,
                'idconto_vendite' => 2,
                'idconto_acquisti' => 2,
                'codice_modalita_pagamento_fe' => 'MP12',
            ],
            [
                'id' => 10,
                'descrizione' => 'Ri.Ba. 30/60gg d.f.',
                'giorno' => 0,
                'num_giorni' => 30,
                'prc' => 50,
                'idconto_vendite' => 2,
                'idconto_acquisti' => 2,
                'codice_modalita_pagamento_fe' => 'MP12',
            ],
            [
                'id' => 11,
                'descrizione' => 'Ri.Ba. 30/60gg d.f.',
                'giorno' => 0,
                'num_giorni' => 60,
                'prc' => 50,
                'idconto_vendite' => 2,
                'idconto_acquisti' => 2,
                'codice_modalita_pagamento_fe' => 'MP12',
            ],
            [
                'id' => 12,
                'descrizione' => 'Ri.Ba. 30/60/90gg d.f.',
                'giorno' => 0,
                'num_giorni' => 30,
                'prc' => 33,
                'idconto_vendite' => 2,
                'idconto_acquisti' => 2,
                'codice_modalita_pagamento_fe' => 'MP12',
            ],
            [
                'id' => 13,
                'descrizione' => 'Ri.Ba. 30/60/90gg d.f.',
                'giorno' => 0,
                'num_giorni' => 60,
                'prc' => 33,
                'idconto_vendite' => 2,
                'idconto_acquisti' => 2,
                'codice_modalita_pagamento_fe' => 'MP12',
            ],
            [
                'id' => 14,
                'descrizione' => 'Ri.Ba. 30/60/90gg d.f.',
                'giorno' => 0,
                'num_giorni' => 90,
                'prc' => 34,
                'idconto_vendite' => 2,
                'idconto_acquisti' => 2,
                'codice_modalita_pagamento_fe' => 'MP12',
            ],
            [
                'id' => 15,
                'descrizione' => 'Ri.Ba. 30/60/90/120gg d.f.',
                'giorno' => 0,
                'num_giorni' => 30,
                'prc' => 25,
                'idconto_vendite' => 2,
                'idconto_acquisti' => 2,
                'codice_modalita_pagamento_fe' => 'MP12',
            ],
            [
                'id' => 16,
                'descrizione' => 'Ri.Ba. 30/60/90/120gg d.f.',
                'giorno' => 0,
                'num_giorni' => 60,
                'prc' => 25,
                'idconto_vendite' => 2,
                'idconto_acquisti' => 2,
                'codice_modalita_pagamento_fe' => 'MP12',
            ],
            [
                'id' => 17,
                'descrizione' => 'Ri.Ba. 30/60/90/120gg d.f.',
                'giorno' => 0,
                'num_giorni' => 90,
                'prc' => 25,
                'idconto_vendite' => 2,
                'idconto_acquisti' => 2,
                'codice_modalita_pagamento_fe' => 'MP12',
            ],
            [
                'id' => 18,
                'descrizione' => 'Ri.Ba. 30/60/90/120gg d.f.',
                'giorno' => 0,
                'num_giorni' => 120,
                'prc' => 25,
                'idconto_vendite' => 2,
                'idconto_acquisti' => 2,
                'codice_modalita_pagamento_fe' => 'MP12',
            ],
            [
                'id' => 19,
                'descrizione' => 'Ri.Ba. 30/60/90/120/150gg d.f.',
                'giorno' => 0,
                'num_giorni' => 30,
                'prc' => 20,
                'idconto_vendite' => 2,
                'idconto_acquisti' => 2,
                'codice_modalita_pagamento_fe' => 'MP12',
            ],
            [
                'id' => 20,
                'descrizione' => 'Ri.Ba. 30/60/90/120/150gg d.f.',
                'giorno' => 0,
                'num_giorni' => 60,
                'prc' => 20,
                'idconto_vendite' => 2,
                'idconto_acquisti' => 2,
                'codice_modalita_pagamento_fe' => 'MP12',
            ],
            [
                'id' => 21,
                'descrizione' => 'Ri.Ba. 30/60/90/120/150gg d.f.',
                'giorno' => 0,
                'num_giorni' => 90,
                'prc' => 20,
                'idconto_vendite' => 2,
                'idconto_acquisti' => 2,
                'codice_modalita_pagamento_fe' => 'MP12',
            ],
            [
                'id' => 22,
                'descrizione' => 'Ri.Ba. 30/60/90/120/150gg d.f.',
                'giorno' => 0,
                'num_giorni' => 120,
                'prc' => 20,
                'idconto_vendite' => 2,
                'idconto_acquisti' => 2,
                'codice_modalita_pagamento_fe' => 'MP12',
            ],
            [
                'id' => 23,
                'descrizione' => 'Ri.Ba. 30/60/90/120/150gg d.f.',
                'giorno' => 0,
                'num_giorni' => 150,
                'prc' => 20,
                'idconto_vendite' => 2,
                'idconto_acquisti' => 2,
                'codice_modalita_pagamento_fe' => 'MP12',
            ],
            [
                'id' => 24,
                'descrizione' => 'Ri.Ba. 30/60/90/120/150/180gg d.f.',
                'giorno' => 0,
                'num_giorni' => 30,
                'prc' => 16,
                'idconto_vendite' => 2,
                'idconto_acquisti' => 2,
                'codice_modalita_pagamento_fe' => 'MP12',
            ],
            [
                'id' => 25,
                'descrizione' => 'Ri.Ba. 30/60/90/120/150/180gg d.f.',
                'giorno' => 0,
                'num_giorni' => 60,
                'prc' => 16,
                'idconto_vendite' => 2,
                'idconto_acquisti' => 2,
                'codice_modalita_pagamento_fe' => 'MP12',
            ],
            [
                'id' => 26,
                'descrizione' => 'Ri.Ba. 30/60/90/120/150/180gg d.f.',
                'giorno' => 0,
                'num_giorni' => 90,
                'prc' => 16,
                'idconto_vendite' => 2,
                'idconto_acquisti' => 2,
                'codice_modalita_pagamento_fe' => 'MP12',
            ],
            [
                'id' => 27,
                'descrizione' => 'Ri.Ba. 30/60/90/120/150/180gg d.f.',
                'giorno' => 0,
                'num_giorni' => 120,
                'prc' => 16,
                'idconto_vendite' => 2,
                'idconto_acquisti' => 2,
                'codice_modalita_pagamento_fe' => 'MP12',
            ],
            [
                'id' => 28,
                'descrizione' => 'Ri.Ba. 30/60/90/120/150/180gg d.f.',
                'giorno' => 0,
                'num_giorni' => 150,
                'prc' => 16,
                'idconto_vendite' => 2,
                'idconto_acquisti' => 2,
                'codice_modalita_pagamento_fe' => 'MP12',
            ],
            [
                'id' => 29,
                'descrizione' => 'Ri.Ba. 30/60/90/120/150/180gg d.f.',
                'giorno' => 0,
                'num_giorni' => 180,
                'prc' => 20,
                'idconto_vendite' => 2,
                'idconto_acquisti' => 2,
                'codice_modalita_pagamento_fe' => 'MP12',
            ],
            [
                'id' => 30,
                'descrizione' => 'Ri.Ba. 30gg d.f.f.m.',
                'giorno' => -1,
                'num_giorni' => 30,
                'prc' => 100,
                'idconto_vendite' => 2,
                'idconto_acquisti' => 2,
                'codice_modalita_pagamento_fe' => 'MP12',
            ],
            [
                'id' => 31,
                'descrizione' => 'Ri.Ba. 60gg d.f.f.m.',
                'giorno' => -1,
                'num_giorni' => 60,
                'prc' => 100,
                'idconto_vendite' => 2,
                'idconto_acquisti' => 2,
                'codice_modalita_pagamento_fe' => 'MP12',
            ],
            [
                'id' => 32,
                'descrizione' => 'Ri.Ba. 90gg d.f.f.m.',
                'giorno' => -1,
                'num_giorni' => 90,
                'prc' => 100,
                'idconto_vendite' => 2,
                'idconto_acquisti' => 2,
                'codice_modalita_pagamento_fe' => 'MP12',
            ],
            [
                'id' => 33,
                'descrizione' => 'Ri.Ba. 120gg d.f.f.m.',
                'giorno' => -1,
                'num_giorni' => 120,
                'prc' => 100,
                'idconto_vendite' => 2,
                'idconto_acquisti' => 2,
                'codice_modalita_pagamento_fe' => 'MP12',
            ],
            [
                'id' => 34,
                'descrizione' => 'Ri.Ba. 150gg d.f.f.m.',
                'giorno' => -1,
                'num_giorni' => 150,
                'prc' => 100,
                'idconto_vendite' => 2,
                'idconto_acquisti' => 2,
                'codice_modalita_pagamento_fe' => 'MP12',
            ],
            [
                'id' => 35,
                'descrizione' => 'Ri.Ba. 180gg d.f.f.m.',
                'giorno' => -1,
                'num_giorni' => 180,
                'prc' => 100,
                'idconto_vendite' => 2,
                'idconto_acquisti' => 2,
                'codice_modalita_pagamento_fe' => 'MP12',
            ],
            [
                'id' => 36,
                'descrizione' => 'Ri.Ba. 30/60gg d.f.f.m.',
                'giorno' => -1,
                'num_giorni' => 30,
                'prc' => 50,
                'idconto_vendite' => 2,
                'idconto_acquisti' => 2,
                'codice_modalita_pagamento_fe' => 'MP12',
            ],
            [
                'id' => 37,
                'descrizione' => 'Ri.Ba. 30/60gg d.f.f.m.',
                'giorno' => -1,
                'num_giorni' => 60,
                'prc' => 50,
                'idconto_vendite' => 2,
                'idconto_acquisti' => 2,
                'codice_modalita_pagamento_fe' => 'MP12',
            ],
            [
                'id' => 38,
                'descrizione' => 'Ri.Ba. 30/60/90gg d.f.f.m.',
                'giorno' => -1,
                'num_giorni' => 30,
                'prc' => 33,
                'idconto_vendite' => 2,
                'idconto_acquisti' => 2,
                'codice_modalita_pagamento_fe' => 'MP12',
            ],
            [
                'id' => 39,
                'descrizione' => 'Ri.Ba. 30/60/90gg d.f.f.m.',
                'giorno' => -1,
                'num_giorni' => 60,
                'prc' => 33,
                'idconto_vendite' => 2,
                'idconto_acquisti' => 2,
                'codice_modalita_pagamento_fe' => 'MP12',
            ],
            [
                'id' => 40,
                'descrizione' => 'Ri.Ba. 30/60/90gg d.f.f.m.',
                'giorno' => -1,
                'num_giorni' => 90,
                'prc' => 34,
                'idconto_vendite' => 2,
                'idconto_acquisti' => 2,
                'codice_modalita_pagamento_fe' => 'MP12',
            ],
            [
                'id' => 41,
                'descrizione' => 'Ri.Ba. 30/60/90/120gg d.f.f.m.',
                'giorno' => -1,
                'num_giorni' => 30,
                'prc' => 25,
                'idconto_vendite' => 2,
                'idconto_acquisti' => 2,
                'codice_modalita_pagamento_fe' => 'MP12',
            ],
            [
                'id' => 42,
                'descrizione' => 'Ri.Ba. 30/60/90/120gg d.f.f.m.',
                'giorno' => -1,
                'num_giorni' => 60,
                'prc' => 25,
                'idconto_vendite' => 2,
                'idconto_acquisti' => 2,
                'codice_modalita_pagamento_fe' => 'MP12',
            ],
            [
                'id' => 43,
                'descrizione' => 'Ri.Ba. 30/60/90/120gg d.f.f.m.',
                'giorno' => -1,
                'num_giorni' => 90,
                'prc' => 25,
                'idconto_vendite' => 2,
                'idconto_acquisti' => 2,
                'codice_modalita_pagamento_fe' => 'MP12',
            ],
            [
                'id' => 44,
                'descrizione' => 'Ri.Ba. 30/60/90/120gg d.f.f.m.',
                'giorno' => -1,
                'num_giorni' => 120,
                'prc' => 25,
                'idconto_vendite' => 2,
                'idconto_acquisti' => 2,
                'codice_modalita_pagamento_fe' => 'MP12',
            ],
            [
                'id' => 45,
                'descrizione' => 'Ri.Ba. 30/60/90/120/150gg d.f.f.m.',
                'giorno' => -1,
                'num_giorni' => 30,
                'prc' => 20,
                'idconto_vendite' => 2,
                'idconto_acquisti' => 2,
                'codice_modalita_pagamento_fe' => 'MP12',
            ],
            [
                'id' => 46,
                'descrizione' => 'Ri.Ba. 30/60/90/120/150gg d.f.f.m.',
                'giorno' => -1,
                'num_giorni' => 60,
                'prc' => 20,
                'idconto_vendite' => 2,
                'idconto_acquisti' => 2,
                'codice_modalita_pagamento_fe' => 'MP12',
            ],
            [
                'id' => 47,
                'descrizione' => 'Ri.Ba. 30/60/90/120/150gg d.f.f.m.',
                'giorno' => -1,
                'num_giorni' => 90,
                'prc' => 20,
                'idconto_vendite' => 2,
                'idconto_acquisti' => 2,
                'codice_modalita_pagamento_fe' => 'MP12',
            ],
            [
                'id' => 48,
                'descrizione' => 'Ri.Ba. 30/60/90/120/150gg d.f.f.m.',
                'giorno' => -1,
                'num_giorni' => 120,
                'prc' => 20,
                'idconto_vendite' => 2,
                'idconto_acquisti' => 2,
                'codice_modalita_pagamento_fe' => 'MP12',
            ],
            [
                'id' => 49,
                'descrizione' => 'Ri.Ba. 30/60/90/120/150gg d.f.f.m.',
                'giorno' => -1,
                'num_giorni' => 150,
                'prc' => 20,
                'idconto_vendite' => 2,
                'idconto_acquisti' => 2,
                'codice_modalita_pagamento_fe' => 'MP12',
            ],
            [
                'id' => 50,
                'descrizione' => 'Ri.Ba. 30/60/90/120/150/180gg d.f.f.m.',
                'giorno' => -1,
                'num_giorni' => 30,
                'prc' => 16,
                'idconto_vendite' => 2,
                'idconto_acquisti' => 2,
                'codice_modalita_pagamento_fe' => 'MP12',
            ],
            [
                'id' => 51,
                'descrizione' => 'Ri.Ba. 30/60/90/120/150/180gg d.f.f.m.',
                'giorno' => -1,
                'num_giorni' => 60,
                'prc' => 16,
                'idconto_vendite' => 2,
                'idconto_acquisti' => 2,
                'codice_modalita_pagamento_fe' => 'MP12',
            ],
            [
                'id' => 52,
                'descrizione' => 'Ri.Ba. 30/60/90/120/150/180gg d.f.f.m.',
                'giorno' => -1,
                'num_giorni' => 90,
                'prc' => 16,
                'idconto_vendite' => 2,
                'idconto_acquisti' => 2,
                'codice_modalita_pagamento_fe' => 'MP12',
            ],
            [
                'id' => 53,
                'descrizione' => 'Ri.Ba. 30/60/90/120/150/180gg d.f.f.m.',
                'giorno' => -1,
                'num_giorni' => 120,
                'prc' => 16,
                'idconto_vendite' => 2,
                'idconto_acquisti' => 2,
                'codice_modalita_pagamento_fe' => 'MP12',
            ],
            [
                'id' => 54,
                'descrizione' => 'Ri.Ba. 30/60/90/120/150/180gg d.f.f.m.',
                'giorno' => -1,
                'num_giorni' => 150,
                'prc' => 16,
                'idconto_vendite' => 2,
                'idconto_acquisti' => 2,
                'codice_modalita_pagamento_fe' => 'MP12',
            ],
            [
                'id' => 55,
                'descrizione' => 'Ri.Ba. 30/60/90/120/150/180gg d.f.f.m.',
                'giorno' => -1,
                'num_giorni' => 180,
                'prc' => 20,
                'idconto_vendite' => 2,
                'idconto_acquisti' => 2,
                'codice_modalita_pagamento_fe' => 'MP12',
            ],
            [
                'id' => 56,
                'descrizione' => 'Bonifico 30gg d.f.',
                'giorno' => 0,
                'num_giorni' => 30,
                'prc' => 100,
                'idconto_vendite' => 2,
                'idconto_acquisti' => 2,
                'codice_modalita_pagamento_fe' => 'MP05',
            ],
            [
                'id' => 57,
                'descrizione' => 'Bonifico 60gg d.f.',
                'giorno' => 0,
                'num_giorni' => 60,
                'prc' => 100,
                'idconto_vendite' => 2,
                'idconto_acquisti' => 2,
                'codice_modalita_pagamento_fe' => 'MP05',
            ],
            [
                'id' => 58,
                'descrizione' => 'Bonifico 90gg d.f.',
                'giorno' => 0,
                'num_giorni' => 90,
                'prc' => 100,
                'idconto_vendite' => 2,
                'idconto_acquisti' => 2,
                'codice_modalita_pagamento_fe' => 'MP05',
            ],
            [
                'id' => 59,
                'descrizione' => 'Bonifico 120gg d.f.',
                'giorno' => 0,
                'num_giorni' => 120,
                'prc' => 100,
                'idconto_vendite' => 2,
                'idconto_acquisti' => 2,
                'codice_modalita_pagamento_fe' => 'MP05',
            ],
            [
                'id' => 60,
                'descrizione' => 'Bonifico 150gg d.f.',
                'giorno' => 0,
                'num_giorni' => 150,
                'prc' => 100,
                'idconto_vendite' => 2,
                'idconto_acquisti' => 2,
                'codice_modalita_pagamento_fe' => 'MP05',
            ],
            [
                'id' => 61,
                'descrizione' => 'Bonifico 180gg d.f.',
                'giorno' => 0,
                'num_giorni' => 180,
                'prc' => 100,
                'idconto_vendite' => 2,
                'idconto_acquisti' => 2,
                'codice_modalita_pagamento_fe' => 'MP05',
            ],
            [
                'id' => 62,
                'descrizione' => 'Bonifico 30/60gg d.f.',
                'giorno' => 0,
                'num_giorni' => 30,
                'prc' => 50,
                'idconto_vendite' => 2,
                'idconto_acquisti' => 2,
                'codice_modalita_pagamento_fe' => 'MP05',
            ],
            [
                'id' => 63,
                'descrizione' => 'Bonifico 30/60gg d.f.',
                'giorno' => 0,
                'num_giorni' => 60,
                'prc' => 50,
                'idconto_vendite' => 2,
                'idconto_acquisti' => 2,
                'codice_modalita_pagamento_fe' => 'MP05',
            ],
            [
                'id' => 64,
                'descrizione' => 'Bonifico 30/60/90gg d.f.',
                'giorno' => 0,
                'num_giorni' => 30,
                'prc' => 33,
                'idconto_vendite' => 2,
                'idconto_acquisti' => 2,
                'codice_modalita_pagamento_fe' => 'MP05',
            ],
            [
                'id' => 65,
                'descrizione' => 'Bonifico 30/60/90gg d.f.',
                'giorno' => 0,
                'num_giorni' => 60,
                'prc' => 33,
                'idconto_vendite' => 2,
                'idconto_acquisti' => 2,
                'codice_modalita_pagamento_fe' => 'MP05',
            ],
            [
                'id' => 66,
                'descrizione' => 'Bonifico 30/60/90gg d.f.',
                'giorno' => 0,
                'num_giorni' => 90,
                'prc' => 34,
                'idconto_vendite' => 2,
                'idconto_acquisti' => 2,
                'codice_modalita_pagamento_fe' => 'MP05',
            ],
            [
                'id' => 67,
                'descrizione' => 'Bonifico 30/60/90/120gg d.f.',
                'giorno' => 0,
                'num_giorni' => 30,
                'prc' => 25,
                'idconto_vendite' => 2,
                'idconto_acquisti' => 2,
                'codice_modalita_pagamento_fe' => 'MP05',
            ],
            [
                'id' => 68,
                'descrizione' => 'Bonifico 30/60/90/120gg d.f.',
                'giorno' => 0,
                'num_giorni' => 60,
                'prc' => 25,
                'idconto_vendite' => 2,
                'idconto_acquisti' => 2,
                'codice_modalita_pagamento_fe' => 'MP05',
            ],
            [
                'id' => 69,
                'descrizione' => 'Bonifico 30/60/90/120gg d.f.',
                'giorno' => 0,
                'num_giorni' => 90,
                'prc' => 25,
                'idconto_vendite' => 2,
                'idconto_acquisti' => 2,
                'codice_modalita_pagamento_fe' => 'MP05',
            ],
            [
                'id' => 70,
                'descrizione' => 'Bonifico 30/60/90/120gg d.f.',
                'giorno' => 0,
                'num_giorni' => 120,
                'prc' => 25,
                'idconto_vendite' => 2,
                'idconto_acquisti' => 2,
                'codice_modalita_pagamento_fe' => 'MP05',
            ],
            [
                'id' => 71,
                'descrizione' => 'Bonifico 30/60/90/120/150gg d.f.',
                'giorno' => 0,
                'num_giorni' => 30,
                'prc' => 20,
                'idconto_vendite' => 2,
                'idconto_acquisti' => 2,
                'codice_modalita_pagamento_fe' => 'MP05',
            ],
            [
                'id' => 72,
                'descrizione' => 'Bonifico 30/60/90/120/150gg d.f.',
                'giorno' => 0,
                'num_giorni' => 60,
                'prc' => 20,
                'idconto_vendite' => 2,
                'idconto_acquisti' => 2,
                'codice_modalita_pagamento_fe' => 'MP05',
            ],
            [
                'id' => 73,
                'descrizione' => 'Bonifico 30/60/90/120/150gg d.f.',
                'giorno' => 0,
                'num_giorni' => 90,
                'prc' => 20,
                'idconto_vendite' => 2,
                'idconto_acquisti' => 2,
                'codice_modalita_pagamento_fe' => 'MP05',
            ],
            [
                'id' => 74,
                'descrizione' => 'Bonifico 30/60/90/120/150gg d.f.',
                'giorno' => 0,
                'num_giorni' => 120,
                'prc' => 20,
                'idconto_vendite' => 2,
                'idconto_acquisti' => 2,
                'codice_modalita_pagamento_fe' => 'MP05',
            ],
            [
                'id' => 75,
                'descrizione' => 'Bonifico 30/60/90/120/150gg d.f.',
                'giorno' => 0,
                'num_giorni' => 150,
                'prc' => 20,
                'idconto_vendite' => 2,
                'idconto_acquisti' => 2,
                'codice_modalita_pagamento_fe' => 'MP05',
            ],
            [
                'id' => 76,
                'descrizione' => 'Bonifico 30/60/90/120/150/180gg d.f.',
                'giorno' => 0,
                'num_giorni' => 30,
                'prc' => 16,
                'idconto_vendite' => 2,
                'idconto_acquisti' => 2,
                'codice_modalita_pagamento_fe' => 'MP05',
            ],
            [
                'id' => 77,
                'descrizione' => 'Bonifico 30/60/90/120/150/180gg d.f.',
                'giorno' => 0,
                'num_giorni' => 60,
                'prc' => 16,
                'idconto_vendite' => 2,
                'idconto_acquisti' => 2,
                'codice_modalita_pagamento_fe' => 'MP05',
            ],
            [
                'id' => 78,
                'descrizione' => 'Bonifico 30/60/90/120/150/180gg d.f.',
                'giorno' => 0,
                'num_giorni' => 90,
                'prc' => 16,
                'idconto_vendite' => 2,
                'idconto_acquisti' => 2,
                'codice_modalita_pagamento_fe' => 'MP05',
            ],
            [
                'id' => 79,
                'descrizione' => 'Bonifico 30/60/90/120/150/180gg d.f.',
                'giorno' => 0,
                'num_giorni' => 120,
                'prc' => 16,
                'idconto_vendite' => 2,
                'idconto_acquisti' => 2,
                'codice_modalita_pagamento_fe' => 'MP05',
            ],
            [
                'id' => 80,
                'descrizione' => 'Bonifico 30/60/90/120/150/180gg d.f.',
                'giorno' => 0,
                'num_giorni' => 150,
                'prc' => 16,
                'idconto_vendite' => 2,
                'idconto_acquisti' => 2,
                'codice_modalita_pagamento_fe' => 'MP05',
            ],
            [
                'id' => 81,
                'descrizione' => 'Bonifico 30/60/90/120/150/180gg d.f.',
                'giorno' => 0,
                'num_giorni' => 180,
                'prc' => 20,
                'idconto_vendite' => 2,
                'idconto_acquisti' => 2,
                'codice_modalita_pagamento_fe' => 'MP05',
            ],
            [
                'id' => 82,
                'descrizione' => 'Bonifico 30gg d.f.f.m.',
                'giorno' => -1,
                'num_giorni' => 30,
                'prc' => 100,
                'idconto_vendite' => 2,
                'idconto_acquisti' => 2,
                'codice_modalita_pagamento_fe' => 'MP05',
            ],
            [
                'id' => 83,
                'descrizione' => 'Bonifico 60gg d.f.f.m.',
                'giorno' => -1,
                'num_giorni' => 60,
                'prc' => 100,
                'idconto_vendite' => 2,
                'idconto_acquisti' => 2,
                'codice_modalita_pagamento_fe' => 'MP05',
            ],
            [
                'id' => 84,
                'descrizione' => 'Bonifico 90gg d.f.f.m.',
                'giorno' => -1,
                'num_giorni' => 90,
                'prc' => 100,
                'idconto_vendite' => 2,
                'idconto_acquisti' => 2,
                'codice_modalita_pagamento_fe' => 'MP05',
            ],
            [
                'id' => 85,
                'descrizione' => 'Bonifico 120gg d.f.f.m.',
                'giorno' => -1,
                'num_giorni' => 120,
                'prc' => 100,
                'idconto_vendite' => 2,
                'idconto_acquisti' => 2,
                'codice_modalita_pagamento_fe' => 'MP05',
            ],
            [
                'id' => 86,
                'descrizione' => 'Bonifico 150gg d.f.f.m.',
                'giorno' => -1,
                'num_giorni' => 150,
                'prc' => 100,
                'idconto_vendite' => 2,
                'idconto_acquisti' => 2,
                'codice_modalita_pagamento_fe' => 'MP05',
            ],
            [
                'id' => 87,
                'descrizione' => 'Bonifico 180gg d.f.f.m.',
                'giorno' => -1,
                'num_giorni' => 180,
                'prc' => 100,
                'idconto_vendite' => 2,
                'idconto_acquisti' => 2,
                'codice_modalita_pagamento_fe' => 'MP05',
            ],
            [
                'id' => 88,
                'descrizione' => 'Bonifico 30/60gg d.f.f.m.',
                'giorno' => -1,
                'num_giorni' => 30,
                'prc' => 50,
                'idconto_vendite' => 2,
                'idconto_acquisti' => 2,
                'codice_modalita_pagamento_fe' => 'MP05',
            ],
            [
                'id' => 89,
                'descrizione' => 'Bonifico 30/60gg d.f.f.m.',
                'giorno' => -1,
                'num_giorni' => 60,
                'prc' => 50,
                'idconto_vendite' => 2,
                'idconto_acquisti' => 2,
                'codice_modalita_pagamento_fe' => 'MP05',
            ],
            [
                'id' => 90,
                'descrizione' => 'Bonifico 30/60/90gg d.f.f.m.',
                'giorno' => -1,
                'num_giorni' => 30,
                'prc' => 33,
                'idconto_vendite' => 2,
                'idconto_acquisti' => 2,
                'codice_modalita_pagamento_fe' => 'MP05',
            ],
            [
                'id' => 91,
                'descrizione' => 'Bonifico 30/60/90gg d.f.f.m.',
                'giorno' => -1,
                'num_giorni' => 60,
                'prc' => 33,
                'idconto_vendite' => 2,
                'idconto_acquisti' => 2,
                'codice_modalita_pagamento_fe' => 'MP05',
            ],
            [
                'id' => 92,
                'descrizione' => 'Bonifico 30/60/90gg d.f.f.m.',
                'giorno' => -1,
                'num_giorni' => 90,
                'prc' => 34,
                'idconto_vendite' => 2,
                'idconto_acquisti' => 2,
                'codice_modalita_pagamento_fe' => 'MP05',
            ],
            [
                'id' => 93,
                'descrizione' => 'Bonifico 30/60/90/120gg d.f.f.m.',
                'giorno' => -1,
                'num_giorni' => 30,
                'prc' => 25,
                'idconto_vendite' => 2,
                'idconto_acquisti' => 2,
                'codice_modalita_pagamento_fe' => 'MP05',
            ],
            [
                'id' => 94,
                'descrizione' => 'Bonifico 30/60/90/120gg d.f.f.m.',
                'giorno' => -1,
                'num_giorni' => 60,
                'prc' => 25,
                'idconto_vendite' => 2,
                'idconto_acquisti' => 2,
                'codice_modalita_pagamento_fe' => 'MP05',
            ],
            [
                'id' => 95,
                'descrizione' => 'Bonifico 30/60/90/120gg d.f.f.m.',
                'giorno' => -1,
                'num_giorni' => 90,
                'prc' => 25,
                'idconto_vendite' => 2,
                'idconto_acquisti' => 2,
                'codice_modalita_pagamento_fe' => 'MP05',
            ],
            [
                'id' => 96,
                'descrizione' => 'Bonifico 30/60/90/120gg d.f.f.m.',
                'giorno' => -1,
                'num_giorni' => 120,
                'prc' => 25,
                'idconto_vendite' => 2,
                'idconto_acquisti' => 2,
                'codice_modalita_pagamento_fe' => 'MP05',
            ],
            [
                'id' => 97,
                'descrizione' => 'Bonifico 30/60/90/120/150gg d.f.f.m.',
                'giorno' => -1,
                'num_giorni' => 30,
                'prc' => 20,
                'idconto_vendite' => 2,
                'idconto_acquisti' => 2,
                'codice_modalita_pagamento_fe' => 'MP05',
            ],
            [
                'id' => 98,
                'descrizione' => 'Bonifico 30/60/90/120/150gg d.f.f.m.',
                'giorno' => -1,
                'num_giorni' => 60,
                'prc' => 20,
                'idconto_vendite' => 2,
                'idconto_acquisti' => 2,
                'codice_modalita_pagamento_fe' => 'MP05',
            ],
            [
                'id' => 99,
                'descrizione' => 'Bonifico 30/60/90/120/150gg d.f.f.m.',
                'giorno' => -1,
                'num_giorni' => 90,
                'prc' => 20,
                'idconto_vendite' => 2,
                'idconto_acquisti' => 2,
                'codice_modalita_pagamento_fe' => 'MP05',
            ],
            [
                'id' => 100,
                'descrizione' => 'Bonifico 30/60/90/120/150gg d.f.f.m.',
                'giorno' => -1,
                'num_giorni' => 120,
                'prc' => 20,
                'idconto_vendite' => 2,
                'idconto_acquisti' => 2,
                'codice_modalita_pagamento_fe' => 'MP05',
            ],
            [
                'id' => 101,
                'descrizione' => 'Bonifico 30/60/90/120/150gg d.f.f.m.',
                'giorno' => -1,
                'num_giorni' => 150,
                'prc' => 20,
                'idconto_vendite' => 2,
                'idconto_acquisti' => 2,
                'codice_modalita_pagamento_fe' => 'MP05',
            ],
            [
                'id' => 102,
                'descrizione' => 'Bonifico 30/60/90/120/150/180gg d.f.f.m.',
                'giorno' => -1,
                'num_giorni' => 30,
                'prc' => 16,
                'idconto_vendite' => 2,
                'idconto_acquisti' => 2,
                'codice_modalita_pagamento_fe' => 'MP05',
            ],
            [
                'id' => 103,
                'descrizione' => 'Bonifico 30/60/90/120/150/180gg d.f.f.m.',
                'giorno' => -1,
                'num_giorni' => 60,
                'prc' => 16,
                'idconto_vendite' => 2,
                'idconto_acquisti' => 2,
                'codice_modalita_pagamento_fe' => 'MP05',
            ],
            [
                'id' => 104,
                'descrizione' => 'Bonifico 30/60/90/120/150/180gg d.f.f.m.',
                'giorno' => -1,
                'num_giorni' => 90,
                'prc' => 16,
                'idconto_vendite' => 2,
                'idconto_acquisti' => 2,
                'codice_modalita_pagamento_fe' => 'MP05',
            ],
            [
                'id' => 105,
                'descrizione' => 'Bonifico 30/60/90/120/150/180gg d.f.f.m.',
                'giorno' => -1,
                'num_giorni' => 120,
                'prc' => 16,
                'idconto_vendite' => 2,
                'idconto_acquisti' => 2,
                'codice_modalita_pagamento_fe' => 'MP05',
            ],
            [
                'id' => 106,
                'descrizione' => 'Bonifico 30/60/90/120/150/180gg d.f.f.m.',
                'giorno' => -1,
                'num_giorni' => 150,
                'prc' => 16,
                'idconto_vendite' => 2,
                'idconto_acquisti' => 2,
                'codice_modalita_pagamento_fe' => 'MP05',
            ],
            [
                'id' => 107,
                'descrizione' => 'Bonifico 30/60/90/120/150/180gg d.f.f.m.',
                'giorno' => -1,
                'num_giorni' => 180,
                'prc' => 20,
                'idconto_vendite' => 2,
                'idconto_acquisti' => 2,
                'codice_modalita_pagamento_fe' => 'MP05',
            ],
            [
                'id' => 108,
                'descrizione' => 'Cambiale',
                'giorno' => 0,
                'num_giorni' => 0,
                'prc' => 100,
                'idconto_vendite' => null,
                'idconto_acquisti' => null,
                'codice_modalita_pagamento_fe' => 'MP06',
            ],
            [
                'id' => 109,
                'descrizione' => 'Assegno',
                'giorno' => 0,
                'num_giorni' => 0,
                'prc' => 100,
                'idconto_vendite' => null,
                'idconto_acquisti' => null,
                'codice_modalita_pagamento_fe' => 'MP02',
            ],
            [
                'id' => 110,
                'descrizione' => 'Bancomat',
                'giorno' => 0,
                'num_giorni' => 0,
                'prc' => 100,
                'idconto_vendite' => null,
                'idconto_acquisti' => null,
                'codice_modalita_pagamento_fe' => 'MP08',
            ],
            [
                'id' => 111,
                'descrizione' => 'Contanti',
                'giorno' => 0,
                'num_giorni' => 0,
                'prc' => 100,
                'idconto_vendite' => 1,
                'idconto_acquisti' => 1,
                'codice_modalita_pagamento_fe' => 'MP01',
            ],
            [
                'id' => 112,
                'descrizione' => 'Visa',
                'giorno' => 0,
                'num_giorni' => 0,
                'prc' => 100,
                'idconto_vendite' => null,
                'idconto_acquisti' => null,
                'codice_modalita_pagamento_fe' => 'MP08',
            ],
            [
                'id' => 113,
                'descrizione' => 'Bonifico bancario',
                'giorno' => 0,
                'num_giorni' => 10,
                'prc' => 100,
                'idconto_vendite' => 2,
                'idconto_acquisti' => 2,
                'codice_modalita_pagamento_fe' => 'MP05',
            ],
        ]);
    }
}
