<?php

use Update\Seed;

class CoPianodeiconti3TableSeeder extends Seed
{
    /**
     * Auto generated seed file.
     */
    public function run()
    {
        $this->capsule->table('co_pianodeiconti3')->truncate();

        $this->capsule->table('co_pianodeiconti3')->insert([
            [
                'id' => 1,
                'numero' => '000010',
                'descrizione' => 'Cassa',
                'idpianodeiconti2' => 1,
                'dir' => '',
                'can_delete' => 0,
                'can_edit' => 0,
            ],
            [
                'id' => 2,
                'numero' => '000020',
                'descrizione' => 'Banca C/C',
                'idpianodeiconti2' => 1,
                'dir' => '',
                'can_delete' => 0,
                'can_edit' => 0,
            ],
            [
                'id' => 3,
                'numero' => '000030',
                'descrizione' => 'Effetti in portafoglio',
                'idpianodeiconti2' => 1,
                'dir' => '',
                'can_delete' => 0,
                'can_edit' => 0,
            ],
            [
                'id' => 4,
                'numero' => '000040',
                'descrizione' => 'Banca effetti all\'incasso',
                'idpianodeiconti2' => 1,
                'dir' => '',
                'can_delete' => 0,
                'can_edit' => 0,
            ],
            [
                'id' => 5,
                'numero' => '000050',
                'descrizione' => 'Titoli',
                'idpianodeiconti2' => 1,
                'dir' => '',
                'can_delete' => 0,
                'can_edit' => 0,
            ],
            [
                'id' => 6,
                'numero' => '000010',
                'descrizione' => 'Riepilogativo clienti',
                'idpianodeiconti2' => 2,
                'dir' => '',
                'can_delete' => 0,
                'can_edit' => 0,
            ],
            [
                'id' => 7,
                'numero' => '000030',
                'descrizione' => 'Clienti per fatture da emettere',
                'idpianodeiconti2' => 2,
                'dir' => '',
                'can_delete' => 0,
                'can_edit' => 0,
            ],
            [
                'id' => 8,
                'numero' => '000040',
                'descrizione' => 'Crediti imposte',
                'idpianodeiconti2' => 2,
                'dir' => '',
                'can_delete' => 0,
                'can_edit' => 0,
            ],
            [
                'id' => 9,
                'numero' => '000050',
                'descrizione' => 'Crediti diversi',
                'idpianodeiconti2' => 2,
                'dir' => '',
                'can_delete' => 0,
                'can_edit' => 0,
            ],
            [
                'id' => 10,
                'numero' => '000060',
                'descrizione' => 'Ri.Ba in portafoglio',
                'idpianodeiconti2' => 2,
                'dir' => '',
                'can_delete' => 0,
                'can_edit' => 0,
            ],
            [
                'id' => 11,
                'numero' => '000080',
                'descrizione' => 'Dipendenti c/stipendi',
                'idpianodeiconti2' => 2,
                'dir' => '',
                'can_delete' => 0,
                'can_edit' => 0,
            ],
            [
                'id' => 12,
                'numero' => '000090',
                'descrizione' => 'Amministratori c/emolumenti',
                'idpianodeiconti2' => 2,
                'dir' => '',
                'can_delete' => 0,
                'can_edit' => 0,
            ],
            [
                'id' => 13,
                'numero' => '000010',
                'descrizione' => 'Effetti allo sconto',
                'idpianodeiconti2' => 3,
                'dir' => '',
                'can_delete' => 0,
                'can_edit' => 0,
            ],
            [
                'id' => 14,
                'numero' => '000020',
                'descrizione' => 'Effetti all\'incasso',
                'idpianodeiconti2' => 3,
                'dir' => '',
                'can_delete' => 0,
                'can_edit' => 0,
            ],
            [
                'id' => 15,
                'numero' => '000030',
                'descrizione' => 'Effetti insoluti',
                'idpianodeiconti2' => 3,
                'dir' => '',
                'can_delete' => 0,
                'can_edit' => 0,
            ],
            [
                'id' => 16,
                'numero' => '000010',
                'descrizione' => 'Risconti attivi',
                'idpianodeiconti2' => 4,
                'dir' => '',
                'can_delete' => 0,
                'can_edit' => 0,
            ],
            [
                'id' => 17,
                'numero' => '000020',
                'descrizione' => 'Ratei attivi',
                'idpianodeiconti2' => 4,
                'dir' => '',
                'can_delete' => 0,
                'can_edit' => 0,
            ],
            [
                'id' => 18,
                'numero' => '000005',
                'descrizione' => 'Erario c/to iva',
                'idpianodeiconti2' => 5,
                'dir' => '',
                'can_delete' => 0,
                'can_edit' => 0,
            ],
            [
                'id' => 19,
                'numero' => '000010',
                'descrizione' => 'Erario c/INPS',
                'idpianodeiconti2' => 5,
                'dir' => '',
                'can_delete' => 0,
                'can_edit' => 0,
            ],
            [
                'id' => 20,
                'numero' => '000030',
                'descrizione' => 'Erario c/IRPEF',
                'idpianodeiconti2' => 5,
                'dir' => '',
                'can_delete' => 0,
                'can_edit' => 0,
            ],
            [
                'id' => 21,
                'numero' => '000040',
                'descrizione' => 'Erario c/INAIL',
                'idpianodeiconti2' => 5,
                'dir' => '',
                'can_delete' => 0,
                'can_edit' => 0,
            ],
            [
                'id' => 22,
                'numero' => '000050',
                'descrizione' => 'Erario c/acconto TFR',
                'idpianodeiconti2' => 5,
                'dir' => '',
                'can_delete' => 0,
                'can_edit' => 0,
            ],
            [
                'id' => 23,
                'numero' => '000060',
                'descrizione' => 'Erario c/ritenute d\'acconto',
                'idpianodeiconti2' => 5,
                'dir' => '',
                'can_delete' => 0,
                'can_edit' => 0,
            ],
            [
                'id' => 24,
                'numero' => '000070',
                'descrizione' => 'Erario c/enasarco',
                'idpianodeiconti2' => 5,
                'dir' => '',
                'can_delete' => 0,
                'can_edit' => 0,
            ],
            [
                'id' => 25,
                'numero' => '000080',
                'descrizione' => 'Erario c/varie',
                'idpianodeiconti2' => 5,
                'dir' => '',
                'can_delete' => 0,
                'can_edit' => 0,
            ],
            [
                'id' => 26,
                'numero' => '000010',
                'descrizione' => 'Fabbricati',
                'idpianodeiconti2' => 6,
                'dir' => '',
                'can_delete' => 1,
                'can_edit' => 0,
            ],
            [
                'id' => 27,
                'numero' => '000020',
                'descrizione' => 'Mobili e macchine da ufficio',
                'idpianodeiconti2' => 6,
                'dir' => '',
                'can_delete' => 0,
                'can_edit' => 0,
            ],
            [
                'id' => 28,
                'numero' => '000030',
                'descrizione' => 'Automezzi',
                'idpianodeiconti2' => 6,
                'dir' => '',
                'can_delete' => 0,
                'can_edit' => 0,
            ],
            [
                'id' => 29,
                'numero' => '000040',
                'descrizione' => 'Impianti e attrezzature',
                'idpianodeiconti2' => 6,
                'dir' => '',
                'can_delete' => 0,
                'can_edit' => 0,
            ],
            [
                'id' => 30,
                'numero' => '000060',
                'descrizione' => 'Manutenzione da ammortizzare',
                'idpianodeiconti2' => 6,
                'dir' => '',
                'can_delete' => 0,
                'can_edit' => 0,
            ],
            [
                'id' => 31,
                'numero' => '000070',
                'descrizione' => 'Costi pluriennali',
                'idpianodeiconti2' => 6,
                'dir' => '',
                'can_delete' => 0,
                'can_edit' => 0,
            ],
            [
                'id' => 32,
                'numero' => '000010',
                'descrizione' => 'Merci c/to rimanenze materie prime',
                'idpianodeiconti2' => 7,
                'dir' => '',
                'can_delete' => 0,
                'can_edit' => 0,
            ],
            [
                'id' => 33,
                'numero' => '000020',
                'descrizione' => 'Merci c/to rimanenze semilavorati',
                'idpianodeiconti2' => 7,
                'dir' => '',
                'can_delete' => 0,
                'can_edit' => 0,
            ],
            [
                'id' => 34,
                'numero' => '000010',
                'descrizione' => 'Riepilogativo fornitori',
                'idpianodeiconti2' => 8,
                'dir' => '',
                'can_delete' => 0,
                'can_edit' => 0,
            ],
            [
                'id' => 35,
                'numero' => '000020',
                'descrizione' => 'Cambiali passive',
                'idpianodeiconti2' => 8,
                'dir' => '',
                'can_delete' => 0,
                'can_edit' => 0,
            ],
            [
                'id' => 36,
                'numero' => '000030',
                'descrizione' => 'Mutui passivi',
                'idpianodeiconti2' => 8,
                'dir' => '',
                'can_delete' => 0,
                'can_edit' => 0,
            ],
            [
                'id' => 37,
                'numero' => '000040',
                'descrizione' => 'Debiti verso banche',
                'idpianodeiconti2' => 8,
                'dir' => '',
                'can_delete' => 0,
                'can_edit' => 0,
            ],
            [
                'id' => 38,
                'numero' => '000050',
                'descrizione' => 'Fornitori per fatture da ricevere',
                'idpianodeiconti2' => 8,
                'dir' => '',
                'can_delete' => 0,
                'can_edit' => 0,
            ],
            [
                'id' => 39,
                'numero' => '000060',
                'descrizione' => 'Debiti diversi',
                'idpianodeiconti2' => 8,
                'dir' => '',
                'can_delete' => 0,
                'can_edit' => 0,
            ],
            [
                'id' => 40,
                'numero' => '000070',
                'descrizione' => 'Finanziamenti vari',
                'idpianodeiconti2' => 8,
                'dir' => '',
                'can_delete' => 0,
                'can_edit' => 0,
            ],
            [
                'id' => 41,
                'numero' => '000200',
                'descrizione' => 'Riepilogativo fornitori contabilit&agrave; semplificata',
                'idpianodeiconti2' => 8,
                'dir' => '',
                'can_delete' => 0,
                'can_edit' => 0,
            ],
            [
                'id' => 42,
                'numero' => '000010',
                'descrizione' => 'Risconti passivi',
                'idpianodeiconti2' => 9,
                'dir' => '',
                'can_delete' => 0,
                'can_edit' => 0,
            ],
            [
                'id' => 43,
                'numero' => '000020',
                'descrizione' => 'Ratei passivi',
                'idpianodeiconti2' => 9,
                'dir' => '',
                'can_delete' => 0,
                'can_edit' => 0,
            ],
            [
                'id' => 44,
                'numero' => '000010',
                'descrizione' => 'Fondi ammortamento fabbricati',
                'idpianodeiconti2' => 10,
                'dir' => '',
                'can_delete' => 0,
                'can_edit' => 0,
            ],
            [
                'id' => 45,
                'numero' => '000020',
                'descrizione' => 'Fondi ammortamento mobili e macchine da ufficio',
                'idpianodeiconti2' => 10,
                'dir' => '',
                'can_delete' => 0,
                'can_edit' => 0,
            ],
            [
                'id' => 46,
                'numero' => '000030',
                'descrizione' => 'Fondi ammortamento automezzi',
                'idpianodeiconti2' => 10,
                'dir' => '',
                'can_delete' => 0,
                'can_edit' => 0,
            ],
            [
                'id' => 47,
                'numero' => '000040',
                'descrizione' => 'Fondi ammortamento impianti e attrezzature',
                'idpianodeiconti2' => 10,
                'dir' => '',
                'can_delete' => 0,
                'can_edit' => 0,
            ],
            [
                'id' => 48,
                'numero' => '000060',
                'descrizione' => 'Fondi ammortamento manutenzione da ammortizzare',
                'idpianodeiconti2' => 10,
                'dir' => '',
                'can_delete' => 0,
                'can_edit' => 0,
            ],
            [
                'id' => 49,
                'numero' => '000070',
                'descrizione' => 'Fondi ammortamento costi pluriennali',
                'idpianodeiconti2' => 10,
                'dir' => '',
                'can_delete' => 0,
                'can_edit' => 0,
            ],
            [
                'id' => 50,
                'numero' => '000010',
                'descrizione' => 'Fondo imposte e tasse',
                'idpianodeiconti2' => 11,
                'dir' => '',
                'can_delete' => 0,
                'can_edit' => 0,
            ],
            [
                'id' => 51,
                'numero' => '000020',
                'descrizione' => 'Fondo TFR liquidazione personale',
                'idpianodeiconti2' => 11,
                'dir' => '',
                'can_delete' => 0,
                'can_edit' => 0,
            ],
            [
                'id' => 52,
                'numero' => '000010',
                'descrizione' => 'Capitale sociale o netto',
                'idpianodeiconti2' => 12,
                'dir' => '',
                'can_delete' => 0,
                'can_edit' => 0,
            ],
            [
                'id' => 53,
                'numero' => '000020',
                'descrizione' => 'Riserve',
                'idpianodeiconti2' => 12,
                'dir' => '',
                'can_delete' => 0,
                'can_edit' => 0,
            ],
            [
                'id' => 55,
                'numero' => '000010',
                'descrizione' => 'Costi merci c/acquisto di rivendita',
                'idpianodeiconti2' => 14,
                'dir' => 'uscita',
                'can_delete' => 0,
                'can_edit' => 0,
            ],
            [
                'id' => 56,
                'numero' => '000020',
                'descrizione' => 'Costi merci c/acquisto di produzione',
                'idpianodeiconti2' => 14,
                'dir' => 'uscita',
                'can_delete' => 0,
                'can_edit' => 0,
            ],
            [
                'id' => 57,
                'numero' => '000030',
                'descrizione' => 'Costi merci c/acquisto intracomunitario',
                'idpianodeiconti2' => 14,
                'dir' => 'uscita',
                'can_delete' => 0,
                'can_edit' => 0,
            ],
            [
                'id' => 58,
                'numero' => '000040',
                'descrizione' => 'Costi merci c/acquisto importazioni',
                'idpianodeiconti2' => 14,
                'dir' => 'uscita',
                'can_delete' => 0,
                'can_edit' => 0,
            ],
            [
                'id' => 59,
                'numero' => '000010',
                'descrizione' => 'Spese telefoniche',
                'idpianodeiconti2' => 15,
                'dir' => 'uscita',
                'can_delete' => 1,
                'can_edit' => 1,
            ],
            [
                'id' => 60,
                'numero' => '000020',
                'descrizione' => 'Spese postali',
                'idpianodeiconti2' => 15,
                'dir' => 'uscita',
                'can_delete' => 1,
                'can_edit' => 1,
            ],
            [
                'id' => 61,
                'numero' => '000030',
                'descrizione' => 'Spese cancelleria',
                'idpianodeiconti2' => 15,
                'dir' => 'uscita',
                'can_delete' => 1,
                'can_edit' => 1,
            ],
            [
                'id' => 62,
                'numero' => '000040',
                'descrizione' => 'Spese locomozione e carburante',
                'idpianodeiconti2' => 15,
                'dir' => 'uscita',
                'can_delete' => 0,
                'can_edit' => 0,
            ],
            [
                'id' => 63,
                'numero' => '000050',
                'descrizione' => 'Spese software',
                'idpianodeiconti2' => 15,
                'dir' => 'uscita',
                'can_delete' => 1,
                'can_edit' => 1,
            ],
            [
                'id' => 64,
                'numero' => '000060',
                'descrizione' => 'Spese energia elettrica',
                'idpianodeiconti2' => 15,
                'dir' => 'uscita',
                'can_delete' => 1,
                'can_edit' => 1,
            ],
            [
                'id' => 65,
                'numero' => '000070',
                'descrizione' => 'Spese consulenze',
                'idpianodeiconti2' => 15,
                'dir' => 'uscita',
                'can_delete' => 1,
                'can_edit' => 1,
            ],
            [
                'id' => 66,
                'numero' => '000080',
                'descrizione' => 'Spese varie',
                'idpianodeiconti2' => 15,
                'dir' => 'uscita',
                'can_delete' => 1,
                'can_edit' => 1,
            ],
            [
                'id' => 67,
                'numero' => '000090',
                'descrizione' => 'Spese assicurazioni',
                'idpianodeiconti2' => 15,
                'dir' => 'uscita',
                'can_delete' => 1,
                'can_edit' => 1,
            ],
            [
                'id' => 68,
                'numero' => '000100',
                'descrizione' => 'Spese bancarie',
                'idpianodeiconti2' => 15,
                'dir' => 'uscita',
                'can_delete' => 1,
                'can_edit' => 1,
            ],
            [
                'id' => 69,
                'numero' => '000110',
                'descrizione' => 'Spese fitti passivi',
                'idpianodeiconti2' => 15,
                'dir' => 'uscita',
                'can_delete' => 1,
                'can_edit' => 1,
            ],
            [
                'id' => 70,
                'numero' => '000120',
                'descrizione' => 'Spese ristoranti e alberghi',
                'idpianodeiconti2' => 15,
                'dir' => 'uscita',
                'can_delete' => 1,
                'can_edit' => 1,
            ],
            [
                'id' => 71,
                'numero' => '000130',
                'descrizione' => 'Spese manutenzione e riparazione',
                'idpianodeiconti2' => 15,
                'dir' => 'uscita',
                'can_delete' => 1,
                'can_edit' => 1,
            ],
            [
                'id' => 72,
                'numero' => '000140',
                'descrizione' => 'Spese canoni leasing',
                'idpianodeiconti2' => 15,
                'dir' => 'uscita',
                'can_delete' => 1,
                'can_edit' => 1,
            ],
            [
                'id' => 73,
                'numero' => '000150',
                'descrizione' => 'Spese acquisto beni strumentali non ammortizzabilii',
                'idpianodeiconti2' => 15,
                'dir' => 'uscita',
                'can_delete' => 0,
                'can_edit' => 0,
            ],
            [
                'id' => 74,
                'numero' => '000010',
                'descrizione' => 'Costi interessi passivi',
                'idpianodeiconti2' => 16,
                'dir' => '',
                'can_delete' => 0,
                'can_edit' => 0,
            ],
            [
                'id' => 75,
                'numero' => '000020',
                'descrizione' => 'Costi abbuoni passivi',
                'idpianodeiconti2' => 16,
                'dir' => '',
                'can_delete' => 0,
                'can_edit' => 0,
            ],
            [
                'id' => 76,
                'numero' => '000030',
                'descrizione' => 'Costi imposte e tasse',
                'idpianodeiconti2' => 16,
                'dir' => '',
                'can_delete' => 0,
                'can_edit' => 0,
            ],
            [
                'id' => 77,
                'numero' => '000040',
                'descrizione' => 'Costi imposta IRA',
                'idpianodeiconti2' => 16,
                'dir' => '',
                'can_delete' => 0,
                'can_edit' => 0,
            ],
            [
                'id' => 78,
                'numero' => '000050',
                'descrizione' => 'Costi minusvalenze',
                'idpianodeiconti2' => 16,
                'dir' => '',
                'can_delete' => 0,
                'can_edit' => 0,
            ],
            [
                'id' => 79,
                'numero' => '000060',
                'descrizione' => 'Costi perdite su crediti',
                'idpianodeiconti2' => 16,
                'dir' => '',
                'can_delete' => 0,
                'can_edit' => 0,
            ],
            [
                'id' => 80,
                'numero' => '000070',
                'descrizione' => 'Costi sopravvenienze passive',
                'idpianodeiconti2' => 16,
                'dir' => '',
                'can_delete' => 0,
                'can_edit' => 0,
            ],
            [
                'id' => 81,
                'numero' => '000080',
                'descrizione' => 'Costi perdite da operazioni finanziarie',
                'idpianodeiconti2' => 16,
                'dir' => '',
                'can_delete' => 0,
                'can_edit' => 0,
            ],
            [
                'id' => 82,
                'numero' => '000010',
                'descrizione' => 'Costi salari e stipendi',
                'idpianodeiconti2' => 17,
                'dir' => '',
                'can_delete' => 0,
                'can_edit' => 0,
            ],
            [
                'id' => 83,
                'numero' => '000020',
                'descrizione' => 'Costi contributi sociali',
                'idpianodeiconti2' => 17,
                'dir' => '',
                'can_delete' => 0,
                'can_edit' => 0,
            ],
            [
                'id' => 84,
                'numero' => '000040',
                'descrizione' => 'Costi TFR',
                'idpianodeiconti2' => 17,
                'dir' => '',
                'can_delete' => 0,
                'can_edit' => 0,
            ],
            [
                'id' => 85,
                'numero' => '000050',
                'descrizione' => 'Costi contributi dipendenti',
                'idpianodeiconti2' => 17,
                'dir' => '',
                'can_delete' => 0,
                'can_edit' => 0,
            ],
            [
                'id' => 86,
                'numero' => '000060',
                'descrizione' => 'Costi contributi assicurazione lavoro',
                'idpianodeiconti2' => 17,
                'dir' => '',
                'can_delete' => 0,
                'can_edit' => 0,
            ],
            [
                'id' => 87,
                'numero' => '000010',
                'descrizione' => 'Ammortamento fabbricati',
                'idpianodeiconti2' => 18,
                'dir' => '',
                'can_delete' => 0,
                'can_edit' => 0,
            ],
            [
                'id' => 88,
                'numero' => '000020',
                'descrizione' => 'Ammortamento mobili e macchine ufficio',
                'idpianodeiconti2' => 18,
                'dir' => '',
                'can_delete' => 0,
                'can_edit' => 0,
            ],
            [
                'id' => 89,
                'numero' => '000030',
                'descrizione' => 'Ammortamento automezzi',
                'idpianodeiconti2' => 18,
                'dir' => '',
                'can_delete' => 0,
                'can_edit' => 0,
            ],
            [
                'id' => 90,
                'numero' => '000040',
                'descrizione' => 'Ammortamento impianti e attrezzature',
                'idpianodeiconti2' => 18,
                'dir' => '',
                'can_delete' => 0,
                'can_edit' => 0,
            ],
            [
                'id' => 91,
                'numero' => '000060',
                'descrizione' => 'Ammortamento manutenzioni',
                'idpianodeiconti2' => 18,
                'dir' => '',
                'can_delete' => 0,
                'can_edit' => 0,
            ],
            [
                'id' => 92,
                'numero' => '000070',
                'descrizione' => 'Ammortamento costi pluriennali',
                'idpianodeiconti2' => 18,
                'dir' => '',
                'can_delete' => 0,
                'can_edit' => 0,
            ],
            [
                'id' => 93,
                'numero' => '000010',
                'descrizione' => 'Accantonamento TFR',
                'idpianodeiconti2' => 19,
                'dir' => '',
                'can_delete' => 0,
                'can_edit' => 0,
            ],
            [
                'id' => 94,
                'numero' => '000010',
                'descrizione' => 'Ricavi merci c/to vendite',
                'idpianodeiconti2' => 20,
                'dir' => 'entrata',
                'can_delete' => 0,
                'can_edit' => 0,
            ],
            [
                'id' => 95,
                'numero' => '000020',
                'descrizione' => 'Ricavi vendita prestazione servizi',
                'idpianodeiconti2' => 20,
                'dir' => 'entrata',
                'can_delete' => 0,
                'can_edit' => 0,
            ],
            [
                'id' => 96,
                'numero' => '000030',
                'descrizione' => 'Ricavi interessi attivi',
                'idpianodeiconti2' => 20,
                'dir' => 'entrata',
                'can_delete' => 0,
                'can_edit' => 0,
            ],
            [
                'id' => 97,
                'numero' => '000040',
                'descrizione' => 'Ricavi fitti attivi',
                'idpianodeiconti2' => 20,
                'dir' => 'entrata',
                'can_delete' => 0,
                'can_edit' => 0,
            ],
            [
                'id' => 98,
                'numero' => '000050',
                'descrizione' => 'Ricavi vari',
                'idpianodeiconti2' => 20,
                'dir' => 'entrata',
                'can_delete' => 0,
                'can_edit' => 0,
            ],
            [
                'id' => 99,
                'numero' => '000051',
                'descrizione' => 'Rimborso spese marche da bollo',
                'idpianodeiconti2' => 20,
                'dir' => '',
                'can_delete' => 0,
                'can_edit' => 0,
            ],
            [
                'id' => 100,
                'numero' => '000060',
                'descrizione' => 'Ricavi abbuoni attivi',
                'idpianodeiconti2' => 20,
                'dir' => '',
                'can_delete' => 0,
                'can_edit' => 0,
            ],
            [
                'id' => 101,
                'numero' => '000070',
                'descrizione' => 'Ricavi sopravvenienze attive',
                'idpianodeiconti2' => 20,
                'dir' => '',
                'can_delete' => 0,
                'can_edit' => 0,
            ],
            [
                'id' => 102,
                'numero' => '000080',
                'descrizione' => 'Ricavi plusvalenze',
                'idpianodeiconti2' => 20,
                'dir' => '',
                'can_delete' => 0,
                'can_edit' => 0,
            ],
            [
                'id' => 103,
                'numero' => '000020',
                'descrizione' => 'Perdite e profitti',
                'idpianodeiconti2' => 21,
                'dir' => '',
                'can_delete' => 0,
                'can_edit' => 0,
            ],
            [
                'id' => 104,
                'numero' => '000010',
                'descrizione' => 'Apertura conti patrimoniali',
                'idpianodeiconti2' => 21,
                'dir' => '',
                'can_delete' => 0,
                'can_edit' => 0,
            ],
            [
                'id' => 105,
                'numero' => '000900',
                'descrizione' => 'Chiusura conti patrimoniali',
                'idpianodeiconti2' => 21,
                'dir' => '',
                'can_delete' => 0,
                'can_edit' => 0,
            ],
            [
                'id' => 106,
                'numero' => '000010',
                'descrizione' => 'Iva su vendite',
                'idpianodeiconti2' => 22,
                'dir' => '',
                'can_delete' => 0,
                'can_edit' => 0,
            ],
            [
                'id' => 107,
                'numero' => '000020',
                'descrizione' => 'Iva su acquisti',
                'idpianodeiconti2' => 22,
                'dir' => '',
                'can_delete' => 0,
                'can_edit' => 0,
            ],
            [
                'id' => 108,
                'numero' => '000030',
                'descrizione' => 'Iva indetraibile',
                'idpianodeiconti2' => 22,
                'dir' => '',
                'can_delete' => 0,
                'can_edit' => 0,
            ],
            [
                'id' => 109,
                'numero' => '000200',
                'descrizione' => 'Intra UE: riepilogativo fornitori',
                'idpianodeiconti2' => 22,
                'dir' => '',
                'can_delete' => 0,
                'can_edit' => 0,
            ],
            [
                'id' => 110,
                'numero' => '000210',
                'descrizione' => 'Intra UE: transitorio iva',
                'idpianodeiconti2' => 22,
                'dir' => '',
                'can_delete' => 0,
                'can_edit' => 0,
            ],
            [
                'id' => 111,
                'numero' => '000220',
                'descrizione' => 'Intra UE: transitorio per movimento iva',
                'idpianodeiconti2' => 22,
                'dir' => '',
                'can_delete' => 0,
                'can_edit' => 0,
            ],
        ]);
    }
}
