<?php

use Update\Seed;

class ZzModulesTableSeeder extends Seed
{
    /**
     * Auto generated seed file.
     */
    public function run()
    {
        $this->capsule->table('zz_modules')->truncate();

        $this->capsule->table('zz_modules')->insert([
            [
                'id' => 1,
                'name' => 'Dashboard',
                'title' => 'Dashboard',
                'directory' => 'dashboard',
                'options' => 'custom',
                'options2' => '',
                'icon' => 'fa fa-dashboard',
                'version' => '2.4',
                'compatibility' => '2.4',
                'order' => 0,
                'parent' => null,
                'default' => 1,
                'enabled' => 1,
            ],
            [
                'id' => 2,
                'name' => 'Anagrafiche',
                'title' => 'Anagrafiche',
                'directory' => 'anagrafiche',
            'options' => 'SELECT |select| FROM `an_anagrafiche` LEFT JOIN `an_relazioni` ON `an_anagrafiche`.`idrelazione` = `an_relazioni`.`id` LEFT JOIN `an_tipianagrafiche_anagrafiche` ON `an_tipianagrafiche_anagrafiche`.`idanagrafica`=`an_anagrafiche`.`idanagrafica` LEFT JOIN `an_tipianagrafiche` ON `an_tipianagrafiche`.`idtipoanagrafica`=`an_tipianagrafiche_anagrafiche`.`idtipoanagrafica` WHERE 1=1 AND `deleted_at` IS NULL GROUP BY `an_anagrafiche`.`idanagrafica` HAVING 2=2 ORDER BY TRIM(`ragione_sociale`)',
                'options2' => '',
                'icon' => 'fa fa-users',
                'version' => '2.4',
                'compatibility' => '2.4',
                'order' => 1,
                'parent' => null,
                'default' => 1,
                'enabled' => 1,
            ],
            [
                'id' => 3,
                'name' => 'Interventi',
                'title' => 'Attività',
                'directory' => 'interventi',
            'options' => 'SELECT |select| FROM (`in_interventi` INNER JOIN `an_anagrafiche` ON `in_interventi`.`idanagrafica` = `an_anagrafiche`.`idanagrafica`) LEFT OUTER JOIN `in_interventi_tecnici` ON `in_interventi_tecnici`.`idintervento` = `in_interventi`.`id` WHERE 1=1 GROUP BY `in_interventi`.`id` HAVING 2=2 AND ((`orario_inizio` >= \'|period_start|\' AND `orario_fine` <= \'|period_end|\') OR (`data_richiesta` >= \'|period_start|\' AND `data_richiesta` <= \'|period_end|\')) ORDER BY IFNULL(`orario_fine`, `data_richiesta`) DESC',
                'options2' => '',
                'icon' => 'fa fa-wrench',
                'version' => '2.4',
                'compatibility' => '2.4',
                'order' => 2,
                'parent' => null,
                'default' => 1,
                'enabled' => 1,
            ],
            [
                'id' => 6,
                'name' => 'Aggiornamenti',
                'title' => 'Aggiornamenti',
                'directory' => 'aggiornamenti',
                'options' => 'custom',
                'options2' => '',
                'icon' => 'fa fa-download',
                'version' => '2.4',
                'compatibility' => '2.4',
                'order' => 9,
                'parent' => 36,
                'default' => 1,
                'enabled' => 1,
            ],
            [
                'id' => 7,
                'name' => 'Backup',
                'title' => 'Backup',
                'directory' => 'backup',
                'options' => 'custom',
                'options2' => '',
                'icon' => 'fa fa-archive',
                'version' => '2.4',
                'compatibility' => '2.4',
                'order' => 8,
                'parent' => 36,
                'default' => 1,
                'enabled' => 1,
            ],
            [
                'id' => 8,
                'name' => 'Tipi di anagrafiche',
                'title' => 'Tipi di anagrafiche',
                'directory' => 'tipi_anagrafiche',
                'options' => 'SELECT |select| FROM `an_tipianagrafiche` WHERE 1=1 HAVING 2=2',
                'options2' => '',
                'icon' => 'fa fa-angle-right',
                'version' => '2.4',
                'compatibility' => '2.4',
                'order' => 0,
                'parent' => 2,
                'default' => 1,
                'enabled' => 0,
            ],
            [
                'id' => 9,
                'name' => 'Tipi di intervento',
                'title' => 'Tipi di attività',
                'directory' => 'tipi_intervento',
                'options' => 'SELECT |select| FROM `in_tipiintervento` WHERE 1=1 HAVING 2=2',
                'options2' => '',
                'icon' => 'fa fa-angle-right',
                'version' => '2.4',
                'compatibility' => '2.4',
                'order' => 0,
                'parent' => 3,
                'default' => 1,
                'enabled' => 1,
            ],
            [
                'id' => 10,
                'name' => 'Stati di intervento',
                'title' => 'Stati di attività',
                'directory' => 'stati_intervento',
                'options' => 'SELECT |select| FROM `in_statiintervento` WHERE 1=1 AND `deleted_at` IS NULL HAVING 2=2',
                'options2' => '',
                'icon' => 'fa fa-angle-right',
                'version' => '2.4',
                'compatibility' => '2.4',
                'order' => 1,
                'parent' => 3,
                'default' => 1,
                'enabled' => 1,
            ],
            [
                'id' => 12,
                'name' => 'Contabilità',
                'title' => 'Contabilità',
                'directory' => 'contabilita',
                'options' => 'menu',
                'options2' => '',
                'icon' => 'fa fa-eur',
                'version' => '2.4',
                'compatibility' => '2.4',
                'order' => 5,
                'parent' => null,
                'default' => 1,
                'enabled' => 1,
            ],
            [
                'id' => 13,
                'name' => 'Preventivi',
                'title' => 'Preventivi',
                'directory' => 'preventivi',
            'options' => 'SELECT |select| FROM `co_preventivi` WHERE 1=1 AND default_revision=1 HAVING 2=2 AND ((\'|period_start|\' >= `data_bozza` AND \'|period_start|\' <= `data_conclusione`) OR (\'|period_end|\' >= `data_bozza` AND \'|period_end|\' <= `data_conclusione`) OR (`data_bozza` >= \'|period_start|\' AND `data_bozza` <= \'|period_end|\') OR (`data_conclusione` >= \'|period_start|\' AND `data_conclusione` <= \'|period_end|\') OR (`data_bozza` >= \'|period_start|\' AND `data_conclusione` = \'0000-00-00\')) ORDER BY `id` DESC',
                'options2' => '',
                'icon' => 'fa fa-angle-right',
                'version' => '2.4',
                'compatibility' => '2.4',
                'order' => 0,
                'parent' => 33,
                'default' => 1,
                'enabled' => 1,
            ],
            [
                'id' => 14,
                'name' => 'Fatture di vendita',
                'title' => 'Fatture di vendita',
                'directory' => 'fatture',
            'options' => 'SELECT |select| FROM `co_documenti` INNER JOIN `co_tipidocumento` ON `co_documenti`.`idtipodocumento` = `co_tipidocumento`.`id` WHERE 1=1 AND `dir` = \'entrata\' |segment| AND `data` >= \'|period_start|\' AND `data` <= \'|period_end|\' HAVING 2=2 ORDER BY `data` DESC, CAST(numero_esterno AS UNSIGNED) DESC',
                'options2' => '',
                'icon' => 'fa fa-angle-right',
                'version' => '2.4',
                'compatibility' => '2.4',
                'order' => 3,
                'parent' => 33,
                'default' => 1,
                'enabled' => 1,
            ],
            [
                'id' => 15,
                'name' => 'Fatture di acquisto',
                'title' => 'Fatture di acquisto',
                'directory' => 'fatture',
            'options' => 'SELECT |select| FROM `co_documenti` INNER JOIN `co_tipidocumento` ON `co_documenti`.`idtipodocumento` = `co_tipidocumento`.`id` WHERE 1=1 AND `dir` = \'uscita\' |segment| AND `data` >= \'|period_start|\' AND `data` <= \'|period_end|\' HAVING 2=2 ORDER BY `data` DESC, CAST(IF(numero_esterno=\'\', numero, numero_esterno) AS UNSIGNED) DESC',
                'options2' => '',
                'icon' => 'fa fa-angle-right',
                'version' => '2.4',
                'compatibility' => '2.4',
                'order' => 4,
                'parent' => 34,
                'default' => 1,
                'enabled' => 1,
            ],
            [
                'id' => 16,
                'name' => 'Prima nota',
                'title' => 'Prima nota',
                'directory' => 'primanota',
                'options' => 'SELECT |select| FROM `co_movimenti` INNER JOIN `co_pianodeiconti3` ON `co_movimenti`.`idconto` = `co_pianodeiconti3`.`id` WHERE 1=1 GROUP BY `idmastrino`, `primanota`, `co_movimenti`.`data` HAVING 2=2 AND `primanota` = 1 AND `co_movimenti`.`data`>=\'|period_start|\' AND `co_movimenti`.`data`<=\'|period_end|\' ORDER BY `co_movimenti`.`data` DESC',
                'options2' => '',
                'icon' => 'fa fa-angle-right',
                'version' => '2.4',
                'compatibility' => '2.4',
                'order' => 5,
                'parent' => 12,
                'default' => 1,
                'enabled' => 1,
            ],
            [
                'id' => 17,
                'name' => 'Piano dei conti',
                'title' => 'Piano dei conti',
                'directory' => 'partitario',
                'options' => 'custom',
                'options2' => '',
                'icon' => 'fa fa-angle-right',
                'version' => '2.4',
                'compatibility' => '2.4',
                'order' => 6,
                'parent' => 12,
                'default' => 1,
                'enabled' => 1,
            ],
            [
                'id' => 18,
                'name' => 'Scadenzario',
                'title' => 'Scadenzario',
                'directory' => 'scadenzario',
            'options' => 'SELECT |select| FROM (`co_scadenziario` INNER JOIN (((`co_documenti` INNER JOIN `an_anagrafiche` ON `co_documenti`.`idanagrafica` = `an_anagrafiche`.`idanagrafica`) INNER JOIN `co_pagamenti` ON `co_documenti`.`idpagamento` = `co_pagamenti`.`id`) INNER JOIN `co_tipidocumento` ON `co_documenti`.`idtipodocumento` = `co_tipidocumento`.`id`) ON `co_scadenziario`.`iddocumento` = `co_documenti`.`id`) INNER JOIN `co_statidocumento` ON `co_documenti`.`idstatodocumento` = `co_statidocumento`.`id` WHERE 1=1 HAVING 2=2 AND (ABS(`pagato_reale`) < ABS(`da_pagare`) AND `co_statidocumento`.`descrizione` IN(\'Emessa\',\'Parzialmente pagato\')) ORDER BY `scadenza` ASC',
                'options2' => '',
                'icon' => 'fa fa-angle-right',
                'version' => '2.4',
                'compatibility' => '2.4',
                'order' => 7,
                'parent' => 12,
                'default' => 1,
                'enabled' => 1,
            ],
            [
                'id' => 20,
                'name' => 'Magazzino',
                'title' => 'Magazzino',
                'directory' => 'magazzino',
                'options' => 'menu',
                'options2' => '',
                'icon' => 'fa fa-truck',
                'version' => '2.4',
                'compatibility' => '2.4',
                'order' => 6,
                'parent' => null,
                'default' => 1,
                'enabled' => 1,
            ],
            [
                'id' => 21,
                'name' => 'Articoli',
                'title' => 'Articoli',
                'directory' => 'articoli',
                'options' => 'SELECT |select| FROM `mg_articoli` WHERE 1=1 HAVING 2=2 ORDER BY `descrizione`',
                'options2' => '',
                'icon' => 'fa fa-angle-right',
                'version' => '2.4',
                'compatibility' => '2.4',
                'order' => 0,
                'parent' => 20,
                'default' => 1,
                'enabled' => 1,
            ],
            [
                'id' => 22,
                'name' => 'Listini',
                'title' => 'Listini',
                'directory' => 'listini',
                'options' => 'SELECT |select| FROM `mg_listini` WHERE 1=1 HAVING 2=2 ORDER BY `nome`',
                'options2' => '',
                'icon' => 'fa fa-angle-right',
                'version' => '2.4',
                'compatibility' => '2.4',
                'order' => 1,
                'parent' => 20,
                'default' => 1,
                'enabled' => 1,
            ],
            [
                'id' => 23,
                'name' => 'Automezzi',
                'title' => 'Automezzi',
                'directory' => 'automezzi',
                'options' => 'SELECT |select| FROM `dt_automezzi` WHERE 1=1 HAVING 2=2 ORDER BY `targa`',
                'options2' => '',
                'icon' => 'fa fa-angle-right',
                'version' => '2.4',
                'compatibility' => '2.4',
                'order' => 2,
                'parent' => 20,
                'default' => 1,
                'enabled' => 1,
            ],
            [
                'id' => 24,
                'name' => 'Ordini cliente',
                'title' => 'Ordini cliente',
                'directory' => 'ordini',
            'options' => 'SELECT |select| FROM `or_ordini` INNER JOIN `or_tipiordine` ON `or_ordini`.`idtipoordine` = `or_tipiordine`.`id` WHERE 1=1 AND `dir` = \'entrata\' AND `data` >= \'|period_start|\' AND `data` <= \'|period_end|\' HAVING 2=2 ORDER BY `data` DESC, CAST(`numero_esterno` AS UNSIGNED) DESC',
                'options2' => '',
                'icon' => 'fa fa-angle-right',
                'version' => '2.4',
                'compatibility' => '2.4',
                'order' => 1,
                'parent' => 33,
                'default' => 1,
                'enabled' => 1,
            ],
            [
                'id' => 25,
                'name' => 'Ordini fornitore',
                'title' => 'Ordini fornitore',
                'directory' => 'ordini',
            'options' => 'SELECT |select| FROM `or_ordini` INNER JOIN `or_tipiordine` ON `or_ordini`.`idtipoordine` = `or_tipiordine`.`id` WHERE 1=1 AND `dir` = \'uscita\' AND `data` >= \'|period_start|\' AND `data` <= \'|period_end|\' HAVING 2=2 ORDER BY `data` DESC, CAST(`numero_esterno` AS UNSIGNED) DESC',
                'options2' => '',
                'icon' => 'fa fa-angle-right',
                'version' => '2.4',
                'compatibility' => '2.4',
                'order' => 2,
                'parent' => 34,
                'default' => 1,
                'enabled' => 1,
            ],
            [
                'id' => 26,
                'name' => 'Ddt di vendita',
                'title' => 'Ddt in uscita',
                'directory' => 'ddt',
            'options' => 'SELECT |select| FROM `dt_ddt` INNER JOIN `dt_tipiddt` ON `dt_ddt`.`idtipoddt` = `dt_tipiddt`.`id` WHERE 1=1 AND `dir` = \'entrata\' AND `data` >= \'|period_start|\' AND `data` <= \'|period_end|\' HAVING 2=2 ORDER BY `data` DESC, CAST(`numero_esterno` AS UNSIGNED) DESC',
                'options2' => '',
                'icon' => 'fa fa-angle-right',
                'version' => '2.4',
                'compatibility' => '2.4',
                'order' => 3,
                'parent' => 20,
                'default' => 1,
                'enabled' => 1,
            ],
            [
                'id' => 27,
                'name' => 'Ddt di acquisto',
                'title' => 'Ddt in ingresso',
                'directory' => 'ddt',
            'options' => 'SELECT |select| FROM `dt_ddt` INNER JOIN `dt_tipiddt` ON `dt_ddt`.`idtipoddt` = `dt_tipiddt`.`id` WHERE 1=1 AND `dir` = \'uscita\' AND `data` >= \'|period_start|\' AND `data` <= \'|period_end|\' HAVING 2=2 ORDER BY `data` DESC, CAST(`numero_esterno` AS UNSIGNED) DESC',
                'options2' => '',
                'icon' => 'fa fa-angle-right',
                'version' => '2.4',
                'compatibility' => '2.4',
                'order' => 4,
                'parent' => 20,
                'default' => 1,
                'enabled' => 1,
            ],
            [
                'id' => 28,
                'name' => 'Zone',
                'title' => 'Zone',
                'directory' => 'zone',
                'options' => 'SELECT |select| FROM `an_zone` WHERE 1=1 HAVING 2=2 ORDER BY `id`',
                'options2' => '',
                'icon' => 'fa fa-angle-right',
                'version' => '2.4',
                'compatibility' => '2.4',
                'order' => 2,
                'parent' => 2,
                'default' => 1,
                'enabled' => 1,
            ],
            [
                'id' => 29,
                'name' => 'Tecnici e tariffe',
                'title' => 'Tecnici e tariffe',
                'directory' => 'tecnici_tariffe',
                'options' => 'custom',
                'options2' => '',
                'icon' => 'fa fa-angle-right',
                'version' => '2.4',
                'compatibility' => '2.4',
                'order' => 3,
                'parent' => 3,
                'default' => 1,
                'enabled' => 1,
            ],
            [
                'id' => 30,
                'name' => 'MyImpianti',
                'title' => 'MyImpianti',
                'directory' => 'my_impianti',
                'options' => 'SELECT |select| FROM `my_impianti` WHERE 1=1 HAVING 2=2 ORDER BY `matricola`',
                'options2' => '',
                'icon' => 'fa fa-puzzle-piece',
                'version' => '2.4',
                'compatibility' => '2.4',
                'order' => 7,
                'parent' => null,
                'default' => 1,
                'enabled' => 1,
            ],
            [
                'id' => 31,
                'name' => 'Contratti',
                'title' => 'Contratti',
                'directory' => 'contratti',
            'options' => 'SELECT |select| FROM `co_contratti` WHERE 1=1 HAVING 2=2 AND ((\'|period_start|\' >= `data_bozza` AND \'|period_start|\' <= `data_conclusione`) OR (\'|period_end|\' >= `data_bozza` AND \'|period_end|\' <= `data_conclusione`) OR (`data_bozza` >= \'|period_start|\' AND `data_bozza` <= \'|period_end|\') OR (`data_conclusione` >= \'|period_start|\' AND `data_conclusione` <= \'|period_end|\') OR (`data_bozza` >= \'|period_start|\' AND `data_conclusione` = \'0000-00-00\')) ORDER BY `id` DESC',
                'options2' => '',
                'icon' => 'fa fa-angle-right',
                'version' => '2.4',
                'compatibility' => '2.4',
                'order' => 0,
                'parent' => 33,
                'default' => 1,
                'enabled' => 1,
            ],
            [
                'id' => 32,
                'name' => 'Voci di servizio',
                'title' => 'Voci di servizio',
                'directory' => 'voci_servizio',
                'options' => 'SELECT |select| FROM `in_vociservizio` WHERE 1=1 HAVING 2=2 ORDER BY `categoria`, `descrizione`',
                'options2' => '',
                'icon' => 'fa fa-angle-right',
                'version' => '2.4',
                'compatibility' => '2.4',
                'order' => 3,
                'parent' => 3,
                'default' => 1,
                'enabled' => 1,
            ],
            [
                'id' => 33,
                'name' => 'Vendite',
                'title' => 'Vendite',
                'directory' => '',
                'options' => 'menu',
                'options2' => '',
                'icon' => 'fa fa-line-chart',
                'version' => '2.4',
                'compatibility' => '2.4',
                'order' => 3,
                'parent' => null,
                'default' => 1,
                'enabled' => 1,
            ],
            [
                'id' => 34,
                'name' => 'Acquisti',
                'title' => 'Acquisti',
                'directory' => '',
                'options' => 'menu',
                'options2' => '',
                'icon' => 'fa fa-shopping-cart',
                'version' => '2.4',
                'compatibility' => '2.4',
                'order' => 4,
                'parent' => null,
                'default' => 1,
                'enabled' => 1,
            ],
            [
                'id' => 35,
                'name' => 'Gestione componenti',
                'title' => 'Gestione componenti',
                'directory' => 'gestione_componenti',
                'options' => 'custom',
                'options2' => '',
                'icon' => 'fa fa-angle-right',
                'version' => '2.4',
                'compatibility' => '2.4',
                'order' => 0,
                'parent' => 30,
                'default' => 1,
                'enabled' => 1,
            ],
            [
                'id' => 36,
                'name' => 'Strumenti',
                'title' => 'Strumenti',
                'directory' => '',
                'options' => 'menu',
                'options2' => '',
                'icon' => 'fa fa-cog',
                'version' => '2.4',
                'compatibility' => '2.4',
                'order' => 11,
                'parent' => null,
                'default' => 1,
                'enabled' => 1,
            ],
            [
                'id' => 37,
                'name' => 'Viste',
                'title' => 'Viste',
                'directory' => 'viste',
                'options' => 'SELECT |select| FROM `zz_modules` WHERE 1=1 HAVING 2=2 ORDER BY `name`, `title` ASC',
                'options2' => '',
                'icon' => 'fa fa-eye',
                'version' => '2.4',
                'compatibility' => '2.4',
                'order' => 1,
                'parent' => 36,
                'default' => 1,
                'enabled' => 0,
            ],
            [
                'id' => 38,
                'name' => 'Utenti e permessi',
                'title' => 'Utenti e permessi',
                'directory' => 'utenti',
                'options' => 'SELECT |select| FROM `zz_groups` WHERE 1=1 HAVING 2=2 ORDER BY `id`, `nome` ASC',
                'options2' => '',
                'icon' => 'fa fa-lock',
                'version' => '2.4',
                'compatibility' => '2.4',
                'order' => 1,
                'parent' => 36,
                'default' => 1,
                'enabled' => 1,
            ],
            [
                'id' => 39,
                'name' => 'Impostazioni',
                'title' => 'Impostazioni',
                'directory' => 'impostazioni',
                'options' => 'SELECT |select| FROM `zz_settings` WHERE 1=1 AND `editable` = 1 GROUP BY `sezione` HAVING 2=2 ORDER BY `sezione`',
                'options2' => '',
                'icon' => 'fa fa-th-list',
                'version' => '2.4',
                'compatibility' => '2.4',
                'order' => 1,
                'parent' => 36,
                'default' => 1,
                'enabled' => 1,
            ],
            [
                'id' => 40,
                'name' => 'Tabelle',
                'title' => 'Tabelle',
                'directory' => '',
                'options' => '',
                'options2' => '',
                'icon' => 'fa fa-table',
                'version' => '2.4',
                'compatibility' => '2.4',
                'order' => 1,
                'parent' => 36,
                'default' => 1,
                'enabled' => 1,
            ],
            [
                'id' => 41,
                'name' => 'IVA',
                'title' => 'IVA',
                'directory' => 'iva',
                'options' => 'SELECT |select| FROM `co_iva` WHERE 1=1 AND deleted_at IS NULL HAVING 2=2',
                'options2' => '',
                'icon' => 'fa fa-percent',
                'version' => '2.4',
                'compatibility' => '2.4',
                'order' => 1,
                'parent' => 40,
                'default' => 1,
                'enabled' => 1,
            ],
            [
                'id' => 42,
                'name' => 'Causali',
                'title' => 'Causali',
                'directory' => 'causali',
                'options' => 'SELECT |select| FROM `dt_causalet` WHERE 1=1 HAVING 2=2',
                'options2' => '',
                'icon' => 'fa fa-commenting-o',
                'version' => '2.4',
                'compatibility' => '2.4',
                'order' => 1,
                'parent' => 40,
                'default' => 1,
                'enabled' => 1,
            ],
            [
                'id' => 43,
                'name' => 'Aspetto beni',
                'title' => 'Aspetto beni',
                'directory' => 'beni',
                'options' => 'SELECT |select| FROM `dt_aspettobeni` WHERE 1=1 HAVING 2=2',
                'options2' => '',
                'icon' => 'fa fa-angle-right',
                'version' => '2.4',
                'compatibility' => '2.4',
                'order' => 1,
                'parent' => 40,
                'default' => 1,
                'enabled' => 1,
            ],
            [
                'id' => 44,
                'name' => 'Unità di misura',
                'title' => 'Unità di misura',
                'directory' => 'misure',
                'options' => 'SELECT |select| FROM `mg_unitamisura` WHERE 1=1 HAVING 2=2',
                'options2' => '',
                'icon' => 'fa fa-angle-right',
                'version' => '2.4',
                'compatibility' => '2.4',
                'order' => 1,
                'parent' => 40,
                'default' => 1,
                'enabled' => 1,
            ],
            [
                'id' => 45,
                'name' => 'Porto',
                'title' => 'Porto',
                'directory' => 'porti',
                'options' => 'SELECT |select| FROM `dt_porto` WHERE 1=1 HAVING 2=2',
                'options2' => '',
                'icon' => 'fa fa-angle-right',
                'version' => '2.4',
                'compatibility' => '2.4',
                'order' => 1,
                'parent' => 40,
                'default' => 1,
                'enabled' => 1,
            ],
            [
                'id' => 46,
                'name' => 'Pagamenti',
                'title' => 'Pagamenti',
                'directory' => 'pagamenti',
                'options' => 'SELECT |select| FROM `co_pagamenti` WHERE 1=1 GROUP BY `descrizione` HAVING 2=2',
                'options2' => '',
                'icon' => 'fa fa-usd',
                'version' => '2.4',
                'compatibility' => '2.4',
                'order' => 1,
                'parent' => 40,
                'default' => 1,
                'enabled' => 1,
            ],
            [
                'id' => 47,
                'name' => 'Categorie articoli',
                'title' => 'Categorie articoli',
                'directory' => 'categorie_articoli',
                'options' => 'SELECT |select| FROM `mg_categorie` WHERE 1=1 AND `parent` IS NULL HAVING 2=2',
                'options2' => '',
                'icon' => 'fa fa-briefcase',
                'version' => '2.4',
                'compatibility' => '2.4',
                'order' => 1,
                'parent' => 40,
                'default' => 1,
                'enabled' => 1,
            ],
            [
                'id' => 48,
                'name' => 'Ritenute acconto',
                'title' => 'Ritenute acconto',
                'directory' => 'ritenute',
                'options' => 'SELECT |select| FROM `co_ritenutaacconto` WHERE 1=1 HAVING 2=2',
                'options2' => '',
                'icon' => 'fa fa-percent',
                'version' => '2.4',
                'compatibility' => '2.4',
                'order' => 1,
                'parent' => 40,
                'default' => 1,
                'enabled' => 1,
            ],
            [
                'id' => 49,
                'name' => 'Movimenti',
                'title' => 'Movimenti',
                'directory' => '',
                'options' => 'SELECT |select| FROM `mg_movimenti` JOIN `mg_articoli` ON `mg_articoli`.id = `mg_movimenti`.`idarticolo` WHERE 1=1 HAVING 2=2 ORDER BY `Data` DESC',
                'options2' => '',
                'icon' => 'fa fa-angle-right',
                'version' => '2.4',
                'compatibility' => '2.4',
                'order' => 1,
                'parent' => 20,
                'default' => 1,
                'enabled' => 1,
            ],
            [
                'id' => 50,
                'name' => 'Stampe contabili',
                'title' => 'Stampe contabili',
                'directory' => 'stampe_contabili',
                'options' => 'custom',
                'options2' => '',
                'icon' => 'fa fa-angle-right',
                'version' => '2.4',
                'compatibility' => '2.4',
                'order' => 1,
                'parent' => 12,
                'default' => 1,
                'enabled' => 1,
            ],
            [
                'id' => 51,
                'name' => 'Statistiche',
                'title' => 'Statistiche',
                'directory' => 'statistiche',
                'options' => 'custom',
                'options2' => '',
                'icon' => 'fa fa-bar-chart',
                'version' => '2.4',
                'compatibility' => '2.4',
                'order' => 10,
                'parent' => null,
                'default' => 1,
                'enabled' => 1,
            ],
            [
                'id' => 52,
                'name' => 'Account email',
                'title' => 'Account email',
                'directory' => 'smtp',
                'options' => 'SELECT |select| FROM zz_smtps WHERE 1=1 AND deleted_at IS NULL HAVING 2=2 ORDER BY `name`',
                'options2' => '',
                'icon' => 'fa fa-user-o',
                'version' => '2.4',
                'compatibility' => '2.4',
                'order' => 10,
                'parent' => 54,
                'default' => 1,
                'enabled' => 1,
            ],
            [
                'id' => 53,
                'name' => 'Template email',
                'title' => 'Template email',
                'directory' => 'emails',
                'options' => 'SELECT |select| FROM zz_emails WHERE 1=1 AND `deleted_at` IS NULL HAVING 2=2 ORDER BY `name`',
                'options2' => '',
                'icon' => 'fa fa-pencil-square-o',
                'version' => '2.4',
                'compatibility' => '2.4',
                'order' => 10,
                'parent' => 54,
                'default' => 1,
                'enabled' => 1,
            ],
            [
                'id' => 54,
                'name' => 'Gestione email',
                'title' => 'Gestione email',
                'directory' => '',
                'options' => '',
                'options2' => '',
                'icon' => 'fa fa-envelope',
                'version' => '2.4',
                'compatibility' => '2.4',
                'order' => 1,
                'parent' => null,
                'default' => 1,
                'enabled' => 1,
            ],
            [
                'id' => 55,
                'name' => 'Segmenti',
                'title' => 'Segmenti',
                'directory' => 'segmenti',
                'options' => 'SELECT |select| FROM `zz_segments` WHERE 1=1 HAVING 2=2 ORDER BY name, id_module',
                'options2' => '',
                'icon' => 'fa fa-database',
                'version' => '2.4',
                'compatibility' => '2.4',
                'order' => 1,
                'parent' => 36,
                'default' => 1,
                'enabled' => 1,
            ],
            [
                'id' => 56,
                'name' => 'Import',
                'title' => 'Import',
                'directory' => 'import',
                'options' => 'custom',
                'options2' => '',
                'icon' => 'fa fa-file-o',
                'version' => '2.4',
                'compatibility' => '2.4',
                'order' => 1,
                'parent' => 36,
                'default' => 1,
                'enabled' => 1,
            ],
            [
                'id' => 57,
                'name' => 'Banche',
                'title' => 'Banche',
                'directory' => 'banche',
                'options' => 'SELECT |select| FROM `co_banche` WHERE 1=1 AND `deleted_at` IS NULL HAVING 2=2',
                'options2' => '',
                'icon' => 'fa fa-university',
                'version' => '2.4',
                'compatibility' => '2.4',
                'order' => 1,
                'parent' => 40,
                'default' => 1,
                'enabled' => 1,
            ],
            [
                'id' => 58,
                'name' => 'Modelli prima nota',
                'title' => 'Modelli prima nota',
                'directory' => 'modelli_primanota',
                'options' => 'SELECT |select| FROM `co_movimenti_modelli` WHERE 1=1 GROUP BY `idmastrino` HAVING 2=2',
                'options2' => '',
                'icon' => 'fa fa-angle-right',
                'version' => '2.4',
                'compatibility' => '2.4',
                'order' => 1,
                'parent' => 40,
                'default' => 1,
                'enabled' => 1,
            ],
            [
                'id' => 59,
                'name' => 'Campi personalizzati',
                'title' => 'Campi personalizzati',
                'directory' => 'custom_fields',
                'options' => 'SELECT |select| FROM `zz_fields` WHERE 1=1 HAVING 2=2',
                'options2' => '',
                'icon' => 'fa fa-list',
                'version' => '2.4',
                'compatibility' => '2.4',
                'order' => 1,
                'parent' => 36,
                'default' => 1,
                'enabled' => 0,
            ],
            [
                'id' => 60,
                'name' => 'Gestione documentale',
                'title' => 'Gestione documentale',
                'directory' => 'gestione_documentale',
            'options' => '{	"main_query": [	{	"type": "table", "fields": "Categoria, Nome, Data", "query": "SELECT id,(SELECT descrizione FROM zz_documenti_categorie WHERE zz_documenti_categorie.id = idcategoria) AS Categoria, zz_documenti.nome AS Nome, DATE_FORMAT( zz_documenti.`data`, \'%d/%m/%Y\' ) AS `Data` FROM zz_documenti  WHERE  `data` >= \'|period_start|\' AND `data` <= \'|period_end|\' HAVING 1=1"}	]}',
                'options2' => '',
                'icon' => 'fa fa-file-text-o',
                'version' => '2.4',
                'compatibility' => '2.4',
                'order' => 1,
                'parent' => null,
                'default' => 1,
                'enabled' => 1,
            ],
            [
                'id' => 61,
                'name' => 'Categorie documenti',
                'title' => 'Categorie documenti',
                'directory' => 'categorie_documenti',
                'options' => '{	"main_query": [	{	"type": "table", "fields": "Descrizione", "query": "SELECT zz_documenti_categorie.`descrizione`as Descrizione, zz_documenti_categorie.`id`as id FROM zz_documenti_categorie WHERE deleted_at IS NULL HAVING 1=1"}	]}',
                'options2' => '',
                'icon' => 'fa fa-file-text-o',
                'version' => '2.4',
                'compatibility' => '2.4',
                'order' => 1,
                'parent' => 60,
                'default' => 1,
                'enabled' => 1,
            ],
            [
                'id' => 62,
                'name' => 'Tipi di spedizione',
                'title' => 'Tipi di spedizione',
                'directory' => 'spedizioni',
                'options' => 'SELECT |select| FROM `dt_spedizione` WHERE 1=1 HAVING 2=2',
                'options2' => '',
                'icon' => 'fa fa-angle-right',
                'version' => '2.4',
                'compatibility' => '2.4',
                'order' => 1,
                'parent' => 40,
                'default' => 1,
                'enabled' => 1,
            ],
            [
                'id' => 63,
                'name' => 'Categorie impianti',
                'title' => 'Categorie impianti',
                'directory' => 'categorie_impianti',
                'options' => 'SELECT |select| FROM `my_impianti_categorie` WHERE 1=1 HAVING 2=2',
                'options2' => '',
                'icon' => 'fa fa-angle-right',
                'version' => '2.4',
                'compatibility' => '2.4',
                'order' => 1,
                'parent' => 30,
                'default' => 1,
                'enabled' => 1,
            ],
        ]);
    }
}
