<?php

use Update\Seed;

class ZzPluginsTableSeeder extends Seed
{
    /**
     * Auto generated seed file.
     */
    public function run()
    {
        $this->capsule->table('zz_plugins')->truncate();

        $this->capsule->table('zz_plugins')->insert([
            [
                'id' => 1,
                'name' => 'Impianti del cliente',
                'title' => 'Impianti del cliente',
                'idmodule_from' => 30,
                'idmodule_to' => 2,
                'position' => 'tab',
                'script' => '',
                'enabled' => 1,
                'default' => 0,
                'order' => 0,
                'compatibility' => '2.*',
                'version' => '2.3',
                'options2' => null,
            'options' => ' { "main_query": [ { "type": "table", "fields": "Matricola, Nome, Data, Descrizione", "query": "SELECT id, (SELECT `id` FROM `zz_modules` WHERE `name` = \'MyImpianti\') AS _link_module_, id AS _link_record_, matricola AS Matricola, nome AS Nome, DATE_FORMAT(data, \'%d/%m/%Y\') AS Data, descrizione AS Descrizione FROM my_impianti WHERE idanagrafica=|id_parent| HAVING 2=2 ORDER BY id DESC"} ]}',
                'directory' => '',
                'help' => '',
            ],
            [
                'id' => 2,
                'name' => 'Impianti',
                'title' => 'Impianti',
                'idmodule_from' => 30,
                'idmodule_to' => 3,
                'position' => 'tab',
                'script' => 'my_impianti.interventi.php',
                'enabled' => 1,
                'default' => 0,
                'order' => 0,
                'compatibility' => '',
                'version' => '',
                'options2' => null,
                'options' => null,
                'directory' => '',
                'help' => '',
            ],
            [
                'id' => 3,
                'name' => 'Referenti',
                'title' => 'Referenti',
                'idmodule_from' => 2,
                'idmodule_to' => 2,
                'position' => 'tab',
                'script' => '',
                'enabled' => 1,
                'default' => 0,
                'order' => 0,
                'compatibility' => '2.*',
                'version' => '2.3',
                'options2' => null,
            'options' => '	{ "main_query": [	{	"type": "table", "fields": "Nominativo, Mansione, Telefono, Indirizzo email, Sede",	"query": "SELECT an_referenti.id, an_referenti.nome AS Nominativo, mansione AS Mansione, an_referenti.telefono AS Telefono, an_referenti.email AS \'Indirizzo email\', IF(idsede = 0, \'Sede legale\', an_sedi.nomesede) AS Sede FROM an_referenti LEFT OUTER JOIN an_sedi ON idsede = an_sedi.id WHERE 1=1 AND an_referenti.idanagrafica=|id_parent| HAVING 2=2 ORDER BY an_referenti.id DESC"}	]}',
                'directory' => 'referenti',
                'help' => '',
            ],
            [
                'id' => 4,
                'name' => 'Sedi',
                'title' => 'Sedi',
                'idmodule_from' => 2,
                'idmodule_to' => 2,
                'position' => 'tab',
                'script' => '',
                'enabled' => 1,
                'default' => 0,
                'order' => 0,
                'compatibility' => '2.*',
                'version' => '2.3',
                'options2' => null,
                'options' => '	{ "main_query": [	{	"type": "table", "fields": "Nome, Indirizzo, Città, CAP, Provincia, Referente", "query": "SELECT an_sedi.id, an_sedi.nomesede AS Nome, an_sedi.indirizzo AS Indirizzo, an_sedi.citta AS Città, an_sedi.cap AS CAP, an_sedi.provincia AS Provincia, an_referenti.nome AS Referente FROM an_sedi LEFT OUTER JOIN an_referenti ON idsede = an_sedi.id WHERE 1=1 AND an_sedi.idanagrafica=|id_parent| HAVING 2=2 ORDER BY an_sedi.id DESC"}	]}',
                'directory' => 'sedi',
                'help' => '',
            ],
            [
                'id' => 7,
                'name' => 'Statistiche',
                'title' => 'Statistiche',
                'idmodule_from' => 2,
                'idmodule_to' => 2,
                'position' => 'tab',
                'script' => 'statistiche.php',
                'enabled' => 1,
                'default' => 0,
                'order' => 0,
                'compatibility' => '',
                'version' => '',
                'options2' => null,
                'options' => null,
                'directory' => '',
                'help' => '',
            ],
            [
                'id' => 8,
                'name' => 'Interventi svolti',
                'title' => 'Interventi svolti',
                'idmodule_from' => 3,
                'idmodule_to' => 30,
                'position' => 'tab',
                'script' => 'my_impianti.interventi.php',
                'enabled' => 1,
                'default' => 0,
                'order' => 0,
                'compatibility' => '',
                'version' => '',
                'options2' => null,
                'options' => null,
                'directory' => '',
                'help' => '',
            ],
            [
                'id' => 9,
                'name' => 'Componenti',
                'title' => 'Componenti',
                'idmodule_from' => 30,
                'idmodule_to' => 30,
                'position' => 'tab',
                'script' => 'my_impianti.componenti.php',
                'enabled' => 1,
                'default' => 0,
                'order' => 0,
                'compatibility' => '',
                'version' => '',
                'options2' => null,
                'options' => null,
                'directory' => '',
                'help' => '',
            ],
            [
                'id' => 10,
                'name' => 'Movimenti',
                'title' => 'Movimenti',
                'idmodule_from' => 21,
                'idmodule_to' => 21,
                'position' => 'tab',
                'script' => 'articoli.movimenti.php',
                'enabled' => 1,
                'default' => 0,
                'order' => 0,
                'compatibility' => '',
                'version' => '',
                'options2' => null,
                'options' => null,
                'directory' => '',
                'help' => '',
            ],
            [
                'id' => 11,
                'name' => 'Serial',
                'title' => 'Serial',
                'idmodule_from' => 21,
                'idmodule_to' => 21,
                'position' => 'tab',
                'script' => 'articoli.lotti.php',
                'enabled' => 1,
                'default' => 0,
                'order' => 0,
                'compatibility' => '',
                'version' => '',
                'options2' => null,
                'options' => null,
                'directory' => '',
                'help' => '',
            ],
            [
                'id' => 12,
                'name' => 'Consuntivo',
                'title' => 'Consuntivo',
                'idmodule_from' => 13,
                'idmodule_to' => 13,
                'position' => 'tab',
                'script' => 'preventivi.consuntivo.php',
                'enabled' => 1,
                'default' => 0,
                'order' => 0,
                'compatibility' => '',
                'version' => '',
                'options2' => null,
                'options' => null,
                'directory' => '',
                'help' => '',
            ],
            [
                'id' => 13,
                'name' => 'Consuntivo',
                'title' => 'Consuntivo',
                'idmodule_from' => 31,
                'idmodule_to' => 31,
                'position' => 'tab',
                'script' => 'contratti.consuntivo.php',
                'enabled' => 1,
                'default' => 0,
                'order' => 0,
                'compatibility' => '',
                'version' => '',
                'options2' => null,
                'options' => null,
                'directory' => '',
                'help' => '',
            ],
            [
                'id' => 14,
                'name' => 'Pianificazione interventi',
                'title' => 'Pianificazione attività',
                'idmodule_from' => 31,
                'idmodule_to' => 31,
                'position' => 'tab',
                'script' => '',
                'enabled' => 1,
                'default' => 0,
                'order' => 0,
                'compatibility' => '',
                'version' => '',
                'options2' => null,
                'options' => 'custom',
                'directory' => 'pianificazione_interventi',
                'help' => '',
            ],
            [
                'id' => 15,
                'name' => 'Pianificazione ordini di servizio',
                'title' => 'Pianificazione ordini di servizio',
                'idmodule_from' => 31,
                'idmodule_to' => 31,
                'position' => 'tab',
                'script' => 'contratti.ordiniservizio.php',
                'enabled' => 0,
                'default' => 0,
                'order' => 0,
                'compatibility' => '',
                'version' => '',
                'options2' => null,
                'options' => null,
                'directory' => '',
                'help' => '',
            ],
            [
                'id' => 16,
                'name' => 'Pianificazione fatturazione',
                'title' => 'Pianificazione fatturazione',
                'idmodule_from' => 31,
                'idmodule_to' => 31,
                'position' => 'tab',
                'script' => 'contratti.fatturaordiniservizio.php',
                'enabled' => 1,
                'default' => 0,
                'order' => 0,
                'compatibility' => '',
                'version' => '',
                'options2' => null,
                'options' => null,
                'directory' => '',
                'help' => '',
            ],
            [
                'id' => 17,
                'name' => 'Ddt del cliente',
                'title' => 'Ddt del cliente',
                'idmodule_from' => 26,
                'idmodule_to' => 2,
                'position' => 'tab',
                'script' => '',
                'enabled' => 1,
                'default' => 0,
                'order' => 0,
                'compatibility' => '2.*',
                'version' => '2.3',
                'options2' => null,
            'options' => ' { "main_query": [ { "type": "table", "fields": "Numero, Data, Descrizione, Qtà", "query": "SELECT dt_ddt.id, (SELECT `id` FROM `zz_modules` WHERE `name` = \'Ddt di vendita\') AS _link_module_, dt_ddt.id AS _link_record_, IF(dt_ddt.numero_esterno = \'\', dt_ddt.numero, dt_ddt.numero_esterno) AS Numero, DATE_FORMAT(dt_ddt.data, \'%d/%m/%Y\') AS Data, dt_righe_ddt.descrizione AS `Descrizione`, REPLACE(REPLACE(REPLACE(FORMAT(dt_righe_ddt.qta, 2), \',\', \'#\'), \'.\', \',\'), \'#\', \'.\') AS `Qtà` FROM dt_ddt LEFT JOIN dt_righe_ddt ON dt_ddt.id=dt_righe_ddt.idddt WHERE dt_ddt.idanagrafica=|id_parent| GROUP BY dt_ddt.id HAVING 2=2 ORDER BY dt_ddt.id DESC"} ]}',
                'directory' => '',
                'help' => 'Righe ddt del cliente. I ddt senza righe non saranno visualizzati.',
            ],
            [
                'id' => 18,
                'name' => 'Fatturazione Elettronica',
                'title' => 'Fatturazione Elettronica',
                'idmodule_from' => 14,
                'idmodule_to' => 14,
                'position' => 'tab',
                'script' => '',
                'enabled' => 1,
                'default' => 0,
                'order' => 0,
                'compatibility' => '',
                'version' => '',
                'options2' => null,
                'options' => 'custom',
                'directory' => 'exportPA',
                'help' => '',
            ],
            [
                'id' => 19,
                'name' => 'Fatturazione Elettronica',
                'title' => 'Fatturazione Elettronica',
                'idmodule_from' => 14,
                'idmodule_to' => 15,
                'position' => 'tab_main',
                'script' => '',
                'enabled' => 1,
                'default' => 0,
                'order' => 0,
                'compatibility' => '',
                'version' => '',
                'options2' => null,
                'options' => 'custom',
                'directory' => 'importPA',
                'help' => '',
            ],
            [
                'id' => 20,
                'name' => 'Revisioni',
                'title' => 'Revisioni',
                'idmodule_from' => 13,
                'idmodule_to' => 13,
                'position' => 'tab',
                'script' => '',
                'enabled' => 1,
                'default' => 0,
                'order' => 0,
                'compatibility' => '',
                'version' => '',
                'options2' => null,
                'options' => 'custom',
                'directory' => 'revisioni',
                'help' => '',
            ],
        ]);
    }
}
