<?php

use Update\Seed;

class ZzPrintsTableSeeder extends Seed
{
    /**
     * Auto generated seed file.
     */
    public function run()
    {
        $this->capsule->table('zz_prints')->truncate();

        $this->capsule->table('zz_prints')->insert([
            [
                'id' => 1,
                'id_module' => 14,
                'is_record' => 1,
                'name' => 'Fattura di vendita',
                'title' => 'Fattura di vendita',
                'directory' => 'fatture',
                'previous' => 'iddocumento',
                'options' => '',
                'icon' => 'fa fa-print',
                'version' => '',
                'compatibility' => '',
                'order' => 0,
                'predefined' => 1,
                'default' => 1,
                'enabled' => 1,
            ],
            [
                'id' => 2,
                'id_module' => 3,
                'is_record' => 0,
                'name' => 'Riepilogo interventi',
                'title' => 'Riepilogo interventi',
                'directory' => 'riepilogo_interventi',
                'previous' => '',
                'options' => '',
                'icon' => 'fa fa-print',
                'version' => '',
                'compatibility' => '',
                'order' => 0,
                'predefined' => 0,
                'default' => 1,
                'enabled' => 1,
            ],
            [
                'id' => 3,
                'id_module' => 21,
                'is_record' => 1,
                'name' => 'Inventario magazzino',
                'title' => 'Inventario magazzino',
                'directory' => 'magazzino_inventario',
                'previous' => '',
                'options' => '',
                'icon' => 'fa fa-print',
                'version' => '',
                'compatibility' => '',
                'order' => 0,
                'predefined' => 0,
                'default' => 1,
                'enabled' => 1,
            ],
            [
                'id' => 4,
                'id_module' => 17,
                'is_record' => 1,
                'name' => 'Mastrino',
                'title' => 'Mastrino',
                'directory' => 'partitario_mastrino',
                'previous' => 'idconto',
                'options' => '',
                'icon' => 'fa fa-print',
                'version' => '',
                'compatibility' => '',
                'order' => 0,
                'predefined' => 0,
                'default' => 1,
                'enabled' => 1,
            ],
            [
                'id' => 5,
                'id_module' => 18,
                'is_record' => 1,
                'name' => 'Scadenzario',
                'title' => 'Scadenzario',
                'directory' => 'scadenzario',
                'previous' => '',
                'options' => '',
                'icon' => 'fa fa-print',
                'version' => '',
                'compatibility' => '',
                'order' => 0,
                'predefined' => 0,
                'default' => 1,
                'enabled' => 1,
            ],
            [
                'id' => 6,
                'id_module' => 50,
                'is_record' => 1,
                'name' => 'Registro IVA',
                'title' => 'Registro IVA',
                'directory' => 'registro_iva',
                'previous' => '',
                'options' => '',
                'icon' => 'fa fa-print',
                'version' => '',
                'compatibility' => '',
                'order' => 0,
                'predefined' => 0,
                'default' => 1,
                'enabled' => 1,
            ],
            [
                'id' => 7,
                'id_module' => 50,
                'is_record' => 1,
                'name' => 'Fatturato',
                'title' => 'Fatturato',
                'directory' => 'fatturato',
                'previous' => '',
                'options' => '',
                'icon' => 'fa fa-print',
                'version' => '',
                'compatibility' => '',
                'order' => 0,
                'predefined' => 0,
                'default' => 1,
                'enabled' => 1,
            ],
            [
                'id' => 8,
                'id_module' => 50,
                'is_record' => 1,
                'name' => 'Spesometro',
                'title' => 'Spesometro',
                'directory' => 'spesometro',
                'previous' => '',
                'options' => '',
                'icon' => 'fa fa-print',
                'version' => '',
                'compatibility' => '',
                'order' => 0,
                'predefined' => 0,
                'default' => 1,
                'enabled' => 1,
            ],
            [
                'id' => 9,
                'id_module' => 31,
                'is_record' => 1,
            'name' => 'Contratto (senza costi)',
            'title' => 'Contratto (senza costi)',
                'directory' => 'contratti',
                'previous' => 'idcontratto',
                'options' => '{"pricing":false}',
                'icon' => 'fa fa-print',
                'version' => '',
                'compatibility' => '',
                'order' => 0,
                'predefined' => 0,
                'default' => 1,
                'enabled' => 1,
            ],
            [
                'id' => 10,
                'id_module' => 3,
                'is_record' => 1,
            'name' => 'Intervento (senza costi)',
            'title' => 'Intervento (senza costi)',
                'directory' => 'interventi',
                'previous' => 'idintervento',
                'options' => '{"pricing":false}',
                'icon' => 'fa fa-print',
                'version' => '',
                'compatibility' => '',
                'order' => 0,
                'predefined' => 0,
                'default' => 1,
                'enabled' => 1,
            ],
            [
                'id' => 11,
                'id_module' => 24,
                'is_record' => 1,
            'name' => 'Ordine cliente (senza costi)',
            'title' => 'Ordine cliente (senza costi)',
                'directory' => 'ordini',
                'previous' => 'idordine',
                'options' => '{"pricing":false}',
                'icon' => 'fa fa-print',
                'version' => '',
                'compatibility' => '',
                'order' => 1,
                'predefined' => 0,
                'default' => 1,
                'enabled' => 1,
            ],
            [
                'id' => 12,
                'id_module' => 25,
                'is_record' => 1,
            'name' => 'Ordine fornitore (senza costi)',
            'title' => 'Ordine fornitore (senza costi)',
                'directory' => 'ordini',
                'previous' => 'idordine',
                'options' => '{"pricing":false}',
                'icon' => 'fa fa-print',
                'version' => '',
                'compatibility' => '',
                'order' => 1,
                'predefined' => 0,
                'default' => 1,
                'enabled' => 1,
            ],
            [
                'id' => 13,
                'id_module' => 26,
                'is_record' => 1,
            'name' => 'Ddt di vendita (senza costi)',
            'title' => 'Ddt di vendita (senza costi)',
                'directory' => 'ddt',
                'previous' => 'idddt',
                'options' => '{"pricing":false}',
                'icon' => 'fa fa-print',
                'version' => '',
                'compatibility' => '',
                'order' => 0,
                'predefined' => 0,
                'default' => 1,
                'enabled' => 1,
            ],
            [
                'id' => 14,
                'id_module' => 13,
                'is_record' => 1,
            'name' => 'Preventivo (senza costi)',
            'title' => 'Preventivo (senza costi)',
                'directory' => 'preventivi',
                'previous' => 'idpreventivo',
                'options' => '{"pricing":false}',
                'icon' => 'fa fa-print',
                'version' => '',
                'compatibility' => '',
                'order' => 0,
                'predefined' => 0,
                'default' => 1,
                'enabled' => 1,
            ],
            [
                'id' => 15,
                'id_module' => 31,
                'is_record' => 1,
            'name' => 'Consuntivo contratto (senza costi)',
            'title' => 'Consuntivo contratto (senza costi)',
                'directory' => 'contratti_cons',
                'previous' => 'idcontratto',
                'options' => '{"pricing":false}',
                'icon' => 'fa fa-print',
                'version' => '',
                'compatibility' => '',
                'order' => 0,
                'predefined' => 0,
                'default' => 1,
                'enabled' => 1,
            ],
            [
                'id' => 16,
                'id_module' => 13,
                'is_record' => 1,
            'name' => 'Consuntivo preventivo (senza costi)',
            'title' => 'Consuntivo preventivo (senza costi)',
                'directory' => 'preventivi_cons',
                'previous' => 'idpreventivo',
                'options' => '{"pricing":false}',
                'icon' => 'fa fa-print',
                'version' => '',
                'compatibility' => '',
                'order' => 0,
                'predefined' => 0,
                'default' => 1,
                'enabled' => 1,
            ],
            [
                'id' => 17,
                'id_module' => 31,
                'is_record' => 1,
            'name' => 'Ordine di servizio (senza costi)',
            'title' => 'Ordine di servizio (senza costi)',
                'directory' => 'interventi_ordiniservizio',
                'previous' => 'idintervento',
                'options' => '{"pricing":false}',
                'icon' => 'fa fa-print',
                'version' => '',
                'compatibility' => '',
                'order' => 0,
                'predefined' => 0,
                'default' => 1,
                'enabled' => 0,
            ],
            [
                'id' => 18,
                'id_module' => 31,
                'is_record' => 1,
                'name' => 'Contratto',
                'title' => 'Contratto',
                'directory' => 'contratti',
                'previous' => 'idcontratto',
                'options' => '{"pricing":true}',
                'icon' => 'fa fa-print',
                'version' => '',
                'compatibility' => '',
                'order' => 0,
                'predefined' => 1,
                'default' => 1,
                'enabled' => 1,
            ],
            [
                'id' => 19,
                'id_module' => 3,
                'is_record' => 1,
                'name' => 'Intervento',
                'title' => 'Intervento',
                'directory' => 'interventi',
                'previous' => 'idintervento',
                'options' => '{"pricing":true}',
                'icon' => 'fa fa-print',
                'version' => '',
                'compatibility' => '',
                'order' => 0,
                'predefined' => 1,
                'default' => 1,
                'enabled' => 1,
            ],
            [
                'id' => 20,
                'id_module' => 24,
                'is_record' => 1,
                'name' => 'Ordine cliente',
                'title' => 'Ordine cliente',
                'directory' => 'ordini',
                'previous' => 'idordine',
                'options' => '{"pricing":true}',
                'icon' => 'fa fa-print',
                'version' => '',
                'compatibility' => '',
                'order' => 0,
                'predefined' => 1,
                'default' => 1,
                'enabled' => 1,
            ],
            [
                'id' => 21,
                'id_module' => 26,
                'is_record' => 1,
                'name' => 'Ddt di vendita',
                'title' => 'Ddt di vendita',
                'directory' => 'ddt',
                'previous' => 'idddt',
                'options' => '{"pricing":true}',
                'icon' => 'fa fa-print',
                'version' => '',
                'compatibility' => '',
                'order' => 0,
                'predefined' => 1,
                'default' => 1,
                'enabled' => 1,
            ],
            [
                'id' => 22,
                'id_module' => 13,
                'is_record' => 1,
                'name' => 'Preventivo',
                'title' => 'Preventivo',
                'directory' => 'preventivi',
                'previous' => 'idpreventivo',
                'options' => '{"pricing":true}',
                'icon' => 'fa fa-print',
                'version' => '',
                'compatibility' => '',
                'order' => 0,
                'predefined' => 1,
                'default' => 1,
                'enabled' => 1,
            ],
            [
                'id' => 23,
                'id_module' => 31,
                'is_record' => 1,
                'name' => 'Consuntivo contratto',
                'title' => 'Consuntivo contratto',
                'directory' => 'contratti_cons',
                'previous' => 'idcontratto',
                'options' => '{"pricing":true}',
                'icon' => 'fa fa-print',
                'version' => '',
                'compatibility' => '',
                'order' => 0,
                'predefined' => 1,
                'default' => 1,
                'enabled' => 1,
            ],
            [
                'id' => 24,
                'id_module' => 13,
                'is_record' => 1,
                'name' => 'Consuntivo preventivo',
                'title' => 'Consuntivo preventivo',
                'directory' => 'preventivi_cons',
                'previous' => 'idpreventivo',
                'options' => '{"pricing":true}',
                'icon' => 'fa fa-print',
                'version' => '',
                'compatibility' => '',
                'order' => 0,
                'predefined' => 1,
                'default' => 1,
                'enabled' => 1,
            ],
            [
                'id' => 25,
                'id_module' => 31,
                'is_record' => 1,
                'name' => 'Ordine di servizio',
                'title' => 'Ordine di servizio',
                'directory' => 'interventi_ordiniservizio',
                'previous' => 'idintervento',
                'options' => '{"pricing":true}',
                'icon' => 'fa fa-print',
                'version' => '',
                'compatibility' => '',
                'order' => 0,
                'predefined' => 1,
                'default' => 1,
                'enabled' => 0,
            ],
            [
                'id' => 26,
                'id_module' => 1,
                'is_record' => 1,
                'name' => 'Stampa calendario',
                'title' => 'Stampa calendario',
                'directory' => 'dashboard',
                'previous' => '',
                'options' => '',
                'icon' => 'fa fa-print',
                'version' => '',
                'compatibility' => '',
                'order' => 0,
                'predefined' => 1,
                'default' => 1,
                'enabled' => 1,
            ],
            [
                'id' => 27,
                'id_module' => 25,
                'is_record' => 1,
                'name' => 'Ordine fornitore',
                'title' => 'Ordine fornitore',
                'directory' => 'ordini',
                'previous' => 'idordine',
                'options' => '{"pricing":true}',
                'icon' => 'fa fa-print',
                'version' => '',
                'compatibility' => '',
                'order' => 0,
                'predefined' => 1,
                'default' => 1,
                'enabled' => 1,
            ],
            [
                'id' => 28,
                'id_module' => 14,
                'is_record' => 1,
            'name' => 'Fattura di vendita (senza intestazione)',
            'title' => 'Fattura di vendita (senza intestazione)',
                'directory' => 'fatture',
                'previous' => 'iddocumento',
                'options' => '{"hide_header":true, "hide_footer":true}',
                'icon' => 'fa fa-print',
                'version' => '',
                'compatibility' => '',
                'order' => 0,
                'predefined' => 0,
                'default' => 1,
                'enabled' => 1,
            ],
        ]);
    }
}
