<?php

use Update\Seed;

class ZzSettingsTableSeeder extends Seed
{
    /**
     * Auto generated seed file.
     */
    public function run()
    {
        $this->capsule->table('zz_settings')->truncate();

        $this->capsule->table('zz_settings')->insert([
            [
                'id' => 2,
                'nome' => 'Azienda predefinita',
                'valore' => '0',
                'tipo' => 'query=SELECT `an_anagrafiche`.`idanagrafica` AS \'id\', `ragione_sociale` AS \'descrizione\' FROM `an_anagrafiche` INNER JOIN `an_tipianagrafiche_anagrafiche` ON `an_anagrafiche`.`idanagrafica` = `an_tipianagrafiche_anagrafiche`.`idanagrafica` WHERE `idtipoanagrafica` = (SELECT `idtipoanagrafica` FROM `an_tipianagrafiche` WHERE `descrizione` = \'Azienda\') AND `deleted_at` IS NULL',
                'editable' => 1,
                'sezione' => 'Generali',
                'order' => 1,
            ],
            [
                'id' => 6,
                'nome' => 'Iva predefinita',
                'valore' => '91',
                'tipo' => 'query=SELECT id, descrizione FROM `co_iva` ORDER BY descrizione ASC',
                'editable' => 1,
                'sezione' => 'Fatturazione',
                'order' => null,
            ],
            [
                'id' => 7,
                'nome' => 'Tipo di pagamento predefinito',
                'valore' => '82',
                'tipo' => 'query=SELECT id, descrizione FROM `co_pagamenti` ORDER BY descrizione ASC',
                'editable' => 1,
                'sezione' => 'Fatturazione',
                'order' => null,
            ],
            [
                'id' => 8,
                'nome' => 'Percentuale ritenuta d\'acconto',
                'valore' => '',
                'tipo' => 'query=SELECT id, descrizione FROM `co_ritenutaacconto` ORDER BY descrizione ASC',
                'editable' => 1,
                'sezione' => 'Fatturazione',
                'order' => null,
            ],
            [
                'id' => 9,
                'nome' => 'Percentuale rivalsa INPS',
                'valore' => '',
                'tipo' => 'query=SELECT id, descrizione FROM `co_rivalsainps` ORDER BY descrizione ASC',
                'editable' => 1,
                'sezione' => 'Fatturazione',
                'order' => null,
            ],
            [
                'id' => 10,
                'nome' => 'Importo marca da bollo',
                'valore' => '0.00',
                'tipo' => 'decimal',
                'editable' => 1,
                'sezione' => 'Fatturazione',
                'order' => null,
            ],
            [
                'id' => 11,
                'nome' => 'Soglia minima per l\'applicazione della marca da bollo',
                'valore' => '77.47',
                'tipo' => 'decimal',
                'editable' => 1,
                'sezione' => 'Fatturazione',
                'order' => null,
            ],
            [
                'id' => 12,
                'nome' => 'Conto aziendale predefinito',
                'valore' => '',
                'tipo' => 'query=SELECT id,descrizione FROM co_pianodeiconti3 WHERE idpianodeiconti2=(SELECT id FROM co_pianodeiconti2 WHERE descrizione=\'Cassa e banche\')',
                'editable' => 1,
                'sezione' => 'Fatturazione',
                'order' => null,
            ],
            [
                'id' => 21,
                'nome' => 'Movimenta il magazzino durante l\'inserimento o eliminazione dei lotti/serial number',
                'valore' => '1',
                'tipo' => 'boolean',
                'editable' => 1,
                'sezione' => 'Magazzino',
                'order' => null,
            ],
            [
                'id' => 22,
                'nome' => 'Formato numero secondario ddt',
                'valore' => '##',
                'tipo' => 'string',
                'editable' => 1,
                'sezione' => 'Ddt',
                'order' => null,
            ],
            [
                'id' => 24,
                'nome' => 'Formato numero secondario ordine',
                'valore' => '##',
                'tipo' => 'string',
                'editable' => 1,
                'sezione' => 'Ordini',
                'order' => null,
            ],
            [
                'id' => 25,
                'nome' => 'Formato codice intervento',
                'valore' => '#',
                'tipo' => 'string',
                'editable' => 1,
                'sezione' => 'Interventi',
                'order' => null,
            ],
            [
                'id' => 26,
                'nome' => 'Formato codice preventivi',
                'valore' => '#',
                'tipo' => 'string',
                'editable' => 1,
                'sezione' => 'Preventivi',
                'order' => null,
            ],
            [
                'id' => 28,
                'nome' => 'Mostra i prezzi al tecnico',
                'valore' => '1',
                'tipo' => 'boolean',
                'editable' => 1,
                'sezione' => 'Interventi',
                'order' => null,
            ],
            [
                'id' => 29,
                'nome' => 'Formato codice anagrafica',
                'valore' => '########',
                'tipo' => 'string',
                'editable' => 1,
                'sezione' => 'Anagrafiche',
                'order' => null,
            ],
            [
                'id' => 31,
                'nome' => 'Formato codice contratti',
                'valore' => '#',
                'tipo' => 'string',
                'editable' => 1,
                'sezione' => 'Contratti',
                'order' => null,
            ],
            [
                'id' => 36,
                'nome' => 'Conto predefinito fatture di vendita',
                'valore' => '',
            'tipo' => 'query=SELECT id, CONCAT_WS(\' - \', numero, descrizione) AS descrizione FROM co_pianodeiconti3 WHERE dir=\'entrata\'',
                'editable' => 1,
                'sezione' => 'Fatturazione',
                'order' => null,
            ],
            [
                'id' => 37,
                'nome' => 'Conto predefinito fatture di acquisto',
                'valore' => '',
            'tipo' => 'query=SELECT id, CONCAT_WS(\' - \', numero, descrizione) AS descrizione FROM co_pianodeiconti3 WHERE dir=\'uscita\'',
                'editable' => 1,
                'sezione' => 'Fatturazione',
                'order' => null,
            ],
            [
                'id' => 40,
                'nome' => 'Numero di backup da mantenere',
                'valore' => '7',
                'tipo' => 'integer',
                'editable' => 1,
                'sezione' => 'Generali',
                'order' => 4,
            ],
            [
                'id' => 41,
                'nome' => 'Backup automatico',
                'valore' => '0',
                'tipo' => 'boolean',
                'editable' => 1,
                'sezione' => 'Generali',
                'order' => 3,
            ],
            [
                'id' => 43,
                'nome' => 'Utilizzare i tooltip sul calendario',
                'valore' => '0',
                'tipo' => 'boolean',
                'editable' => 1,
                'sezione' => 'Dashboard',
                'order' => 6,
            ],
            [
                'id' => 44,
                'nome' => 'Visualizzare la domenica sul calendario',
                'valore' => '1',
                'tipo' => 'boolean',
                'editable' => 1,
                'sezione' => 'Dashboard',
                'order' => 7,
            ],
            [
                'id' => 45,
                'nome' => 'Nascondere la barra sinistra di default',
                'valore' => '0',
                'tipo' => 'boolean',
                'editable' => 1,
                'sezione' => 'Generali',
                'order' => 2,
            ],
            [
                'id' => 47,
                'nome' => 'Cifre decimali per importi',
                'valore' => '2',
                'tipo' => 'list[1,2,3,4]',
                'editable' => 1,
                'sezione' => 'Generali',
                'order' => 9,
            ],
            [
                'id' => 48,
                'nome' => 'CSS Personalizzato',
                'valore' => '',
                'tipo' => 'textarea',
                'editable' => 1,
                'sezione' => 'Generali',
                'order' => 17,
            ],
            [
                'id' => 49,
                'nome' => 'Attiva aggiornamenti',
                'valore' => '1',
                'tipo' => 'boolean',
                'editable' => 0,
                'sezione' => 'Generali',
                'order' => null,
            ],
            [
                'id' => 50,
                'nome' => 'Vista dashboard',
                'valore' => 'settimana',
                'tipo' => 'list[mese,settimana,giorno]',
                'editable' => 1,
                'sezione' => 'Dashboard',
                'order' => 5,
            ],
            [
                'id' => 53,
                'nome' => 'Dicitura fissa fattura',
                'valore' => 'Ai sensi del D.Lgs. 196/2003 Vi informiamo che i Vs. dati saranno utilizzati esclusivamente per i fini connessi ai rapporti commerciali tra di noi in essere. Contributo CONAI assolto ove dovuto - Vi preghiamo di controllare i Vs. dati anagrafici, la P. IVA e il Cod. Fiscale. Non ci riteniamo responsabili di eventuali errori.',
                'tipo' => 'ckeditor',
                'editable' => 1,
                'sezione' => 'Fatturazione',
                'order' => null,
            ],
            [
                'id' => 54,
                'nome' => 'Tabelle escluse per la sincronizzazione API automatica',
                'valore' => 'zz_users,zz_permissions,zz_semaphores,zz_tokens,updates',
                'tipo' => 'string',
                'editable' => 0,
                'sezione' => 'API',
                'order' => null,
            ],
            [
                'id' => 55,
                'nome' => 'Lunghezza pagine per API',
                'valore' => '200',
                'tipo' => 'integer',
                'editable' => 0,
                'sezione' => 'API',
                'order' => null,
            ],
            [
                'id' => 56,
                'nome' => 'Attiva notifica di presenza utenti sul record',
                'valore' => '0',
                'tipo' => 'boolean',
                'editable' => 1,
                'sezione' => 'Generali',
                'order' => 13,
            ],
            [
                'id' => 57,
            'nome' => 'Timeout notifica di presenza (minuti)',
                'valore' => '15',
                'tipo' => 'integer',
                'editable' => 1,
                'sezione' => 'Generali',
                'order' => 14,
            ],
            [
                'id' => 58,
                'nome' => 'Modifica Viste di default',
                'valore' => '0',
                'tipo' => 'boolean',
                'editable' => 0,
                'sezione' => 'Generali',
                'order' => null,
            ],
            [
                'id' => 59,
                'nome' => 'Prima pagina',
                'valore' => '1',
                'tipo' => 'query=SELECT id, title AS \'descrizione\' FROM zz_modules WHERE enabled = 1 AND options != \'\' AND options != \'menu\' AND options IS NOT NULL ORDER BY `order` ASC',
                'editable' => 1,
                'sezione' => 'Generali',
                'order' => 11,
            ],
            [
                'id' => 60,
                'nome' => 'Cifre decimali per quantità',
                'valore' => '2',
                'tipo' => 'list[1,2,3,4]',
                'editable' => 1,
                'sezione' => 'Generali',
                'order' => 10,
            ],
            [
                'id' => 61,
                'nome' => 'Google Maps API key',
                'valore' => '',
                'tipo' => 'string',
                'editable' => 1,
                'sezione' => 'Generali',
                'order' => 12,
            ],
            [
                'id' => 62,
                'nome' => 'apilayer API key for Email',
                'valore' => '',
                'tipo' => 'string',
                'editable' => 1,
                'sezione' => 'Generali',
                'order' => 15,
            ],
            [
                'id' => 63,
                'nome' => 'apilayer API key for VAT number',
                'valore' => '',
                'tipo' => 'string',
                'editable' => 1,
                'sezione' => 'Generali',
                'order' => 16,
            ],
            [
                'id' => 64,
                'nome' => 'Metodologia calcolo ritenuta d\'acconto predefinito',
                'valore' => 'Imponibile',
                'tipo' => 'list[Imponibile,Imponibile + rivalsa inps]',
                'editable' => 1,
                'sezione' => 'Fatturazione',
                'order' => null,
            ],
            [
                'id' => 65,
                'nome' => 'Cambia automaticamente stato ddt fatturati',
                'valore' => '1',
                'tipo' => 'boolean',
                'editable' => 1,
                'sezione' => 'Ddt',
                'order' => null,
            ],
            [
                'id' => 66,
                'nome' => 'Cambia automaticamente stato ordini fatturati',
                'valore' => '1',
                'tipo' => 'boolean',
                'editable' => 1,
                'sezione' => 'Ordini',
                'order' => null,
            ],
            [
                'id' => 67,
                'nome' => 'Tempo di attesa ricerche in secondi',
                'valore' => '2',
                'tipo' => 'integer',
                'editable' => 0,
                'sezione' => 'Generali',
                'order' => null,
            ],
            [
                'id' => 68,
                'nome' => 'Logo stampe',
                'valore' => '',
                'tipo' => 'string',
                'editable' => 0,
                'sezione' => 'Generali',
                'order' => null,
            ],
            [
                'id' => 69,
                'nome' => 'Abilita esportazione Excel e PDF',
                'valore' => '0',
                'tipo' => 'boolean',
                'editable' => 1,
                'sezione' => 'Generali',
                'order' => 18,
            ],
            [
                'id' => 70,
                'nome' => 'Allega stampa per fattura verso Privati',
                'valore' => '0',
                'tipo' => 'boolean',
                'editable' => 1,
                'sezione' => 'Fatturazione Elettronica',
                'order' => 8,
            ],
            [
                'id' => 71,
                'nome' => 'Allega stampa per fattura verso Aziende',
                'valore' => '0',
                'tipo' => 'boolean',
                'editable' => 1,
                'sezione' => 'Fatturazione Elettronica',
                'order' => 9,
            ],
            [
                'id' => 72,
                'nome' => 'Allega stampa per fattura verso PA',
                'valore' => '0',
                'tipo' => 'boolean',
                'editable' => 1,
                'sezione' => 'Fatturazione Elettronica',
                'order' => 10,
            ],
            [
                'id' => 73,
                'nome' => 'Regime Fiscale',
                'valore' => '',
                'tipo' => 'query=SELECT codice AS id, descrizione FROM fe_regime_fiscale',
                'editable' => 1,
                'sezione' => 'Fatturazione Elettronica',
                'order' => 1,
            ],
            [
                'id' => 74,
                'nome' => 'Tipo Cassa',
                'valore' => '',
                'tipo' => 'query=SELECT codice AS id, descrizione FROM fe_tipo_cassa',
                'editable' => 1,
                'sezione' => 'Fatturazione Elettronica',
                'order' => 2,
            ],
            [
                'id' => 75,
                'nome' => 'Causale ritenuta d\'acconto',
                'valore' => '',
                'tipo' => 'query=SELECT codice AS id, descrizione FROM fe_causali_pagamento_ritenuta',
                'editable' => 1,
                'sezione' => 'Fatturazione Elettronica',
                'order' => 3,
            ],
            [
                'id' => 76,
                'nome' => 'Authorization ID Indice PA',
                'valore' => '',
                'tipo' => 'string',
                'editable' => 1,
                'sezione' => 'Fatturazione Elettronica',
                'order' => 4,
            ],
            [
                'id' => 77,
                'nome' => 'Inizio orario lavorativo',
                'valore' => '00:00:00',
                'tipo' => 'time',
                'editable' => 1,
                'sezione' => 'Dashboard',
                'order' => 1,
            ],
            [
                'id' => 78,
                'nome' => 'Fine orario lavorativo',
                'valore' => '23:59:00',
                'tipo' => 'time',
                'editable' => 1,
                'sezione' => 'Dashboard',
                'order' => 2,
            ],
            [
                'id' => 79,
                'nome' => 'Stampa per anteprima e firma',
                'valore' => '19',
            'tipo' => 'query=SELECT id, title AS descrizione FROM zz_prints WHERE id_module = (SELECT id FROM zz_modules WHERE name = \'Interventi\') AND is_record = 1',
                'editable' => 1,
                'sezione' => 'Interventi',
                'order' => 3,
            ],
        ]);
    }
}
